### ISSUE TITLE
addSpawn not working

### ISSUE THREAD

**Issue by thekazador** [superckl/BiomeTweaker#10]
i want to add monsters and creatures to my new biome (deep ocean) and this dont work:

waterBiome = forBiomes(24)
waterBiome.set("name","WaterWorld")
waterBiome.set("temperature", 0.8)
waterBiome.set("actualFillerBlock","minecraft:bedrock")
waterBiome.set("enableRain", true)
waterBiome.addSpawn("net.minecraft.entity.passive.EntitySheep", "CREATURE", 12, 4, 4)
waterBiome.addSpawn("net.minecraft.entity.passive.EntityPig", "CREATURE", 10, 4, 4)
waterBiome.addSpawn("net.minecraft.entity.passive.EntityChicken", "CREATURE", 10, 4, 4)
waterBiome.addSpawn("net.minecraft.entity.passive.EntityCow", "CREATURE", 8, 4, 4)
waterBiome.addSpawn("net.minecraft.entity.monster.EntitySpider", "MONSTER", 60, 4, 4)
waterBiome.addSpawn("net.minecraft.entity.monster.EntityZombie", "MONSTER", 100, 4, 4)
waterBiome.addSpawn("net.minecraft.entity.monster.EntitySkeleton", "MONSTER", 70, 4, 4)
waterBiome.addSpawn("net.minecraft.entity.monster.EntityCreeper", "MONSTER", 40, 4, 4)
waterBiome.addSpawn("net.minecraft.entity.monster.EntityEnderman", "MONSTER", 20, 4, 4)
waterBiome.addSpawn("net.minecraft.entity.monster.EntityWitch", "MONSTER", 10, 4, 4)

**Comment by superckl** [comment]
Can I get a full log, including loading up a world and quitting Minecraft?

**Comment by superckl** [comment]
Sorry, I'll also need your BiomeTweaker.cfg and any included script files.

**Comment by superckl** [comment]
I can confirm creatures spawning in your modified ocean biome with a clean installation of BiomeTweaker. I set the liquidFillerBlock to grass to expedite the spawning process:
![2015-05-03_22 58 42](https://cloud.githubusercontent.com/assets/2230216/7448745/11365732-f1e8-11e4-86d6-056260813bd9.png)

**Comment by thekazador** [comment]
https://drive.google.com/folderview?id=0B2QKhGCkKdnqfk5TcTU3ZFF3ZG80ZjBtUXdaVHdXazRWcEZ6VjFLOGk0a3lyUUF4LWljcms&usp=sharing

**Comment by thekazador** [comment]
i see in the log [main/ERROR] [BiomeTweakerCore/]: Failed to find meaning in command addSpawn("net.minecraft.entity.monster.EntityWitch", "MONSTER", 10, 4, 4)waterBiome.set("name","WaterWorld"). It will be ignored.
i just test for zombies and still dont spawn monsters or creatures... :(

![2015-05-04_01 17 04](https://cloud.githubusercontent.com/assets/5355867/7448849/8e850f2c-f1fb-11e4-8e73-555c85f081bf.png)

**Comment by thekazador** [comment]
another test, i just set the liquidFillerBlock to grass like you and the creatures (pig, cow, sheeps) spawn when the biome generate, but monsters dont, i think the problems is the generation over time when they can spawn, only spawn when the biome is created.

**Comment by superckl** [comment]
![2015-05-03_23 52 01](https://cloud.githubusercontent.com/assets/2230216/7448977/72201770-f1ef-11e4-93d8-0a2b0e9f4e79.png)
Definitely getting mobs...

**Comment by thekazador** [comment]
can i get your script file? i cant get it work really sorry

**Comment by superckl** [comment]
I can definitively confirm hostile mobs are spawning regularly. I have yet to see a passive mob spawn while I wan in the world though. I've asked @jadedcat if she can confirm passive mobs can spawn in the ocean, as she has done this in AG2.

**Comment by thekazador** [comment]
ok the problem is the grass Y position, like your picture, we have to put the grass two blocks aver the water or they dont spawn, really thx, btw..... this cannot be?

**Comment by superckl** [comment]
I'll look into this more. What you describe seems to be the case and explains why it works in AG2. I'll let you know when I have more information.

**Comment by superckl** [comment]
I've done some more testing. I've confirmed that hostile mobs can spawn on grass that is at least one block above the water, but I have not seen any on the same level as the water.
![2015-05-05_23 09 51](https://cloud.githubusercontent.com/assets/2230216/7487792/64a49788-f384-11e4-85a2-3dde3ce3828b.png)
![2015-05-05_22 48 37](https://cloud.githubusercontent.com/assets/2230216/7487794/6bb1d676-f384-11e4-87db-07f1d07241cc.png)

I have yet to see a single passive mob spawn... It's strange because I've been playing AG2 lately, and JadedCat has nearly the same script. Mobs do spawn in ocean biomes in that pack, given that there is no actual water. This leads me to believe the cause is the water, but I can't pick out anything in the spawning code. I'll keep testing. Anything you can try out helps a bunch.

**Comment by thekazador** [comment]
1 block over water spawn mobs.
3 blocks over water spawn creatures.

**Comment by superckl** [comment]
Fixing this would require overhauling a portion of the spawning code, something I'm not going to do with BiomeTweaker. I'm going to consider it as an unfortunate side effect.
