### ISSUE TITLE
Foliage/grass color overrides ineffective in BOP biomes + some vanilla biomes.

### ISSUE THREAD

**Issue by TitusArmillius** [superckl/BiomeTweaker#100]
savannaBiome = forBiomes(35)
savannaBiome.set("foliageColor", 13413215)
savannaBiome.set("grassColor", 13413215)

The above code does not change the savanna biomes grass/foliage color, similar ineffectiveness has been found with attempts to change the color of some other BOP biomes, such as Xeric Shrubland. I suspect this is entirely to do with BOP, since BOP does modify the savanna biome. 

https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.10.2-5.0.x/src/main/java/biomesoplenty/common/biome/vanilla/BiomeExtSavanna.java

**Comment by superckl** [comment]
I'll look into this as soon as I have some free time from classes.

**Comment by kragnoth** [comment]
As a side note, the BoP compatibility classes never seem to get loaded.  Looking at the code, the text that is supposed to be written in the logs when BoP integration is loaded never gets added to the logs.  Log also says that it fails to find meaning in any of the BoP commands.

**Comment by superckl** [comment]
Turns out the color overrides not working was a bug. You're right that BOP overrides it, but I have ASM code that is supposed to fix that (that wasn't working).

Give the latest a build a try and let me know.

http://jenkins.superckl.me/job/BiomeTweaker%201.11/246/

**Comment by kragnoth** [comment]
Thanks, sorry for the late reply, I don't check my gmail very often.

**Comment by kragnoth** [comment]
246 doesn't seem to override grass/foliage color in BoP biomes.  This was pulled straight from jenkins regular, not dev.

**Comment by kragnoth** [comment]
Alright, biome colors are working for BoP support, but only one BoP world type.  If you are using the BoP  support on another world type it doesn't do the color modifications. (the part where you override it so BoP biomes spawn in vanilla default, but make it so world gen still happens in those biomes instead of being just dirt)

**Comment by kragnoth** [comment]
Weird things are happening.  Thought it had fixed it, but the only BoP biome that seems to be working with an override is the outback biome.  I'll edit this with a further list as I move around.

**Comment by superckl** [comment]
Closing this since it's on 1.10.2. Please verify that this is still an issue on 1.11.2 and I'll reopen it.
