### ISSUE TITLE
Biome inconsistencies at border chunks

### ISSUE THREAD

**Issue by hgsbsn** [superckl/BiomeTweaker#101]
With these scripts installed, borders between biomes become problematic. There is no problem between the "coniferous forest," "river," and "dust field" biomes, but the problem crops up around the borders of the mountainous biomes: "Stone hills," "siltstone hills," "limestone hills," "Gypsum peaks," and "Shale peaks." Essentially, certain chunks on the borders between these biomes and other biomes end up having the wrong block as the top and filler blocks. This is consistent for the entire 16x16 square chunk. The block that becomes the top and filler blocks is always the block between the top layers and bedrock, where a vanilla world would have stone. It looks like this:

http://imgur.com/a/gduZ7

The height variation of the biomes does not affect this, I have tried it with the "stone hills" biome set to the same height as the "coniferous forest" biome and these chunk-sized errors persist.

It's worth noting that biomes o'plenty is in the client, as well as these mods:
AutoRegLib
Baubles
Biomes O' Plenty
Botania
Ex Nihilo Adscencio
Jurassicraft
LLibrary
Quark

Scripts:

https://gist.github.com/superckl/80b9bf4e7b623fc21f19c11901cae004

**Comment by superckl** [comment]
I've moved your scripts to a gist to save space on this issue thread. I'll be looking into this as soon as I have some free time from classes.

**Comment by superckl** [comment]
Please confirm that this is still an issue on the latest dev builds for 1.11.2. I haven't been able to reproduce this myself, but I believe I fixed this issue while fixing something else. I'll re-open the issue if it is.
