### ISSUE TITLE
[Script Help]  How to disable abandoned mineshafts

### ISSUE THREAD

**Issue by addrever** [superckl/BiomeTweaker#102]
Is there currently a way to stop the spawn of abandoned mineshafts?

Currently using:
Minecraft 1.10.2
Forge 12.18.3.2221
Biome Tweaker 2.1.230

**Comment by superckl** [comment]
No, they're hard-coded into Chunk Providers. Not planning on adding this feature anytime soon. I know there are other mods that will let you do that.
