### ISSUE TITLE
Getting entity Id's

### ISSUE THREAD

**Issue by Winddbourne** [superckl/BiomeTweaker#106]
The id's used to add an entity to generation are not the same as the entity id's used by minecraft. For example EntityPigZombie gives me zombie pigmen spawning in the overworld . . . which was great. But minecraft lists the zombie pigman's entity id as "Zombie_Pigman" . . . it isn't the same. 

Doing some research I figured out that your code is referencing a forge entity data. But looking around online I couldn't find a complete listing of these ID's. I specifically wanted to add shulkers to overworld generation in some forested regions. 

The closest data I could find is here:

https://takahikokawasaki.github.io/minecraft-resources/javadoc/forge/1.8-11.14.1.1320/net/minecraft/entity/monster/package-tree.html

But it's obviously older and doesn't contain information for the Shulker. So how would I go about getting this ID and others? My first thought was to look in the output for The_End but it only listed Endermen among the registered spawns.

**Comment by superckl** [comment]
You're right that this feature needs some updates.

College life doesn't allow me enough time to do more than directly port BT between versions. It was initially constructed on 1.7.10, so a lot of the nuances and internal changes between 1.7.10 and 1.11 haven't been reflected in BiomeTweaker. There's a lot of features that need to be rebuilt on the 1.11 structure. Eventually I'll get to it...

**Comment by superckl** [comment]
All the features you need should be implemented now. Give them and a try and let me know.

http://jenkins.superckl.me/job/BiomeTweaker%201.11/245/

**Comment by Winddbourne** [comment]
This looks really good I'll give it a try ASAP. Right now I'm taking care of a sick wife and child. Great job getting this worked on with college. My wife is doing full time college and school so I know what that is like. :)

**Comment by Winddbourne** [comment]
Sick now myself but I finally had a moment to look at it. It looks good, but it has one major flaw . . . it requires 1.11.2. I did immediately consider upgrading but my test pack found that a lot of important mods still are living at 1.10.2 or lower only. Tinkers construct and immersive engineering both happen to be counted among the missing. 

I may use my test profile to simply run the commands to get the codes I need though. lol

**Comment by Seth0067** [comment]
+1 for entity output on 1.10.2 when you can, please. TiA.

**Comment by superckl** [comment]
Going to close this. No guarantee for a back-port to 1.10.2.
