### ISSUE TITLE
Eeek! The world is flooded!

### ISSUE THREAD

**Issue by Winddbourne** [superckl/BiomeTweaker#108]
All = forAllBiomes()
All.set("height",-2.5)

![2017-03-11_15 29 48](https://cloud.githubusercontent.com/assets/24589533/23826691/cbe6fbfc-066f-11e7-8264-2155b6374a5c.png)

![2017-03-11_15 30 20](https://cloud.githubusercontent.com/assets/24589533/23826692/cdafbcda-066f-11e7-8563-a5c4789336a3.png)

Yeah . . . I think you can see the problem. Setting the height worked just fine. Biomes are generating at a starting level of 26 but . . . apparently there is a sea level I should be resetting as well. So what I get is waterworld. My birch forest isn't just lower on the map, it's completely flooded. The entire world is one big ocean. 

Now my goal wasn't to flood the world. I'm using RTG and it adds in some pretty tall terrain generation so I was fiddling with biome generation height as a way to lower the number of blocks per chunk with all those tall trees and mountains. 

Obviously what I got was surprising. Is there a way to lower the water level? lol

**Comment by superckl** [comment]
Short answer is no.

Long answer is yes but it would break everything and require egregious amounts of time to implement properly. Perhaps another mod has?
