### ISSUE TITLE
Crash java.lang.ArithmeticException: / by zero

### ISSUE THREAD

**Issue by BlayzerQ** [superckl/BiomeTweaker#109]
Crash-report: http://pastebin.com/yT88bRqw
Script: http://pastebin.com/CMv4x2PM
Its start when i try remove all other biomes
#Remove other biomes
all = forAllBiomes()
all.remove()
MC version 1.10.2
BT version 1.10.2-2.1.230

**Comment by BlayzerQ** [comment]
I`m fix it:
#Remove other biomes
other = forAllBiomesExcept(2, 17, 7, 44, 49, 63, 73, 76, 85, 88, 89, 92, 95, 101)
other.remove()

**Comment by superckl** [comment]
https://github.com/superckl/BiomeTweaker/wiki/On-the-Topic-of-Biome-Generation#why-does-removing-too-many-biomes-cause-a-crash-can-i-fix-it
