### ISSUE TITLE
registerGenBlockRep dont work on Ores?

### ISSUE THREAD

**Issue by BlayzerQ** [superckl/BiomeTweaker#110]
Script dont work:
desertD = forBiomes(2)
desertD.registerGenBlockRep("minecraft:diamiond_ore", "minecraft:sand")
desertD.registerGenBlockRep("minecraft:iron_ore", "minecraft:sand")
desertD.registerGenBlockRep("minecraft:redstone_ore", "minecraft:sand")
desertD.registerGenBlockRep("minecraft:lapis_ore", "minecraft:sand")
desertD.registerGenBlockRep("minecraft:gold_ore", "minecraft:sand")
desertD.registerGenBlockRep("ic2:resource", "minecraft:sand")
Its dont work?

**Comment by superckl** [comment]
https://github.com/superckl/BiomeTweaker/wiki/On-the-Topic-of-Block-Replacement

```
Chunk Creation -> Stone Maps placed (Stone and Water) -> BT Block Replacement -> Biome Top and Filler Block placement -> Biome Decoration placement
```
Ores are placed after block replacement occurs (decorations).
