### ISSUE TITLE
Tweaking with MoCreatures

### ISSUE THREAD

**Issue by gdarai** [superckl/BiomeTweaker#111]
I want to create a dangerous ocean, full of sharks... using Mo Creatures and BiomeTweaker.

Well, I created test script:
`ocean = forAllBiomes()`
`ocean.removeAllSpawns("CREATURE")`
`ocean.removeAllSpawns("WATER_CREATURE")`
`ocean.removeAllSpawns("CAVE_CREATURE")`
`ocean.removeAllSpawns("MONSTER")`

`ocean.set("topBlock", "minecraft:sand")`
`ocean.set("fillerBlock", "minecraft:sand")`

`ocean.addSpawn("drzhark.mocreatures.entity.aquatic.MoCEntityShark", "WATER_CREATURE", 15000, 50, 60)`

Which caused generation of ocean json like this:
`  "Spawnable Water Creatures": [`
`    {`
`      "Entity Class": "drzhark.mocreatures.entity.aquatic.MoCEntityShark",`
`      "Weight": 15000,`
`      "Min Group Count": 50,`
`      "Max Group Count": 60`
`    }`
`  ],`

Well, I have some small bands of sharks wandering the land, in mountains, on deserts, but no sharks in the sea... can you give me a tip, why? Thank you,
Darai.

**Comment by superckl** [comment]
You added sharks to every biome. Only add them to the ocean.

**Comment by gdarai** [comment]
Hello,

thanks for the quick reply.
Yes I know I created the 'ocean' as all biomes... that is because it seemed to do nothing to ocean itself, so I wanted to try if it does somthing at least to some other biome.

And it does... which is the strange thing. I just tried what you suggested and unfortunately this simple hack didn't worked.

`allB = forAllBiomes()`
`ocean = forBiomes(0)`
`allB.removeAllSpawns("CREATURE")`
`allB.removeAllSpawns("WATER_CREATURE")`
`allB.removeAllSpawns("CAVE_CREATURE")`
`allB.removeAllSpawns("MONSTER")`

`ocean.addSpawn("drzhark.mocreatures.entity.aquatic.MoCEntityShark", "WATER_CREATURE", 15000, 50, 60)`

**Comment by superckl** [comment]
Closing this because it's so old. If you are still having this issue on 1.12, please let me know.

**Comment by jaz000** [comment]
I am having this problem on 1.12 with the current version of everything

removeAllSpawns("WATER_CREATURE") doesn't remove entries from mo creatures from the biome info files (if they are refreshed with /btoutput the original entries are still there).

Also no water creatures spawn in river or oceans - co-incidence? perhaps not.
mo creatures might be doing something weird, don't know if anyone can work out what?
