### ISSUE TITLE
Superflat ocean

### ISSUE THREAD

**Issue by gdarai** [superckl/BiomeTweaker#112]
Hello,
I am trying to create infinite ocean, but the ocean biome still has some tedious islands. Can I get rid of those somehow? I thought setting height to -1 and heightVariation to 0 is enough but obviously I was wrong...

Thanks,
Darai.

**Comment by superckl** [comment]
You can set height to be very low, but you may still have some mountains and little islands. It's just how default generation works.
There might be a mod out there for ocean worlds? I don't know.
