### ISSUE TITLE
[1.7.10] Crash - incompatibility?

### ISSUE THREAD

**Issue by Cronosus** [superckl/BiomeTweaker#115]
Hello
i have this crash, even i dont use any own scripts.. game not fully crashing, just cant create or join any world
https://paste.ee/p/Tqp6S

i think ist incompatibility with Parzi's star wars mod, because when i remove it from mods, then no crashing
Can you please help me?
thanks in advance

**Comment by superckl** [comment]
The 1.7.10 branch is no longer supported. If you're still having issues on 1.10.2+, please open a new issue.
