### ISSUE TITLE
Is there any way to make a custom biome "inherit" properties?

### ISSUE THREAD

**Issue by zxz41** [superckl/BiomeTweaker#116]
I've spend a few hours looking for something like it on the wiki. Am I missing something?
I'm trying to add slightly more variations to vanilla biomes (like how Roofed Forest have a Roofed Forest M variant).
The closest I could find was 'intersectionOf' and 'subtractFrom' but the description is really confusing.

**Comment by superckl** [comment]
No, there is currently no way to do that. I'll look into adding it in the future.

Right now, you have to look in the output files and use whatever values you need.

**Comment by superckl** [comment]
Feature is now available in dev builds. Will be released when version 3.0 is ready.
