### ISSUE TITLE
Open Terrain Generator

### ISSUE THREAD

**Issue by ghost** [superckl/BiomeTweaker#117]
have you thought about working together with the open terrain generator mod (continuation of terrain control) authors? their mod already includes the ability to create new custom biomes, structures and much more, but i think your mod goes a bit more in detail when it comes to biomes. so it would be great if you could join the otg development, since i think yours and their mod have similar audiences and everyone would benefit from a merger.

maybe you could also help them out with their oceans (https://github.com/superckl/BetterOceans) :D

**Comment by superckl** [comment]
They haven't reached out to me, so, no, I haven't. If they feel a merge would be a good idea, they can suggest it to me. Perhaps some integration might be a better idea (and easier). I haven't really looked much into it though.
