### ISSUE TITLE
biome tweaker isn't working

### ISSUE THREAD

**Issue by shaun98** [superckl/BiomeTweaker#118]
I'm using windows 10, installed the mod, and found out the scripts don't work.

**Comment by superckl** [comment]
Okay. I'd love to help, but you've given me no information.

**Comment by shaun98** [comment]
I want to make it snow in the plains biome, so I created a configuration file in the scripts folder and in the config file I typed:
plainsbiome = forbiomes("minecraft:plains")
plainsbiome.set("temperature", 0.1)
plainsbiome.set("enableSnow", true)
then I opeded minecraft and created a new world and no changes were made to the plains biome. I am using version 3.0 of the mod.

**Comment by superckl** [comment]
You typed `forbiomes`. The command is `forBiomes`.

**Comment by shaun98** [comment]
Thank you
