### ISSUE TITLE
genWeight and Biomes of Plenty

### ISSUE THREAD

**Issue by Kaelten** [superckl/BiomeTweaker#12]
Here's the config I'm testing with... 

    allBiomes = forAllBiomes()
    allBiomes.set("genWeight", 5)

    plains = forBiomesOfTypes("PLAINS")
    plains.set("genWeight", 200)

    hills = forBiomesOfTypes("HILLS")
    hills.set("genWeight", 100)

    mountains = forBiomesOfTypes("MOUNTAIN")
    mountains.set("genWeight", 50)

    hots = forBiomesOfTypes("HOT")
    hots.set("genWeight", 50)

    deads = forBiomesOfTypes("DEAD")
    deads.set("genWeight", 50)

    forests = forBiomesOfTypes("FOREST")
    forests.set("genWeight", 5)

    colds = forBiomesOfTypes("COLD")
    colds.set("genWeight", 5)

    desireables = forBiomes(52, 105, 42, 40, 99, 57, 80)
    desireables.set("genWeight", 75)

Seems to result in BoP biomes not generating.  Not sure if this is related to the other issue I reported or not.

**Comment by superckl** [comment]
Would you mind packing the output folder into a .zip and uploading it somewhere?

**Comment by Kaelten** [comment]
Here it is. https://www.dropbox.com/s/ipujmq38sr70ikz/BiomeOutput.zip?dl=0

I however don't see a genWeight in the output.

**Comment by superckl** [comment]
I was able to find several BOP Biomes in world using the script you provided. Are you sure you've set the level type to Biome O Plenty? If I recall correctly BOP biomes will not generate unless you do.

**Comment by Kaelten** [comment]
Oh gah, that's what I  get for doing late night testing... sorry about that.

Bryan McLemore
Kaelten

**Comment by superckl** [comment]
Haha, it's totally fine!

**Comment by Outfluence** [comment]
This should also work, but it doesn't-

tiagas = forBiomes(5, 19, 30, 31, 32, 33, 133, 158, 160, 161)
forests = forBiomes(4, 132, 18, 27, 155, 28, 156, 29, 157, 56, 97)
swampy = forBiomes(6, 134, 43, 44, 73, 71, 75, 58, 68, 107, 89, 96) 
tropics = forBiomes(21, 149, 22, 23, 151, 57, 109, 83, 85, 91, 93, 101, 64) 
woods = forBiomes(45, 48, 50, 55, 103, 72, 108, 79, 82, 84, 86, 112, 87, 114)
hills = forBiomes(3, 131, 20, 34, 162, 40, 104, 76, 66, 67)
snowy = forBiomes(10, 11, 12, 140, 13, 26, 104, 40, 41, 60, 106, 120, 51, 94)
bland = forBiomes(46, 81, 111, 88, 92, 37, 165, 38, 166, 39, 167, 35, 163, 36, 164)
thriving = forBiomes(48, 61, 63, 65, 70, 122, 74, 77) 
barren = forBiomes(53, 54, 123, 78, 110, 113, 90, 102, 95, 98, 2, 130, 17)
pretty = forBiomes(59, 49, 62, 69, 80, 1, 129)

tiagas.set("genWeight", 1)
forests.set("genWeight", 100)
swampy.set("genWeight", 325)
tropics.set("genWeight", 240)
woods.set("genWeight", 290)
hills.set("genWeight", 80)
snowy.set("genWeight", 2)
bland.set("genWeight", 500)
thriving.set("genWeight", 225)
barren.set("genWeight", 760)
pretty.set("genWeight", 30)
