### ISSUE TITLE
bring back sensationcraft

### ISSUE THREAD

**Issue by opstwotwin** [superckl/BiomeTweaker#120]
ok :)

**Comment by superckl** [comment]
Who are you and how do you know that name

**Comment by opstwotwin** [comment]
I'm just an old sensationcraft player lol.
I think i started to play in that server in around 2012 or something, the thing I most used to love was the beautiful community...
But then all dissapeared, I got very sad, until I heard about a new of Sensationcraft re-opening, It was true! the server opened again and I was very happy, but it was not the same.
The players I used to know all disappeared, the map and the plugins wheren't the same too, I was sad because of this and left the server.
A day I tried to join the server one more time, but it was closed, and that was the end of all of this.

I just wanted to vent :b
