### ISSUE TITLE
Do Decorations work?

### ISSUE THREAD

**Issue by davqvist** [superckl/BiomeTweaker#124]
So, I was reading the documentation of how decorations work and tried to test it.
I tested different placement stages (mainly PRE_DECORATION and POST_ORES) without any luck.
So in my world I set the world with JED to one biome, the Volcanic Island which has the Ash Block as the Top and Filler Block but I set them manually as well to make sure. I selected a random block to spawn as decoration to test it (Vanilla Bone Block in this case) but couldn't see any. I played around with Count and Radius values without anything happening either. So is this the same issue as in #122 or is this a new issue or am I doing something wrong?

BT 3.1.301
BTCore 1.0.16
MC 1.12.1
Forge 2456

(Still don't get any fml-client-latest.log in case you are wondering, haven't figured that out yet)

Example script:

standardBiome.set("topBlock", "biomesoplenty:ash_block")
standardBiome.set("fillerBlock", "biomesoplenty:ash_block")

Tweaker.setPlacementStage("PRE_DECORATION")
clusterDec = newClusterDecoration()
clusterDec.setCount(5)
clusterDec.setBlock("minecraft:bone_block")
clusterDec.setRadius(3)
clusterDec.addSoilBlock("biomesoplenty:ash_block")

**Comment by superckl** [comment]
You need to add the decoration to your biome.

```
standardBiome.addDecoration(clusterDec)
```

**Comment by davqvist** [comment]
Oh sorry, of course. Sorry for the derp.
