### ISSUE TITLE
BiomeTweaker doesn't work on dedicated server

### ISSUE THREAD

**Issue by davqvist** [superckl/BiomeTweaker#125]
Wanted to include BiomeTweaker now already without any tweaks on the server in my test pack to see if it works and indeed it prevented the server from starting. The crash log is not very clear (https://pastebin.com/JsZ5YeG6) and the normal log had nothing in it, but in the console I found this (https://pastebin.com/w4p1BySA) which might help you finding the issue.

BiomeTweaker 1.12.1-3.1.301
BiomeTweakerCore 1.12.1-1.0.16
Forge 2459
MC 1.12.1

**Comment by superckl** [comment]
Could be a version issue... Could you try Forge versions around 2448? Maybe start with 2449 and a few versions after that. BiomeTweaker is compiled against 2448, and there might have been a change in recent versions. I think 2448 has a bug with startup though.

**Comment by davqvist** [comment]
It will be hard for me to downgrade the server because of a lot of other mods and people playing on it. I was hoping you could test when you come back from vacation. If you can't replicate, I look what I can do.

**Comment by superckl** [comment]
All right, I'll look into it when I get back. These sort of issues are to be expected when working with non-recommended versions.

**Comment by superckl** [comment]
Please verify this issue is now resolved. I'll re-open the issue if it isn't.
