### ISSUE TITLE
disable ore gen and tree gen ?

### ISSUE THREAD

**Issue by ghost** [superckl/BiomeTweaker#126]
i read wiki so hard about few hour and it seems there is no "remove" command on decoration feature
so i tried to replace all ore to stone but it does not work. it still generate ores.
here is my script

`unNecessaryBiomes = forBiomes(37,38,39,165,166,167)
all = forAllBiomes()
unNecessaryBiomes.remove()
all.removeAllSpawns("CREATURE")

Tweaker.setStage("PRE_INIT")
all.set("treePerChunk", 20)
Tweaker.setStage("FINISHED_LOAD")
 
all = forAllBiomes()
 
all.registerGenBlockRep("minecraft:coal_ore","minecraft:stone")
all.registerGenBlockRep("minecraft:redstone_ore","minecraft:stone")
all.registerGenBlockRep("minecraft:lapis_ore","minecraft:stone")
all.registerGenBlockRep("minecraft:iron_ore","minecraft:stone")
all.registerGenBlockRep("minecraft:gold_ore","minecraft:stone")
all.registerGenBlockRep("minecraft:diamond_ore","minecraft:stone")
all.registerGenBlockRep("minecraft:emerald_ore","minecraft:stone")

all.set("genVillages",false)

all.set("genStrongholds",false)`

what i want is "remove all mesa biome" , "disable all tree gen" , "disable all ore gen" , "disable Villages and Dungeon gen" and "disable all animals gen"
it seems like "remove all mesa biome" , "disable Villages and Dungeon gen" and "disable all animals gen" works fine
but i can not disable tree gen and ore gen

i put replace code in pretty every stage include PlacementStage.
and still does not work.
can i get some help?

**Comment by ghost** [comment]
i checked world and it seems like dungeon still generate too
cause i found a end portal dungeon :/

**Comment by superckl** [comment]
What version of Forge and BiomeTweaker are you using? Can you provide a full log please?
