### ISSUE TITLE
Block replacement works only for around every other chunk

### ISSUE THREAD

**Issue by davqvist** [superckl/BiomeTweaker#127]
Forge 2460
MC 1.12.1
BT 3.1.303
BTCore 1.0.18

latest log: https://gist.github.com/davqvist/7bad7535c73abffec75d334b66bdebf8
(still haven't figured out why I don't get fml-client, I apologize)
Some screenshots: http://i.imgur.com/ZztRyCZ.png, http://i.imgur.com/IENYKQ6.png
My script: https://pastebin.com/B8EE39C2 (currently testing with adding decorations, so ignore the weird current state)

It's weird. For some parts several chunks are working fine, but there are always several chunks that didn't get affected by block replacements. Cuts are exactly on chunk border, distribution seemingly random.

**Comment by superckl** [comment]
Have you tried different placement stages? See if this occurs with all stages.

I can't seem to reproduce this in a development environment. Might be a compatibility issue.

**Comment by davqvist** [comment]
Disabling decorations fixed it, for reference, the working script where I just commented out the decorations:

https://pastebin.com/2Sw7z3b5

**Comment by superckl** [comment]
I think I know what the issue is, but I'll need a bit more information... The log you posted above seems to be incomplete. Can you post the entire log?

**Comment by davqvist** [comment]
I don't think it's incomplete. For big files on gist, you need to click the link on the top to show the full file. Did you click that?

**Comment by superckl** [comment]
I... totally knew about that. I've added a small tweak, please try it out and see if the issue still persists. If it doesn't please give me an updated log file.

**Comment by davqvist** [comment]
304 still not working unfortunately, log: https://gist.github.com/davqvist/ebb03f9b3af14c5dc573c2ba2c847187

In case it was not clear, decorations ARE working, just break replacements.

**Comment by davqvist** [comment]
Did some more tests, commentating out standardBiome.addDecoration(clusterDec) fixes it, so it is indeed adding decorations that breaks it.

**Comment by superckl** [comment]
I've identified the cause of this issue. Because you've set the radius of your cluster decoration so large, it causes cascading chunk loading. For some reason I'm unsure of, this is what is breaking replacement. The interesting thing is, it is only broken for the "PRE_ORES" and "POST_ORES" stages.

There are a couple ways to work around this:
1. Use a different stage such as "PRE_DECORATE".
2. Reduce the size of your cluster decoration and increase the count.

I have a feeling the underlying issue is in Minecraft itself, and thus beyond my ability to fix. Just don't do block replacement during any "XXX_ORES" stage. Let me know if that works for you.

**Comment by davqvist** [comment]
Oh, makes totally sense. I can try 2.) in a bit, but 1.) I'm confused about. I already used PRE_DECORATE. Or do you mean to change the block replacement to PRE_DECORATE? Isn't that way too late?

**Comment by superckl** [comment]
PRE_DECORATE happens before PRE_ORES. The order is:

```
BIOME_BLOCKS -> PRE_POPULATE -> PRE_DECORATE -> PRE_ORES -> POST_ORES -> POST_DECORATE -> POST_POPULATE
```

**Comment by davqvist** [comment]
Oh, I didn't know that, makes much more sense now. I will test.
