### ISSUE TITLE
Question/Bug? remove BOP Features/Generators

### ISSUE THREAD

**Issue by davqvist** [superckl/BiomeTweaker#128]
Forge 2460
MC 1.12.1
BT 3.1.304
BTCore 1.0.18

Biome json: https://pastebin.com/8sVYv25P
So I want to test a few things by removing BOP Features, so I tested removeGeneratorBOP.
So what do I need to use as argment for it if I want to replace lava lakes? Is it lava_lakes, lakes, SAND or what? But no matter what I use, I get something like this:

'Failed to parse arguments for command removeGeneratorBOP("lava_lakes")'

Is it not ported yet maybe? Or am I doing something wrong?

**Comment by superckl** [comment]
Thanks for the report. It was an issue with BOP command registration. Broke a while back but I never tested them.
