### ISSUE TITLE
disable sun/moon horizon?

### ISSUE THREAD

**Issue by resinate** [superckl/BiomeTweaker#129]
any chance of disabling sun/moon and their horizons?

**Comment by superckl** [comment]
No. That part of vanilla rendering is not exposed to mods nor is it done on a biome-specific basis. The best you can do is change the sky color.

**Comment by resinate** [comment]
if its vanilla how did deep dark dim do it lol

**Comment by superckl** [comment]
I never said custom dimensions can't turn it off. I said it's not exposed and thus outside the scope of BiomeTweaker.
