### ISSUE TITLE
crash with forge essential

### ISSUE THREAD

**Issue by cbcercas** [superckl/BiomeTweaker#13]
I get a crash with forgeessentials-1.7.10-1.4.0-beta7.jar and BiomeTweaker-1.7.10-0.7.49.jar on forge-1.7.10-10.13.3.1387
here the log : https://clitxt.com/t/q5z-1430758532.txt

I get the same with BiomeTweaker-1.7.10-0.8.65.jar

the report on forge essential tracker [#1471](https://github.com/ForgeEssentials/ForgeEssentialsMain/issues/1471)

**Comment by superckl** [comment]
Seems to be related to ForgeEssentials/ForgeEssentialsMain#1449. Note entirely sure about fixing it on my side at the moment. I'll have to see what I can do.

**Comment by superckl** [comment]
Just an update: Even enabling BiomeTweaker's light ASM mode does not fix the issue. As such, I'm very doubtful I will be able to fix this from my end. Light ASM mode has BiomeTweaker do only the ASM tweaking it needs to function. If it still doesn't work, I'm not sure what can be done.

**Comment by superckl** [comment]
Not going to fix this on my end, so you should be watching their releases for a fix.
