### ISSUE TITLE
confine modding biomes to dim id?

### ISSUE THREAD

**Issue by resinate** [superckl/BiomeTweaker#131]
is there a way to white list the dim ids for biome replacements? cuz some mods that create more worlds and stuff also get affected

could be like replaceallbiomesdimID(0)

**Comment by superckl** [comment]
Short answer: No, there is currently no way to do so. 

Long answer: Dimension information is not passed to the gen layers. In the future, it may be possible if the events are updated to include it. I don't see it happening the near future though.
