### ISSUE TITLE
Breaking lag

### ISSUE THREAD

**Issue by Catoptrix** [superckl/BiomeTweaker#132]
The mod is amazing but i'm having a lag problem:

Creative Mode the breaking is fine but in Survival I have breaking lag. Need to break a tree block 2-3 times before it gets registered.

Using these mods:
- Minecraft 1.12.1
- BetterFoliage MC1.12-2-1-10
- BiomesOPlenty-1.12-7.0.0.2291-universal
- BiomeTweaker-1.12.1-3.1.306
- BiomeTweakerCore-1.12.1-1.0.21
- ChunkAnimator-MC1.12-1.2
- Optifine:1.12.1_HD_U_C5

World is an Amplified World and uses this BiomeTweaker script: 

[test2.zip](https://github.com/superckl/BiomeTweaker/files/1297323/test2.zip)

Everything in the BiomeTweakerCore is set on "True".

Maybe the logs helps too:

[fml-client-latest.zip](https://github.com/superckl/BiomeTweaker/files/1297295/fml-client-latest.zip)

What is also strange that in the output dimension i get 2 Nethers:

- Nether (_nether)
- the_nether (_nether)

both are set to -1, is that a problem?

thx in advance

**Comment by superckl** [comment]
Nothing in your script should be causing lag from BT's side. Please remove all superfluous mods (Optifine, chunk animator, better foliage) and see if the issue still persists. Amplified worlds are inherently more taxing on your computer as well...

**Comment by Catoptrix** [comment]
Hi even installed a shader now and didn't have the problem again. Thanks for analyzing my script.
