### ISSUE TITLE
weighted registerGenBlockRep not working

### ISSUE THREAD

**Issue by Thyriel** [superckl/BiomeTweaker#134]
The wiki example for weighted registerGenBlockRep doesn't work ?
`allBiomes.registerGenBlockRep("minecraft:stone", "minecraft:sandstone", 1)`

throws an error in logfile:
[01:07:12] [main/ERROR] [SuperScript/biometweaker]: Failed to parse arguments for command registerGenBlockRep("minecraft:stone", "minecraft:sandstone", 1). It will be ignored.

without the ", 1" in the end it works fine.

Version: 1.12 3.1.306

**Comment by superckl** [comment]
The weight goes first. If you want to specify metadata, you need to use the new blocks objects.

```
allBiomes.registerGenBlockRep(1, "minecraft:stone", "minecraft:sandstone")
```

**Comment by Thyriel** [comment]
Thx. You should probably update the wiki then (on the topic of ore generation)
