### ISSUE TITLE
Can't start a World [1.7.10]

### ISSUE THREAD

**Issue by Kuranara** [superckl/BiomeTweaker#135]
While loading everything is fine, but when I want to create or join a World my Minecraft goes into a frozen state, althought I didn't even touch the configs, I looked at them but couldn't figure out what is causing it.

Log:

https://pastebin.com/U7zLt6AC

**Comment by superckl** [comment]
I'm sorry you're having an issue. However, I don't see what's wrong immediately, and I no longer support 1.7.10. The best you can do is try the beta 2.x.x versions and see if they work.
