### ISSUE TITLE
Startup Crash on 1.12.2

### ISSUE THREAD

**Issue by brisingraerowing** [superckl/BiomeTweaker#136]
I get a startup crash on 1.12.2 referencing BiomeTweaker.

[Crash Log](https://gist.github.com/BrisingrAerowing/6d7cac4f8cd65b456ebba79ec0e5d54a)

Not sure what went wrong there.

I use BT to replace the BOP Wastelands biome with Desert.

**Comment by superckl** [comment]
What version of BiomeTweaker are you using?

**Comment by brisingraerowing** [comment]
I'll have to check when I get back to my computer.

**Comment by brisingraerowing** [comment]
According to the log 3.1.306

**Comment by superckl** [comment]
I'll go ahead and say this then, if you aren't using the latest development build, this has already been fixed. I haven't released the fix to CurseForge yet.

You can get the latest build from the jenkins server:
http://jenkins.superckl.me/job/BiomeTweaker%201.12/

**Comment by brisingraerowing** [comment]
OK. Thanks. I'll go ahead and do that.

**Comment by brisingraerowing** [comment]
I'm getting pretty much the same crash with the latest build (3.1.309) as well.

[New Crash Log](https://gist.github.com/BrisingrAerowing/3441e094b8368db54f2552043d8a59a4)

**Comment by superckl** [comment]
Sorry that took so long. School has me swamped.

Reproduced this on my end and verified it's fixed now.

**Comment by brisingraerowing** [comment]
No problem. I'm on a temporary system since my main computer has a bad power jack, and it is currently at a local computer repair shop to get fixed. I was able to set up MC, but I am only using 1.10.2 until I get my computer back (this system doesn't have enough RAM for some of the 1.12.x mods I use).
