### ISSUE TITLE
Cant get the script to work

### ISSUE THREAD

**Issue by Lecapria** [superckl/BiomeTweaker#137]
No matter what i put in the scipt from the tutorial, every line comes out in the command prompt like
[BiomeTweaker]: Failed to find meaning in command ..... It will be ignored.
im trying to just replace minecraft tall grass with a modded one. im using 1.10.2

**Comment by ghost** [comment]
While I doubt you still are looking, it should be noted no one can do anything to help you if you don't provide proper information. And if you have indeed moved on, you should close your issue.
