### ISSUE TITLE
1.10.2 it just loaded

### ISSUE THREAD

**Issue by dagantang** [superckl/BiomeTweaker#139]
when i install this mod 
it just loaded but not active?
why?

**Comment by superckl** [comment]
How do you know it's not active?

**Comment by dagantang** [comment]
http://upload.lsforum.net/users/public/d55311i12.jpg

**Comment by superckl** [comment]
And you know that's BiomeTweaker how? It's BiomeTweakerCore that is disabled, not BiomeTweaker.

**Comment by dagantang** [comment]
how to active BiomeTweakerCore
sorry for asking
i dont why cant work

**Comment by superckl** [comment]
You don't. You don't want to. It only serves a purpose at startup. You don't need it afterwards, so it's disabled.

**Comment by dagantang** [comment]
thank you
