### ISSUE TITLE
Typo for mushroom

### ISSUE THREAD

**Issue by keybounce** [superckl/BiomeTweaker#14]
else if(prop.equals("muchroomsPerChunk"))

I'm not sure how often I'll see much rooms in a chunk, other than castles and such with lots of rooms :-)

Github says line 224

**Comment by superckl** [comment]
Heh, you made me laugh :P

This is what I get for hastily pushing an update.
Fixed in 9f2c5eecedd97c926929e83ebbf179d34b1b7c71

**Comment by keybounce** [comment]
I was thinking of those big mushroom castles, full of empty rooms :-)


On 2015-05-04, at 8:14 PM, Chris <notifications@github.com> wrote:

> Heh, you made me laugh :P
> 
> This is what I get for hastily pushing an update.
> Fixed in 9f2c5ee
> 
> —
> Reply to this email directly or view it on GitHub.
> 

---
Entertaining minecraft videos
http://YouTube.com/keybounce
