### ISSUE TITLE
Did mob spawning via biometweaker change at all?

### ISSUE THREAD

**Issue by Sunconure11** [superckl/BiomeTweaker#140]
I created a script to spawn two specific mobs, but it appears it's no longer working. The changes do not even show up in the appropriate output. Did this mod change spawning through it at all?

https://pastebin.com/2NhKsEfy

Note: Biomes O' Plenty is installed.

**Comment by superckl** [comment]
I'll need a log file to debug scripts. BiomeTweaker will tell you if your script is incorrect.

**Comment by Sunconure11** [comment]
I found an error, it says it failed to parse the script.

"java.io.IOException: The filename, directory name, or volume label syntax is incorrect"

Of note is that the file is a .cfg file.

**Comment by superckl** [comment]
That's great, but I need the full error or the log.

**Comment by Sunconure11** [comment]
https://pastebin.com/mJj4PbVH

I had tried changing it to run outside of the scripts folder, to see if that would fix it. Looks like it did not.

**Comment by superckl** [comment]
... How did you manage to get quotation marks in a file name? Those aren't valid characters for file names. Remove them

**Comment by Sunconure11** [comment]
More like I edited the config.
