### ISSUE TITLE
Possible to remove igloos?

### ISSUE THREAD

**Issue by ghost** [superckl/BiomeTweaker#141]
I see that in [the link from the wiki](https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/src/main/java/net/minecraftforge/event/terraingen/DecorateBiomeEvent.java#L112) on "xxxPerChunk" section you can disable biome specific generation such as desert water wells. Would it be possible to also disable igloos?

On a semi-unrelated request, would it also be possible to disable ravines using BT? I know you said in #51 that it would not be since they are not biome specific but then neither are strongholds or villages. Reason I ask is because no mod that disabled these seems to work with BT (or any world gen modifying mods, like geographycraft).

**Comment by superckl** [comment]
V[illages and strongholds actually are biome specific](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/common/BiomeManager.java#L89-L123). Ravines still are not, though it would be possible through ASM. I may consider adding the feature in future update.

Currently you cannot disable igloos. They are linked with swamp huts and desert pyramids as "scattered features". I can add this in a future update. To add to the bad news, school is particularly heavy right now, so it might be a while.

**Comment by ghost** [comment]
Would be greatly appreciated if at all possible. No rush, school > mods.

**Comment by ghost** [comment]
Perhaps seeing how DarkHax does it (note the mod seems incompatible with BT) might be of use?

https://github.com/Darkhax-Minecraft/No-Worldgen-5-You/blob/master/src/main/java/net/darkhax/noworldgen5you/world/gen/MapGenScatteredFeaturesEmpty.java

**Comment by superckl** [comment]
In what way is it incompatible?

**Comment by ghost** [comment]
I can only guess it applies it before your mod. I have found igloos and ravines with both installed.

**Comment by superckl** [comment]
So BiomeTweaker nullifies the changes done by the other mod? Have you noticed any over incompatibilities?

**Comment by ghost** [comment]
Well, I'm using BT to specifically [generate a cold biome only world](https://github.com/HellishINC/ColdBlooded/blob/master/config/BiomeTweaker/scripts/frozenthrone.cfg). It's possible other functionality also is incompatible but I'd have to do further specific testing. I can do so later or perhaps tomorrow.

**Comment by superckl** [comment]
Turns out igloos will have to be ASM based as well. This is to ensure compatibility with all mod structures. I'm working on this feature now.

**Comment by ghost** [comment]
Thank you!

**Comment by superckl** [comment]
Give the new feature a try and let me know. It was added to the set command.

```
coldBiomes.set("genScatteredFeatures", false)
```

**Comment by ghost** [comment]
When I get a chance, I'll def try it out!

**Comment by smcnabb** [comment]
I've been looking for this as well, so did a quick test with the latest jenkins build and it seems to be working great. I created a world with a jungle temple, added the above set command to a script and re-created the world and the temple was removed.

**Comment by ghost** [comment]
Thank you for testing. Haven't had much time for MC as of late.
