### ISSUE TITLE
Removing/Adding mob spawns.

### ISSUE THREAD

**Issue by ghost** [superckl/BiomeTweaker#142]
Apologies if this is me simply misunderstanding the wiki.

In the `addSpawn` section, it states that the four mob types are:

`"CREATURE", "MONSTER", "CAVE_CREATURE", "WATER_CREATURE"`

I had assumed that those four types would also apply when using `removeAllSpawns` and `BIOME.addSpawn("MOB", "TYPE", INT, INT, INT)`

Is that the intended functionality? My goal is to remove all mobs and only allow a specified few however when doing:

```
all.removeAllSpawns("CREATURE")
all.removeAllSpawns("WATER_CREATURE")
all.removeAllSpawns("CAVE_CREATURE")
all.removeAllSpawns("MONSTER")
```
[The game throws a huge list of errors.](https://gist.github.com/HellishINC/ea2c35b02430a936697afcf0bffc2c14) Currently all instances of `"CAVE_CREATURE"` have been commented out to prevent log spam and no other BT errors are thrown, however, no mobs spawn in game (be it day/night passive/hostile in all dimensions) except for bats and the ender dragon. I flew/ran around various worlds for about an hour.

[The complete script can be found here.](https://github.com/HellishINC/ColdBlooded/blob/master/config/BiomeTweaker/scripts/ripwcrts.cfg)

Also, can hostile mobs be spawned in when set to a `CREATURE` type? Would this allow hostile mobs to spawn during the day? Likewise, could you use `MONSTER` type to allow non hostiles to spawn only in unlit locations (assuming there is a valid block to spawn on)?

**Comment by superckl** [comment]
Looks like "CAVE_CREATURE" was renamed to "AMBIENT" recently. I've updated the wiki to reflect this.

I'm not sure on the specifics of mob spawning... A cursory code inspection says you're correct. I'd say try it out and see what happens!

**Comment by ghost** [comment]
I did try it out. The only mobs spawning are bats and the ender dragon. If I remove the mob spawn script mobs start spawning again. The script/mod throws no errors so I can only guess it's a bug?

**Comment by superckl** [comment]
A bug with what? What are you trying to do?

**Comment by ghost** [comment]
> My goal is to remove all mobs and only allow a specified few

I'd like to make it so that only X mob can spawn in Y biome. This would require players to travel around and gather specific materials versus just staying in one static location.

The "bug" is that no mobs spawn at all. Except the ender dragon and bats.

Here's a small "mod pack" that has all the required. https://www.dropbox.com/s/8fi5ddbzm42yc1n/MobTest.tar.gz?dl=0

**Comment by superckl** [comment]
Looks like part of the spawn command got deleted during a refactoring. Grab the latest version from the Jenkins server and your script should work.

http://jenkins.superckl.me/job/BiomeTweaker%201.12/

**Comment by ghost** [comment]
thatsmyfetish.gif

Thanks!

**Comment by GeekGaming3443** [comment]
you can also use it in skript
