### ISSUE TITLE
Tweaker.createBiome("crimson_plains", "minecraft:plains") error

### ISSUE THREAD

**Issue by donqixot** [superckl/BiomeTweaker#143]
I am using MC 1.11.2, forge 13.20.1.2530, BiomeTweaker-1.11.2-2.3.246, BiomeTweakerCore-1.11.2-1.0.18.

I am following instructions for basic script command. I have one line script:
Tweaker.createBiome("crimson_plains", "minecraft:plains")

From the game, I run command "btreload", it says "successfully reloaded scripts". However, in the log it says:
[Server thread/ERROR] [SuperScript]: Failed to find meaning in command createBiome("crimson_plains", "minecraft:plains"). It will be ignored.

Should I ignore error message or it means biome creation failed?

Here is one line script called Test1.cfg from folder minecraft\config\BiomeTweaker\scripts
[Test1.zip](https://github.com/superckl/BiomeTweaker/files/1460560/Test1.zip)

I have many biomes in this pack from different mods - Biomes'O'Plenty, Galacticraft, Extra Planets, More Planets, Advanced Rocketry, Futurepack. In total, there are 207 biomes registered. Is there some mod interaction I should aware of?

**Comment by superckl** [comment]
You're running a super old version of BiomeTweaker... Update to the latest 1.11.2 version and it should work.

**Comment by donqixot** [comment]
Oops, sorry about that, took release version, did not see beta.
