### ISSUE TITLE
Custom property [basictypemars] for block [galacticraftplanets:mars] are set incorrectly for topBlock and fillerBlock.

### ISSUE THREAD

**Issue by donqixot** [superckl/BiomeTweaker#147]
Apologies for bombarding with issues, I read all articles before I submit.

I am using MC 1.11.2, forge 13.20.1.2530, BiomeTweaker-1.11.2-3.1.304, BiomeTweakerCore-1.11.2-1.0.18, GalacticraftCore-1.11.2-4.0.0.118, Galacticraft-Planets-1.11.2-4.0.0.118.

I am trying to set custom property for my block, here is the script:
Tweaker.createBiome("MarsPlus")
mars = forBiomes("biometweaker:MarsPlus")
mars.set("name", "Mars Plus")
myBlock = forBlock("galacticraftplanets:mars")
myBlock.setProperty("basictypemars", "mars_surface")
mars.set("topBlock", myBlock)

I see that command worked because there is new block for topBlock in json file created, however, it says:
"Top Block": "galacticraftplanets:mars[basictypemars\u003dore_copper_mars]"

When I try to create dimension using my new biome, I do indeed get copper ore on top. I tried this syntax:
myBlock = forBlock("galacticraftplanets:mars[basictypemars\u003dmars_surface]")
mars.set("topBlock", myBlock)

Still doesn't help. Anything I am doing wrong? For comparison, addActualFillerBlock() and registerGenBlockRep() work correctly, so this script is fine:

myBlock = forBlock("galacticraftplanets:mars")
myBlock.setProperty("basictypemars", "mars_stone")
mars.addActualFillerBlock(myBlock)
mars.registerGenBlockRep("minecraft:stone", myBlock)

**Comment by superckl** [comment]
Do you see any errors in your log?

**Comment by donqixot** [comment]
No, it says script loaded successfully.

**Comment by donqixot** [comment]
Weird, I just tried again, wanted to take a snapshot, and now it is correct! The only change was this line:
mars.addToGeneration("DESERT", 100)

I will test more...

**Comment by donqixot** [comment]
Turns out, there was indirect error:

[21:38:57] [Client thread/INFO] [biometweaker]: Beginning script parsing...
[21:38:57] [Client thread/INFO] [biometweaker]: Finished script parsing.
[21:39:00] [Client thread/INFO]: [STDERR]: Potential problem: Galacticraft did not complete injection of bytecode into: bqe (4 / 6)

If I run script second time, after initial load of the game, then it's fine. Should I run this script at a different phase (post BIOME_BLOCKS)?

Here is snapshot with script loaded only once:
![2017-11-13_21 44 58](https://user-images.githubusercontent.com/12219588/32760523-a0578ef6-c8bc-11e7-85e5-3a75e67924d0.png)

And here with script reloaded second time after game started:
![2017-11-13_21 29 36](https://user-images.githubusercontent.com/12219588/32760543-b668f964-c8bc-11e7-920a-5782bb5d3169.png)

I see that it may be GC interaction issue, but if you can suggest anything, I'd really appreciate!

**Comment by donqixot** [comment]
But aside from loading script twice, I now have my custom Mars biome! This is soooo cool! Thank you so much for this mod!
![2017-11-13_21 55 00](https://user-images.githubusercontent.com/12219588/32760712-7ebfc212-c8bd-11e7-81fd-d32809a8ed9b.png)

**Comment by superckl** [comment]
Do you know if this is still an issue on 1.12?
