### ISSUE TITLE
Rivers still spawn after being diabled

### ISSUE THREAD

**Issue by SpudGunMcGee** [superckl/BiomeTweaker#150]
I have written a script for a single biome to be spawned however rivers still seem to spawn when generating the world.

`#Specify IDs
alps = forBiomes("biomesoplenty:alps")
alpsf = forBiomes("biomesoplenty:alps_foothills")
river = forBiomes("minecraft:river")

#Add alpsf to gen
alpsf.addToGeneration("WARM", 5000)
alpsf.addToGeneration("COOL", 5000)
alpsf.addToGeneration("DESERT", 5000)
alpsf.addToGeneration("ICY", 5000)

#control mob spawns
alpsf.removeAllSpawns("CREATURE")

Tweaker.setStage("PRE_INIT")
desert.set("reedsPerChunk", 20)
desert.set("clayPerChunk", 10)
hills.set("clayPerChunk", 10)
Tweaker.setStage("FINISHED_LOAD")

river.set("isSpawnBiome", false)
#Remove other biomes
all = forAllBiomes()
all.set("genWeight", 11)
all.set("isSpawnBiome", false)

#remove all water (keeps lakes tho)
all.registerGenBlockRep("minecraft:water", "minecraft:air")

alpsf.set("isSpawnBiome", true)
alpsf.set("genWeight", 50000)`

**Comment by superckl** [comment]
This mod isn't designed to create single biome worlds. Use BiomeTweaker to create the biome and a mod like Lonely Biome to spawn only it in the world.

**Comment by MattJohns** [comment]
You can create single biome worlds though using registerGenBiomeRep() .  At least I think i've done it in the past.
