### ISSUE TITLE
The 1.12 Version Says 1.12 but really its for 1.12.1

### ISSUE THREAD

**Issue by FNaFTaleTeam** [superckl/BiomeTweaker#151]
I need some help with this

**Comment by superckl** [comment]
Why is this a problem...?

**Comment by Cazadorsniper** [comment]
Its just that it is not marked on Curseforge as 1.12 (in my case 1.12.2) so if I tried to publish a pack on Curse it will get rejected most likely.

**Comment by superckl** [comment]
It's marked as 1.12 and 1.12.1.

**Comment by Cazadorsniper** [comment]
can it be marked as 1.12.2 also?

**Comment by superckl** [comment]
Have you verified it works on 1.12.2? I haven't, so I can't mark it as compatible. 1.12.2 wasn't released yet when I put that version out.

**Comment by Cazadorsniper** [comment]
Well as far I know for what I'm using it for, it works completely fine, which is turning off rain and replacing the blocks in the nether back to netherrack will probably use more if needed.
