### ISSUE TITLE
Best way to generate decorative stone?

### ISSUE THREAD

**Issue by ghost** [superckl/BiomeTweaker#152]
I've been reading the docs and I would like to add more decorative stone (like andesite) to the game. Are big blobs using the ore decoration the only real option? Is there a way to add new stones to the built in mix? Would it be too heavy to make the blobs after ore gen so that they don't hinder resources?
Thank you.

**Comment by superckl** [comment]
Your best best bet currently would be an ore decoration. Current stone variants do use the ore decoration, actually. They use a size of 33 and count of 10. It shouldn't impact your performance too much to add a few ores.
