### ISSUE TITLE
removeDicType not working at all

### ISSUE THREAD

**Issue by Snorps** [superckl/BiomeTweaker#156]
but addDicType works fine
for example

```
forest=forBiomes("minecraft:birch_forest","minecraft:birch_forest_hills","minecraft:mutated_birch_forest","minecraft:mutated_birch_forest_hills")
forest.removeDicType("FOREST")
forest.addDicType("MAGICAL")
```
results in Birch_Forest (minecraft_birch_forest).json being
```
"Dictionary Types": [
    "FOREST",
    "MAGICAL"
  ]
```
broken with both
BiomeTweaker 1.12.1-3.1.306 (latest curse version)
BiomeTweakerCore 1.12.2 1.0.23
and
BiomeTweaker 1.12.2-3.1.311 (latest jenkin's version)
BiomeTweakerCore 1.12.2 1.0.23

**Comment by Snorps** [comment]
Turns out this is appearing in the console:
`[SuperScript]: Failed to find meaning in command removeDicType("FOREST"). It will be ignored.`

**Comment by IMarvinTPA** [comment]
I tried to find "removeDicType" in the documentation, and while it would be really handy to have, it does not appear to actually exist at this time.  Perhaps you are a time traveler.

**Comment by Snorps** [comment]
must be. Does this page exist in your time? https://github.com/superckl/BiomeTweaker/wiki/Basic-Script-Commands

**Comment by IMarvinTPA** [comment]
I swear it wasn't there before...  Also, Bearinstein Bears.  Now to clean up the stupid system-assigned biome descriptors on my hell biome.

**Comment by superckl** [comment]
Turns out the issue was a change in the command name. The name you should be using is `removeDicTypes`. This has been changed on the wiki as well.
