### ISSUE TITLE
Possible to define a height level for block replacement?

### ISSUE THREAD

**Issue by HorizonsMC** [superckl/BiomeTweaker#157]
So I am wanting to remove the bedrock roof in a custom Nether dimension, is it possible to define a Y level for blocks to be replaced at as this script works but also removes the bottom bedrock layer. Or even better is there a way to stop all gen above a certain Y level.

Tweaker.setWorld(5002)

#Specify ids
all = forAllBiomes()

Tweaker.setPlacementStage("BIOME_BLOCKS")
all.registerGenBlockRep("minecraft:bedrock", "minecraft:air")
#all.removeFeature("NETHER_LAVA")

**Comment by superckl** [comment]
There is not currently a way to do that. I can add it in a future release of you'd like, but it will be a while.

**Comment by superckl** [comment]
This should now be possible using the latest builds of BiomeTweaker. Use this in your script:

```
Tweaker.setWorld(5002)

all = forAllBiomes()

Tweaker.setPlacementStage("BIOME_BLOCKS")
topBed = newBlockReplacement()
topBed.set("block", "minecraft:air")
topBed.set("minY", 120)
all.registerGenBlockRep("minecraft:bedrock", topBed)
```

I won't have official documentation on this until I release it to CurseForge. Ask questions here if you have any.
