### ISSUE TITLE
BiomeTweaker Can't Modify NetherEx Generated DImensions

### ISSUE THREAD

**Issue by HorizonsMC** [superckl/BiomeTweaker#158]
Using the NetherEx mod on 1.12.2 and latest version of forge trying to replace blocks isn't working.

**Comment by superckl** [comment]
Remove NetherEx and see if it still doesn't work.

**Comment by superckl** [comment]
Will be closing this issue in a few days if there no response.

**Comment by HorizonsMC** [comment]
Yes it works without NetherEX.

The mod changes the world provider for the nether so maybe that is breaking something.

**Comment by superckl** [comment]
The mod does not fire the appropriate events. This is something you need to take up with the author of NetherEx. Open an issue on NetherEx's issue tracker and link this issue, please.

For reference, the events that are not fired are the populate and decorate events. The populate events are fired via `ForgeEventFactory.onChunkPopulate` and the decorate events are fired manually with the `DecorateBiomeEvent.Pre` and `DecorateBiomeEvent.Post` events.
