### ISSUE TITLE
Let createBiome be able to copy most biomes

### ISSUE THREAD

**Issue by superckl** [superckl/BiomeTweaker#159]
Repost of #154 

Some biomes such as forest cannot be copied directly because their constructors take parameters. Allowing these to be copied will require some sort of structure to allow users to specify data to be passed to biome constructors.

**Comment by RiverC** [comment]
Noticed that there may be something added to the createBiome command here - can we get a hint as to what its structure should be like? 


Thanks.

**Comment by superckl** [comment]
This update is transparent to the end user. Use the command as you did before.

**Comment by RiverC** [comment]
Great, I hoped that was the case, thanks for the quick response. I'll try it out, hopefully tonight.
