### ISSUE TITLE
[Feathure request] Horizon color setting

### ISSUE THREAD

**Issue by GrzechuGrek** [superckl/BiomeTweaker#160]
This option is just a only thing that is missing in this mod.

**Comment by superckl** [comment]
What do you mean by horizon color? Can you provide an image of exactly what you would like to change?

**Comment by GrzechuGrek** [comment]
By "horizon" I mean this: 
http://pokazywarka.pl/nelcww/

Look at landscapes/screenshoots from Biomes of Plenty mod:
http://pokazywarka.pl/ipy423/
http://pokazywarka.pl/0f7z44/
http://pokazywarka.pl/q8m0ez/
http://pokazywarka.pl/4nqjqm/
http://pokazywarka.pl/nke4tf/

So Biome Tweaker can define color of sky, but horizon's color remain same, through this sky's landscape look at weird and incomplete in case if color of sky was set other than default blue.

There function/script command like "horizonColor" would be useful beside "skyColor".

**Comment by superckl** [comment]
This isn't a very easy thing to do, and will require BiomeTweakerCore. I'll work on implementing it soon.

**Comment by GrzechuGrek** [comment]
Ok, thank you for responding and good luck 👍

**Comment by superckl** [comment]
You should now be able to set color via the set command:
```
biome.set("fogColor", <color>)
```
Let me know how it works for you.
