### ISSUE TITLE
Typo & command needed/ info request?

### ISSUE THREAD

**Issue by kingdadrules** [superckl/BiomeTweaker#163]
Hi,
I noticed on https://github.com/superckl/BiomeTweaker/wiki/Custom-Decorations,  you have "addBlockToReplace" instead of "setBlockToReplace".

Is there a way with BiiomeTweaker to stop abandoned  mineshafts generating?
 I tried removeFeature("DUNGEON") in case it did mineshafts as well to no avail.

Keep up the great work with this outstanding & I feel essential mod for modpack makers, etc... It's much appreciated.

Environment:
Forge Mod Loader version 14.23.1.2555 for Minecraft 1.12.2, 
BiomeTweaker-1.12.2-3.1.311, BiomeTweakerCore-1.12.2-1.0.22

**Comment by superckl** [comment]
That's not a typo with the most recent versions (from the Jenkins Server), and you currently cannot disable mineshafts. I don't intend on adding that feature anytime soon, since mineshafts aren't inherently biome related.
