### ISSUE TITLE
newTreeDecoration mainBlock wrong placement

### ISSUE THREAD

**Issue by Bobb-E-Burns** [superckl/BiomeTweaker#164]
Forge: `14.23.1.2559`
`BiomeTweakerCore-1.12.2-1.0.22`
`BiomeTweaker-1.12.2-3.1.329` from Jenkins

```
Tweaker.setScriptStage("POST_INIT")
Tweaker.setPlacementStage("POST_DECORATE")
newTrees = newTreeDecoration()
newTrees.set("count", 20)
newTrees.set("minHeight", 16)
newTrees.set("heightVariation", 8)
newTrees.set("mainBlock", "traverse:fir_log")
newTrees.set("leafBlock", "traverse:fir_leaves")
newTrees.set("leafHeight", 10)
```
Also tested with vanilla `minecraft:log`

![2018-01-11_17 59 11](https://user-images.githubusercontent.com/11016915/34837223-5e67f258-f6fa-11e7-89fa-6ec892e22ffd.png)

**Comment by superckl** [comment]
Thanks for the report, should be fixed now.
