### ISSUE TITLE
Can't stop Ocelots spawning

### ISSUE THREAD

**Issue by smcnabb** [superckl/BiomeTweaker#168]
I'm having trouble getting Ocelots to stop spawning in Jungle biomes. Here's the script I've been testing with:

```
jungle = forBiomes(21)

jungle.set("isSpawnBiome", true)
jungle.removeFeature("ANIMALS")
jungle.removeAllSpawns("CREATURE")
jungle.removeDecoration("TREE")
jungle.removeSpawn("net.minecraft.entity.passive.EntityOcelot", "CREATURE")

allButJungle = forAllBiomesExcept(21)
allButJungle.registerGenBiomeRep(21)
```

I added the removeSpawn() call after I found the other script commands weren't removing Ocelots but it didn't help. The above is just a test script to reproduce the problem - I noticed them in jungle biomes using another script that doesn't limit to just jungle biomes, so it looks like a general problem.

Here's some version info:

```
Minecraft 1.12.2
forge-1.12.2-14.23.1.2600.jar
BiomeTweaker-1.12.2-3.1.312.jar
```

I also tried with the latest build on jenkins but the same thing happens.

Here's the output script for the jungle biome in my test world:
https://gist.github.com/anonymous/1c714bba11c0afa3aeb59611e02c67f0

You can see the net.minecraft.entity.passive.EntityOcelot entry is still there but all other animals are gone.

And a screenshot:
https://imgur.com/a/qhvqN

Thanks for keeping up all your hard work on this great mod. I was very happy to see the 1.12.2 version!

**Comment by superckl** [comment]
Ocelots are classified as monsters in the spawn lists. You can see them registered under "MONSTER". Change the line 
```
jungle.removeSpawn("net.minecraft.entity.passive.EntityOcelot", "CREATURE")
```
to
```
jungle.removeSpawn("net.minecraft.entity.passive.EntityOcelot", "MONSTER")
```

**Comment by smcnabb** [comment]
Yup, that worked perfectly. Thanks!
