### ISSUE TITLE
Is possible to register new ores (and mobs) using BT?

### ISSUE THREAD

**Issue by vico93** [superckl/BiomeTweaker#169]
Hi!
Coming from OreSpawn (and InControl) after all my scripts for those mods failed to be processed.

My main goals are:

- Make Emerald gereration in all biomes (with the same rate as vanilla);
- Register a custom block i made via CubeX2's [CustomStuff 4](https://github.com/cubex2/customstuff4/) to the ore generation (i know CS4 have the possiblity to register oregen from there, but i want to concentrate all custom stuff in a single mod for better organization);
- Make oocelots spawn in all forest biomes;
- Make wolves spawn on plains too.

What is possible to do using BiomeTweaker at current state? Thanks in advance!

**Comment by superckl** [comment]
You can add any block you want to as an ore using BiomeTweaker.

https://github.com/superckl/BiomeTweaker/wiki/Custom-Decorations

Emerald uses a count between 3 and 8, and a size of 1. For entities, you can also add any existing LivingEntity as a spawn.

https://github.com/superckl/BiomeTweaker/wiki/Basic-Script-Commands#addspawn

If you need help writing the script, let me know.

**Comment by vico93** [comment]
Two little questions: does `clayGen.addBlockToReplace("minecraft:stone")` also add Andersite/Diorite/Granite (variations of stone block) as well? Can we add specific metadata/variation blocks to be replaced?

And you have a discord server or are in MMD? I think would be better to ask questions in that to not cluster the issues with newbie questions.

EDIT: Well, i manage to make [this script](https://github.com/vicocraft/bt_pack/blob/master/config/BiomeTweaker/scripts/claygen.cfg), but no clay blocks are generating on my world (Created a brand new for test, blew up a large part of it and no clay found).

**Comment by superckl** [comment]
I have a channel in the RTG Discord. You can find the link on their forum page.
