### ISSUE TITLE
Client crash after installing BT and starting a new world with BOP then teleporting.

### ISSUE THREAD

**Issue by ProsperCraft** [superckl/BiomeTweaker#171]
https://gist.github.com/ProsperCraft/4a0070348a1787227a2b0a2b3050ed66

untimeException: Climate lookup failed climateOrdinal: 57

Modpack in question - https://minecraft.curseforge.com/projects/towncraft

**Comment by superckl** [comment]
That doesn't seem like an error with BT. First of all, BOP is mentioned in 99% of the report, and second of all, BT does nothing without any scripts. You'll have to give me some more info.
