### ISSUE TITLE
"topBlock", "fillerBlock" can not be replaced with other blocks.

### ISSUE THREAD

**Issue by RealLith** [superckl/BiomeTweaker#172]
running latest 1.12.2 BiomeTweakre and BiomeTweakerCore.

 Im trying to change a top and filler block to another modded blocks. I tried multiple ways.
1st. 
allBiomes = forAllBiomes()
allBiomes.registerGenBlockRep("minecraft:sand", "primal:ortho_stone")
allBiomes.addActualFillerBlock("primal:ortho_stone")

2nd.
allBiomes = forAllBiomes()
allBiomes.set("topBlock", "fillerBlock", "primal:ortho_stone")
allBiomes.registerGenBlockRep("minecraft:sand", "primal:ortho_stone")

3rd.

instead of "allBiomes = forAllBiomes()" i tried using "desert = forBiomes(2)
hills = forBiomes(17)
river = forBiomes(7)" and for everyone of them i used 1st and  2nd method.

None worked. I have a desert world. I used the same script for a desert world that your wiki holds " https://github.com/superckl/BiomeTweaker/wiki/Example-Scripts " just so i could learn this mod and make my own stuff. 

I dont know if its me doing something wrong or mod. It would be awesome to get some information about this.

**Comment by RealLith** [comment]
I figured it out. I needed to use:
allBiomes.set("topBlock", "primal:ortho_stone")
allBiomes.set("fillerBlock", "primal:ortho_stone")
allBiomes.registerGenBlockRep("minecraft:stone", "primal:ortho_stone")
allBiomes.set("actualFillerBlock", "primal:ortho_stone")

So it was my problem not mods.

But quick question, how do i disable random water patches/pools from spawning? oceans are dry, rivers are dry but sometimes little lava and water pools will generate. how to disable that?

**Comment by superckl** [comment]
https://github.com/superckl/BiomeTweaker/wiki/Basic-Script-Commands#removefeature

and

https://github.com/superckl/BiomeTweaker/wiki/Basic-Script-Commands#removedecoration

They both have options for "LAKE" and "LAVA". Figure out what works for you.
