### ISSUE TITLE
"waterColor" "skyColor" "fogColor" Arent working

### ISSUE THREAD

**Issue by RealLith** [superckl/BiomeTweaker#173]
BiomeTweaker-1.12.2-3.2.344
BiomeTweakerCore-1.12.2-1.0.3.9
Minecraft 1.12.2
Forge-14.23.2.2618

allBiomes = forAllBiomes()
allBiomes.set("topBlock", "biomesoplenty:dried_sand")
allBiomes.set("fillerBlock", "primal:ortho_stone")
allBiomes.removeOre("IRON")
allBiomes.removeOre("COAL")
allBiomes.removeOre("DIAMOND")
allBiomes.removeOre("GOLD")
allBiomes.removeOre("LAPIS")
allBiomes.removeOre("REDSTONE")
allBiomes.removeOre("DIORITE")
allBiomes.removeOre("GRANITE")
allBiomes.removeOre("ANDESITE")
allBiomes.removeOre("EMERALD")
allBiomes.removeAllSpawns("WATER_CREATURE")
allBiomes.set("waterColor", "15073024")
allBiomes.set("skyColor", "9477744")
allBiomes.set("fogColor", "12106885")

removeOre works, top and fillter block works BUT waterColor, skyColor and fogColors arent working. in BiomeTweakerCore I Have 'addActualFillerBlock' 'fogColor' 'skyColor' 'waterColor' set to true and the rest set to false (default). I tried with all set to false, it dosent work aswell.

No other tool is used to edit terrain or add anything new.
There are none, or atleast i found none, errors in logs.

**Comment by superckl** [comment]
If things aren't working, you should look in the log. If you did, you'd see BT complaining that it can't match the arguments you provided. Colors are provided as numbers, not strings. When you put "12753", you're telling BT that is text. You need to drop the quotation marks for numbers.
