### ISSUE TITLE
Cannot generate Botania Flowers with cluster decorations

### ISSUE THREAD

**Issue by GunmetalGears** [superckl/BiomeTweaker#175]
I'm using Minecraft version 1.12.2, with Forge version 14.23.2.2627, and BiomeTweaker version 3.1.

I'm trying to use BiomeTweaker's cluster decoration system to spawn Botania's Pure Daisies. However, I cannot for the life of me get it to spawn the actual Pure Daisy block. I can only get it to spawn an invalid Botania flower, which is a generic botania:specialflower block.

Here is my script: https://pastebin.com/8afkhH0N

In the line that designates the variant as 'puredaisy,' I've tried subtile_id and type in place of the word 'variant.' None of these work.

**Comment by superckl** [comment]
I'm not sure how Botania handles it's flowers. You'll have to ask Vazkii if the flowers can be set through the usual blockstate system. I have a feeling it's a bit more complicated.

**Comment by superckl** [comment]
Haven't heard anything on this, so I'm going to close it. Let me know if it's still an issue for you.
