### ISSUE TITLE
Need some help figuring things out

### ISSUE THREAD

**Issue by haeihaeihaei** [superckl/BiomeTweaker#176]
Hey, I'm trying to make my first modpack and stared playing around with Biometweaker. Here's what I'm trying to do:

The Overworld should only be made of Mesa blocks and scarce water sources. Trees should only be Acacia trees and some cacti. There should only be certain animals spawning from certain mods.

The spawns are quite clear, it's just the Biome options that I don't understand.

Would it be better to create a new biome and register it?

**Comment by superckl** [comment]
I would recommend modifying an existing biome, like plains, and using a mod such as Lonely Biome to make it the only biome that generates.

**Comment by haeihaeihaei** [comment]
Hey, thanks buddy. I've come to this for now: https://imgur.com/a/bB4ib

As you an see there are still some weird things left, how can I get rid of them? Using this script: https://pastebin.com/4pqeKWvK

**Comment by superckl** [comment]
You'll have to be specific with what you mean by "weird things". To get rid of the stone, you need to add

```
plainsBiome.registerGenBlockRep("minecraft:stone", "minecraft:red_sandstone")
```

**Comment by haeihaeihaei** [comment]
Hi, I meant like the water is still there for example, I figured out the stone but I want the water to be lava.

**Comment by superckl** [comment]
That water is from lake generation which happens later than the water replacement you have. You can remove lakes with the remove feature command, or you can schedule the lava replacement later with set placement stage.

**Comment by superckl** [comment]
Assuming this is resolved. Let me know if you still need help.
