### ISSUE TITLE
Minecraft crashes in loading custom decoration

### ISSUE THREAD

**Issue by tkxyooj** [superckl/BiomeTweaker#177]
I'm working on a custom modpack and I'm tweaking the wasteland from BiomesOPlenty to have custom tress and ores generation. The game crashes every time I try to generate a new world. What I am getting from the [crash log ](https://pastebin.com/M9LxtqUk) is that there is an error with the decoration generation, but that's as far as I can tell. The custom generation is using custom blocks that were made by ContentTweaker. I am able to generate a custom world if I don't add decorations, but as this is a specialized pack, I would need those custom decorations as well. I've included the [config file ](https://pastebin.com/gfPyELFT) as well in case that helps point out where the issue could be.

**Comment by superckl** [comment]
The radius you've set for your cluster decoration is way too large. It keeps spilling over into new chunks causing never-ending cascading world gen. The radius of a chunk is 8, so you want to keep it under 8 to avoid too much cascading. Anywhere between 8-16 should eventually stop, but 16 and over will always cause never-ending cascading.

**Comment by superckl** [comment]
If you're looking to add decorations that large, either open a new issue as a feature request (it would have to be noised based to cross multiple chunks) or find another mod that can do that.

**Comment by tkxyooj** [comment]
Thank you. It was the misunderstanding of what radius meant. Modified the script and now the world generates without any issue.
