### ISSUE TITLE
Overriding biomes in combination with Climate Control

### ISSUE THREAD

**Issue by SeriousCreeper** [superckl/BiomeTweaker#178]
Heya,

i'm currently trying to create a world that's mostly ocean with a few islands here and there. 
I use climate control to control the size and rarity of islands, and biome tweaker to adjust some things. 

One of the things i try to do is to replace the ocean and deep ocean biomes with the Tropicraft ocean biome. This works fine when i don't include Climate Control, using this:

```
ocean = forBiomes(0, 24)
ocean.registerGenBiomeRep(110)
```

But as soon as i use climate control, it spawns the vanilla oceans instead. 
Was wondering if that is just a general conflict between the two mods, or if there is a way to do this still. I tried to call the registerGenBiomeRep inside the PRE_INIT stage as well with no success. 

Cheers,
SC

**Comment by superckl** [comment]
If I recall correctly, this is an issue with CC overriding the Gen layer stack. If you aren't on 1.12, I doubt this will get fixed.

**Comment by SeriousCreeper** [comment]
Heya,

thanks for the quick reply!
So if i understand this correctly, it's something CC would have to fix on their end? Luckily i am on 1.12 so there is hope then heh.

**Comment by superckl** [comment]
First verify that your replacement works without CC. If it does, then yes, the author of CC needs to fox it.

**Comment by SeriousCreeper** [comment]
It does indeed work without CC. Thanks, will report it over there! 

Quick side question (hope this is okay), as far as i know, i can only adjust every biome size at once (using setAverageBiomeSize), i can't just increase the beach biome size, is that correct?

**Comment by superckl** [comment]
Correct, there is only a global biome size field in vanilla. Adding per-biome support would require a large overhaul.

**Comment by SeriousCreeper** [comment]
Got it, thanks a lot for the help!
