### ISSUE TITLE
Disable sun/moon

### ISSUE THREAD

**Issue by resinate** [superckl/BiomeTweaker#179]
is there a way to disable sun/moon like nether biome in nether?

**Comment by superckl** [comment]
No, this is not currently a feature. I haven't looked into adding it, but I have a feeling it won't be terribly easy. Do you need it as a feature?

**Comment by superckl** [comment]
BiomeTweaker for MC 1.12 is now EOL, so I will not be addressing bugs that are related to BT - MC interactions. If this bug persists in BiomeTweaker for MC 1.18, please submit a new issue.
