### ISSUE TITLE
can't get scripts to work

### ISSUE THREAD

**Issue by Wolfram96** [superckl/BiomeTweaker#180]
hey i realize that this is more my personal issue than a fault of the mod, but have tried following the instructions in the video and looked at the list of basic script commands but i can't seem to get them to work

specifically i am trying to disable water and lava lake generation using the allbiomes.removefeature("LAKE") script for my modded single player worlds. I am using BoP for the biomes and Geographicraft to tweak how often which biomes are generated

I have never had any prior experience with coding so i hope this is the right place to ask for help and mention that as a total programming noob i can't seem to figure something out that is probably explained somewhere in that helpful wiki u provided

**Comment by superckl** [comment]
The log file will show you what is wrong with your script, if it is even being parsed. Look through it.
