### ISSUE TITLE
Grass/Dirt Replacement Non-Function in Hill Biomes

### ISSUE THREAD

**Issue by Kazerima** [superckl/BiomeTweaker#181]
I'm attempting to replace all the dirt and grass in my world with gravel, but for some reason extreme hill type biomes don't seem to replace their dirt or grass blocks at all. The following is my script:

all = forAllBiomes()
all.registerGenBlockRep("minecraft:dirt", "minecraft:gravel")
all.registerGenBlockRep("minecraft:grass", "minecraft:gravel")
all.set("topBlock", "minecraft:gravel")
all.set("fillerBlock", "minecraft:gravel")

**Comment by superckl** [comment]
You need BiomeTweakerCore to override those top and filler blocks.

https://minecraft.curseforge.com/projects/biometweakercore

**Comment by Kazerima** [comment]
I do have biometweakercore installed and all options enabled except the one that can have serious issues with canyon biomes, it's still not functioning

**Comment by Kazerima** [comment]
Do I need to enable forced replacement/late block assignments?

**Comment by superckl** [comment]
Do you have the appropriate options enabled in BTC?

**Comment by Kazerima** [comment]
I did yes. Looks like enabling late block assignment fixed the issue

**Comment by Kazerima** [comment]
After some additional work, the issue is still persisting, particularly near spawn.
These biomes also include trees even when tree generation is disabled.
The custom tree generation and liquid filler commands are also not functioning.
I have have all options in BiomeTweakerCore enabled.
