### ISSUE TITLE
removed biomes

### ISSUE THREAD

**Issue by C0LiSii0N** [superckl/BiomeTweaker#182]
Hi, not really a issues here but I've seen that the Extreme Hills Edge biome is still in the list but it have been removed ^^'

**Comment by C0LiSii0N** [comment]
Ha and also can you tell me how to put multiple option for decoration?
Ex: I want to create cluster of fire so i put this in my config;
```
Tweaker.setPlacementStage("BIOME_BLOCKS")
clusterDec = newClusterDecoration()
clusterDec.set("count", 2)
clusterDec.set("mainBlock", minecraft:fire)
clusterDec.addSoilBlock("minecraft:grass")
clusterDec.addSoilBlock("minecraft:sand")
```
but it's not working, I've also tried to create custom dead tree(with another script) like this;
```
Tweaker.setPlacementStage("POST_ORES")
treeDec = newTreeDecoration()
treeDec.set("count", 2 && "height", 3 && "leafBlock", minecraft:air)
```
then like this;
```
Tweaker.setPlacementStage("POST_ORES")
treeDec = newTreeDecoration()
treeDec.set("count", 2, "height", 3, "leafBlock", minecraft:air)
```
then like this;
```
Tweaker.setPlacementStage("POST_ORES")
treeDec = newTreeDecoration()
treeDec.set("count", 2)
treeDec.set("height", 3)
treeDec.set("leafBlock", minecraft:air)
```
but no one worked :/ Also I tried to remove water in ocean and river but it's also not working(see log below)

log;
`[06:30:39] [Server thread/ERROR] [SuperScript]: Failed to execute script command: set @ ScriptContext(scriptName=genTree.cfg, lineNumber=4). Reason: No property found for height`
`[06:30:39] [Server thread/ERROR] [SuperScript]: Failed to execute script command: set @ ScriptContext(scriptName=Wasteland.cfg, lineNumber=9). Reason: No property found for liquidFillerBlock`

**Comment by superckl** [comment]
You need to add the decoration to a biome for it to generate. See the addDecoration command.
