### ISSUE TITLE
remove all water on river/ocean but keep small lakes

### ISSUE THREAD

**Issue by C0LiSii0N** [superckl/BiomeTweaker#183]
Hey I wanted to know if it's possible to remove all the water excepting the small random lakes we can find sometimes? Tried to remove the water from river and ocean biomes(0, 7, 10, 11, 24) but because the rivers generate water on adjacent chunk there are some water flow. Maybe add a code to remove water on chunks that avec river biomes in them instead of just remove water in biome itself?

Adding lakes decoration type would be great also bc I can't generate random lakes now(Tried with some decorations already existing but I can't make them generate in like 1% of the chunks so I'm stuck with no water at all :/)

Ha and btw, the liquidFillerBlock option that appear in the wiki doesn't exist(I found oceanFillerBlock tho but keep crashing my game when I use it so I used registerGenBlockRep instead)

**Comment by C0LiSii0N** [comment]
Just tinked of something else(Tell me what can or can't be done);
Would it be possible to create the option for creating the decorations in a certain percent of the chunks instead of in all of them or like be able to say "one of them in a radius of X block" we could generate rare decoration?
And would it be possible to create a decoration "custom" which would take a .schematic to generate it(we could make little construction(like safe-house) in few place with the option above) ?

**Comment by superckl** [comment]
Lakes won't get replaced when doing a water replacement because they generate after the replacement is done. You can safely replace water in all biomes and still have lakes.

There are a lot of things I would love to add to custom decorations, it's just a matter of time. These are great suggestions and I'll consider them if I ever find myself with the time.

**Comment by superckl** [comment]
Ocean blocks require BiomeTweakerCore, which is why is keeps crashing.

**Comment by C0LiSii0N** [comment]
I have the core mod too, that's why I don't get why it's still crashing, maybe I put the wrong tweaker stage?

**Comment by superckl** [comment]
Did you enable the ocean block features in the core's config?

**Comment by C0LiSii0N** [comment]
Yes, there's my config file;
```
# Configuration file

asm {
    # This can be used to specify biome classes BiomeTweaker should not touch with ASM. You can find the class for a biome in the output files. You should only be using this if you understand what ASM is, and you know the issue it is causing. [default: ]
    S:"ASM Blacklist" <
     >
}


"asm tweaks" {
    # Enables the 'addActualFillerBlock' command. [default: false]
    B:"Actual Filler Blocks"=true

    # Enables 'fogColor' in the set command. [default: false]
    B:"Fog Color"=true

    # Enables 'foliageColor' in the set command. [default: false]
    B:"Foliage Color"=true

    # Enables 'grassColor' in the set command. [default: false]
    B:"Grass Color"=true

    # Enables 'genInitialSnow' in the set command. [default: false]
    B:"Initial Snow Gen"=false

    # Enables 'oceanFillerBlock' in the set command. [default: false]
    B:"Ocean Filler Block"=true

    # Enables 'oceanTopBlock' in the set command. [default: false]
    B:"Ocean Top Block"=true

    # Enable this if you want BiomeTweaker to force topBlock and fillerBlock overrides in most biomes. This is done by using ASM to strip some assignments that happen in the 'genTerrainBlocks' method. This will not work for all biomes. This WILL cause issues where some biomes will have incorrect top and filler blocks if you do not override them (Extreme Hills (M), Mutated Savannah, Taiga). light ASM must be disabled for this to have any effect. [default: false]
    B:"Remove Late Block Assignments"=true

    # Enables 'skyColor' in the set command. [default: false]
    B:"Sky Color"=true

    # Enables 'waterColor' in the set command. [default: false]
    B:"Water Color"=true
}
```

**Comment by C0LiSii0N** [comment]
Finally I just created a world in solo with custom preset, put the water level to 1 and copied the level.dat, did the work perfectly
