### ISSUE TITLE
Biome removing problem

### ISSUE THREAD

**Issue by LokyLive** [superckl/BiomeTweaker#189]
Hello , 
I'm trying to remove "Landfill" biome from mod : "Dumpster Diving" , i've tryed to remove it by using ID method or by name and no one works . I've certainly made a mistake  could you help me ?

I'm using:
Forge version 14-23.3.2678
Biometweaker version 1.12.2 3.2.345 
Dumpster Diving version 1.01

Script used : 
mybiomes = forBiomes(40);
mybiomes.remove();

**Comment by superckl** [comment]
Remove the semicolons

**Comment by LokyLive** [comment]
like this ?
mybiomes=forBiomes(40);mybiomes.remove();

**Comment by superckl** [comment]
I said semicolon, not line break

**Comment by LokyLive** [comment]
ok i try this
mybiomes=forBiomes(40)
mybiomes.remove()

**Comment by LokyLive** [comment]
still not working

**Comment by superckl** [comment]
Okay... Have you tried debugging? Tried to remove a vanilla biome like forest to see if it's a compatibility issue? Have you checked your log for errors? Have you done anything except just come here and tell me it doesn't work?

**Comment by LokyLive** [comment]
I'm sorry i've already take 5 hour to test it and i've no error log from Biometweaker . I'm sorry too if my english is bad , i'm doing my best. And i'm sorry if my question looks as stupid as me but i'm just starting on modpack development and dev language is still a bit blurring for me .
At this moment i have to go to work, i will do more testing Thursday . If you got more test to suggest me to do, i will do .
Send you back a message Thursday to tell the result for compatibility issue test

Thanks for your time and i apologize again i'm just searching help

**Comment by LokyLive** [comment]
Ok so i've done more test so i've tryed Vanilla Biome removal and it won't remove specified biome , and i've tryed both wordlgen example from wiki and won't work too.

I've retry the same test with just biometweaker install to avoid any conflict from other mods and same result.

Latest log file: https://pastebin.com/Tf29eHKM

**Comment by superckl** [comment]
BiomeTweaker is not finding your script. The log shows no sign of any script being executed. Make sure your script file is in the scripts folder and ends with ".cfg"

**Comment by LokyLive** [comment]
Ok so i'm feeling like a big dumbass ... cause i read script file and i've created a ".zs" , really sorry to disturb you for this xD
Thanks for your help and for wasting your time for a noob like me ,p

PS: I've think to an enhancement for the "/BTListBiomes" , you can maybe change the text color for disabled biome , perhaps it's an other dumb idea so nvm xD
