### ISSUE TITLE
Biome tweaker prevents minecraft from starting up.

### ISSUE THREAD

**Issue by keybounce** [superckl/BiomeTweaker#19]
This is "not good".

In attempting to determine what was causing the core mod startup problem, I started turning off core mods.

With biome tweaker turned off, minecraft starts up. Log: https://gist.github.com/keybounce/4f6949bd6943145544b0

With biome tweaker turned on, minecraft fails to start. Log: https://gist.github.com/keybounce/e5c2dd5571d7b3449500

**Comment by superckl** [comment]
Can you try setting "enable light asm" to true?

**Comment by keybounce** [comment]
... I'll check the config file.

**Comment by keybounce** [comment]
Where is that set? There's no option in BiomeTweaker.cfg for it

**Comment by superckl** [comment]
I'll bet you haven't let BiomeTweaker regenerate the config in a while then. Delete the one that's there and let BiomeTweaker make a new one.

**Comment by keybounce** [comment]
OK. It will be a few minutes -- I'm writing up a report for Reika.

That odd startup tweak error? It finally went away when I disabled every core mod; dragonAPI was the last core mod.

**Comment by superckl** [comment]
A slight issue is that I can't reproduce this. For some reason Blocks.fire is being set to null. In other words, it doesn't exist in the registry. So, can you do something for me.

1. Run BiomeTweaker in light ASM mode.
2. Run BiomeTweaker without any scripts.
3. Unfortunately it's now a compatibility issue. You'll have to disable coremods until Minecraft starts with BiomeTweaker enabled.

**Comment by keybounce** [comment]
... That's ... Huh?

This is before any world is loaded. I thought the registry was only mapped/identified when a world was loaded and the world's block ID's were retrieved from level.dat.

Alright, so ... here's what I see when not using biome tweaker:
[19:30:11] [main/TRACE] [FML/]: Registry add: minecraft:fire 51 net.minecraft.block.BlockFire@7de16071 (req. id 51)
[19:30:11] [main/TRACE] [FML/]: Registry add: minecraft:fire 51 net.minecraft.item.ItemBlock@34c5d0cc (req. id 51)


And, if I add in Biome Tweaker,
[20:02:24] [main/TRACE] [FML/]: Registry add: minecraft:fire 51 net.minecraft.block.BlockFire@7d0e06bf (req. id 51)
[20:02:24] [main/TRACE] [FML/]: Registry add: minecraft:fire 51 net.minecraft.item.ItemBlock@191cc0f6 (req. id 51)


Now, on a hunch, add in Dragon API ...
[20:03:46] [main/TRACE] [FML/]: Registry add: minecraft:fire 51 net.minecraft.block.BlockFire@7f62602c (req. id 51)
[20:03:47] [main/TRACE] [FML/]: Registry add: minecraft:fire 51 net.minecraft.item.ItemBlock@1f185d74 (req. id 51)


Hmm. Add in CCC/Nei:

[20:05:04] [main/TRACE] [FML/]: Registry add: minecraft:fire 51 net.minecraft.block.BlockFire@59f4e49e (req. id 51)
[20:05:05] [main/TRACE] [FML/]: Registry add: minecraft:fire 51 net.minecraft.item.ItemBlock@70aaacc0 (req. id 51)

...

Alright, and this is NOT light asm mode -- that's sitting in a buffer in a window I forgot to save from.

ttCore is the next (only?) remaining "missing mod":
[20:07:19] [main/TRACE] [FML/]: Registry add: minecraft:fire 51 net.minecraft.block.BlockFire@10647742 (req. id 51)
[20:07:20] [main/TRACE] [FML/]: Registry add: minecraft:fire 51 net.minecraft.item.ItemBlock@44b0c913 (req. id 51)

and it gets up to the menu.

So ...

Reasonable realism:
[20:09:06] [main/TRACE] [FML/]: Registry add: minecraft:fire 51 net.minecraft.block.BlockFire@755392d5 (req. id 51)
[20:09:06] [main/TRACE] [FML/]: Registry add: minecraft:fire 51 net.minecraft.item.ItemBlock@6db66c18 (req. id 51)

...
Fastcraft .... works
Legacy craft? It has options to change how fire behaves ... works.

AAGGGHHHH ... I can't make it fail!
will test more in a few minutes

**Comment by keybounce** [comment]
Oh, silly, silly me:
"Run BiomeTweaker without any scripts."
I never turned the scripts back on!

I don't play with fire. Just lava. But ...
Yes! As soon as I loaded the tweaks, it fails!

[20:28:27] [main/TRACE] [FML/]: Registry add: minecraft:fire 51 net.minecraft.block.BlockFire@57ed5a07 (req. id 51)

The item form is not there! Only the block form.

**Comment by superckl** [comment]
Can you try commenting out sections of your script file to see what's causing it? I'd start with the lava part, but there's really no telling what it is by inspection.

**Comment by keybounce** [comment]
Alright, so with the only core mods being biome tweaker, and my script, it causes the problem.

Da Good News! I had a re-write of my script. My old version did not cause problems, but was getting too complicated to maintain. So, some difference between them is (probably?) causing the difference.

So ... what's different between them? Will test.

**Comment by superckl** [comment]
No hurry. I've got finals week coming up, so the amount of time I can spend here is going to drastically decrease over the next week and a half.

**Comment by keybounce** [comment]
For me, it's almost the opposite. A week and a half from now will be too late (Jampacked).

Today has been mostly toilet; tomorrow will be doctors.

**Comment by coolsquid** [comment]
Could you post your scripts? I want to see if I can reproduce the error. If I can, I'll do some debugging.

**Comment by keybounce** [comment]
Heh, it's not linked in this thread.

https://gist.github.com/keybounce/96a4743fd3fd995ec9a3
Has the current files from my "rewriteBiomeTops" branch.

I think this is the older version: https://gist.github.com/keybounce/96a4743fd3fd995ec9a3/724bd779dbf04fd20ae6ccb1fca04771d4f31104
I think that will give you something close to my last working version -- it says 11 days ago,

**Comment by keybounce** [comment]
This is crazy.

Here's the current, trimmed, crashing script:

beaches = forBiomesOfTypes("BEACH")
rivers = forBiomesOfTypes("River")
sandy = forBiomesOfTypes("Sandy")
nether = forBiomesOfTypes("Hell")

I verified in the logs that the only core mods or access transformers are FML, Forge, DeobfTweaker, and Biome tweaker.

... In fact, it happens with just
nether = forBiomesOfTypes("Hell")

but it doesn't happen with just
beaches = forBiomesOfTypes("BEACH")

hmm ...

nether = forBiomesOfTypes("HELL")
note the capitals -- also fails.

What the type?!?

Yep. Going back to the full config (I love git), with this change:

## nether = forBiomesOfTypes("Hell")
nether = forBiomes(8)

and it works.

**Comment by superckl** [comment]
Awesome. Now we can start answering questions rather than asking more. Try this build out:

http://jenkins.superckl.me/job/BiomeTweaker/69/

Commit: 3fe9c37033c6f44234a735e7612f4b60c756d243

**Comment by superckl** [comment]
http://minecraft.curseforge.com/mc-mods/228895-biometweaker/files/2238153
