### ISSUE TITLE
Decorations are stone now since update

### ISSUE THREAD

**Issue by davqvist** [superckl/BiomeTweaker#191]
BiomeTweaker 3.2.345
BTCore 1.0.39
Forge 2678
MC 1.12.2

So I made a big mistake, I want to release my modpack finally in about a week and I am going through my modlist and realised that I forgot to update BT and BTCore since months. So I updated to the current versions described above. But suddenly all the custom decorations are spawned in as Minecraft Stone instead of the blocks described.

Here are 2 of my scripts with decorations, both are generating Stone:
https://hastebin.com/roqucenaho.cpp
https://hastebin.com/xobakoxaje.bash

I would appreciate if you can have a look and see if I made a mistake, the syntax changed or if it is a bug.

**Comment by superckl** [comment]
If the syntax changed, you will see it in your log. Look for anything from "superscript" or "BiomeTweaker". I can look through it too, if you post it.

**Comment by davqvist** [comment]
Oh indeed 

https://hastebin.com/unisidipem.vbs

What is the new syntax?

**Comment by superckl** [comment]
It uses the base "set" command now. For example

object.set("block", deco)

**Comment by davqvist** [comment]
Thank you so much, you are my saviour.
