### ISSUE TITLE
1.12.2 Remove/Replace vanilla biomes?

### ISSUE THREAD

**Issue by ano19920** [superckl/BiomeTweaker#192]
Situation: Iʻm wanting to build on a map while using ConquestReforged and Biomes O Plenty. ConquestReforged now has biome/terrain generation, but I think Iʻve got the right script that disables those. However, Iʻve been trying to replace vanilla biomes with BOP biomes, but nothing I do seems to be working.

Here is the script Iʻm trying to use to replace vanilla biomes with a BOP biome.

> all = forAllBiomes()
all.registerGenBiomeRep(biomesoplenty_flower_field)

Here is the script Iʻm using to disable CR biomes.
> noBiomes = forBiomes("conquest:conquest_alder_swamp","conquest:conquest_oldgrowth_forest","conquest:conquest_ocean","conquest:conquest_lorein_forest","conquest:conquest_marsh","conquest:conquest_mediterranean","conquest:conquest_mega_boreal_forest","conquest:conquest_mesa_extreme_mod","conquest:conquest_moorland","conquest:conquest_mountains","conquest:conquest_bamboo_forest","conquest:conquest_beach_mod","conquest:conquest_birch_forest","conquest:conquest_bog","conquest:conquest_boreal_forest","conquest:conquest_cold_beach_mod,"conquest:conquest_deciduous_forest","conquest:conquest_desert_mod","conquest:conquest_forest_flower_plain","conquest:conquest_japanese_forest","conquest:conquest_jungle_mod","conquest:conquest_red_desert","conquest:conquest_river","conquest:conquest_tundra","conquest:conquest_tundra_marsh")
noBiomes.removeBOP()

...and here is the crash...
[crash-2018-06-09_03.44.18-server.txt](https://github.com/superckl/BiomeTweaker/files/2086803/crash-2018-06-09_03.44.18-server.txt)

Iʻve never worked with this kind of stuff before, so Iʻm not sure what do to beyond asking for help from people who DO have experience with all this.

**Comment by superckl** [comment]
You need to place biome resource locations in quotes, which you failed to do in your first script. You also are removing way too many biomes, so a climate type is empty. You need to add biomes to that type so it isn't empty.

**Comment by ano19920** [comment]
Okay, testing all of this now. How do I find out which biomes havenʻt been replaced? Will I have to individually type the vanilla biomes like I had to do with the ConquestReforged and make sure they are paired with their replacement?

**Comment by superckl** [comment]
Yes, you have to list the vanilla biomes. You can list I'd ranges such as 1-50 if you wish, but resource locations are preferred.

**Comment by ano19920** [comment]
Thanks so much! I **did** just get it to spawn mystic groves instead of any other vanilla biome, but my friend and I have a "VIP" list of BoP biomes we want to add in. Now that youʻve told me what to do, I can actually sort the BoP biomes over the vanilla ones "evenly" ... WOO! Again, thanks!! Love this mod!
