### ISSUE TITLE
Spawn usage confusion.

### ISSUE THREAD

**Issue by JustLiam040** [superckl/BiomeTweaker#193]
Hi, im not sure whether this is the correct place for this or not but i really couldnt figure out where to put it.
Long story short, im creating a modpack and im using your mod to influence its spawning.

The 3 biomes i have configured to use with the world are swamp, xeric shrubland and wasteland, however as far as i can tell none of these biomes support the capability of spawning mobs. I initially thought this would be due to the lack of grass blocks so i set the top block to grass but alas, no spawns. This led me to the conclusion it was based on the biome.

What im wondering, is there a way to specify that passive animals can spawn in the biome; im aware i can use the addSpawn string however this means i have to go down each passive entity one by one, while this isnt too much hassle i was just wondering whether there was a better alternative.

I also only want the mobs to spawn on grass, meaning the players would have to make a grass platform in the biome for the mobs to spawn on. So i was wondering, if when i added the passive entities to the spawn list, there was a way to ensure they didnt spawn unless there was grass for them to spawn on?

My thinking is that is would effectively work like the removeallspawn variable, but rather than removing "creature" spawns, it would work the inverse, and add them.

One final comment (i promise). I found in the pack squid were spawning in the ocean and river beyond control which meant other mobs (sharks etc.) werent spawning due to the mob cap being full of squids. My initial thought was to use the removespawn variable to remove squids from oceans and rivers. the use the addspawn command to add them back in; but with a lower weight than they originally had. Would this actually work? because so far it doesnt seem to however this might be a fault at my end.

**Comment by superckl** [comment]
For now, you have to add the creatures one by one. In a large modpack, there may be many, many passive creatures that don't normally spawn. Adding them all would be bad.

Passive creatures in the "CREATURES" list require grass too spawn you don't need to do anything additional there.

**Comment by superckl** [comment]
BiomeTweaker for MC 1.12 is now EOL, so I will not be addressing bugs that are related to BT - MC interactions. If this bug persists in BiomeTweaker for MC 1.18, please submit a new issue.
