### ISSUE TITLE
Enhancement?  Tweaking for specific dimensions

### ISSUE THREAD

**Issue by Trellinane** [superckl/BiomeTweaker#194]
I didn't know where to post this so my apologies if this is not an appropriate forum.  I could not see where you could place in the script to only affect the biomes generation for specific dimensions.  Can this be done currently or would this be an enhancement to the mod?

**Comment by superckl** [comment]
It's impossible with the way BiomeTweaker modifies biome generation. Use a mod like JustEnoughDimensions or DimensionalControl
