### ISSUE TITLE
[1.12.2] Constant Crashes {Please Close}

### ISSUE THREAD

**Issue by Flytre** [superckl/BiomeTweaker#196]
No matter what I put in a script, even running scripts other people said were successful, my game crashes when creating a new world.

Here's 1 of the crashes:
(https://github.com/superckl/BiomeTweaker/files/2130189/crash-2018-06-23_16.00.32-server.txt)

**Comment by superckl** [comment]
Update to the latest recommended Forge version please. You are several versions behind.

**Comment by Flytre** [comment]
Thanks so much! I recommend putting what version of Forge is required on the Curseforge page in an easily noticeable place, as most mods do not require such up-to-date versions of Forge. Thanks for the help! :)
