### ISSUE TITLE
[Enhancement] Rivers, Beaches, and Generate Structures

### ISSUE THREAD

**Issue by Flytre** [superckl/BiomeTweaker#197]
A good idea might be to add the ability to choose what type of river/beach spawns in each biome.

Eg: I'm creating a cold biome. I set the beaches to Stone Beach, and the rivers to Frozen River for that biome.

Eg. I don't like frozen rivers. I tweak all rivers to spawn as normal rivers.

One more Idea: On a biome-by-biome basis (if not possible, then for all biomes), allow users to edit spawn rates of vanilla generate structures. (Think super flat generate structure customization).

**Comment by superckl** [comment]
Unlikely that I will add the river control. It is outside the scope of what BiomeTweaker does internally. That is better suited in other more serious terrain overhaul mods. One option for this is to create a BiomeTweaker custom world type that allows river control.

Structure control is something I do want to add, but I haven't yet come up with a robust way to do it. They aren't handled very well in vanilla.

**Comment by Flytre** [comment]
Oh, Okay. The problem is that I have changed the water color of several biomes, so when a river generates with its default water color it looks super ugly. Thanks for responding!

**Comment by lobbienjonsji** [comment]
You might want to try dimensional control. That mod lets you pick beaches and rivers for your biomes. It works well with biome tweaker.

**Comment by Nathan22211** [comment]
and for structure pillar might be feasable

**Comment by superckl** [comment]
BiomeTweaker for MC 1.12 is now EOL, so I will not be addressing bugs that are related to BT - MC interactions. If this bug persists in BiomeTweaker for MC 1.18, please submit a new issue.
