### ISSUE TITLE
[1.12.2]Galacticraft Biomes behave strangely

### ISSUE THREAD

**Issue by Mike-U5** [superckl/BiomeTweaker#198]
I've been trying to edit Galacticraft biomes, but nothing seems to work.
I've tried moon = forBiomes(102) (Default biome ID in config)
I also tried moon = forBiomes("galacticraft:moon")
Eventually, I tried
everywhere = forAllBiomesExcept("minecraft:void")
And sure, enough, that works for every biome EXCEPT the ones added by Galacticraft.

I checked the output files, and Galacticraft generates 3 files called "Outer_Space", "Outer_Space_1" and "Outer_Space_2". I can't seem to edit any of those either. It's possible that I'm missing something but I think it's bug.

**Comment by superckl** [comment]
Please post your full script and log file.

**Comment by Mike-U5** [comment]
Test 1:
> moon = forBiomes(102)
> moon.set("temperature", 0)
> moon.set("genInitialSnow", true)
> moon.set("topBlock", "minecraft:emerald_block")   

Console Error 1:
> [12:51:21] [main/ERROR] [BiomeTweakerAPI]: Error applying tweaks. Biome ID 102 does not correspond to a biome! Check the output files for the correct ID!
 
Test 2:
> moon = forBiomes("galacticraftcore:moon")
> moon.set("temperature", 0)
> moon.set("genInitialSnow", true)
> moon.set("topBlock", "minecraft:emerald_block")
 
Console Error 2:
>[12:55:47] [main/ERROR] [BiomeTweakerAPI]: Error applying tweaks. Resource location galacticraftcore:moon does not correspond to a biome! Check the output files for the correct location!
 
Test 3:
> all = forAllBiomes()
> all.set("temperature", 0)
> all.set("genInitialSnow", true)
> all.set("topBlock", "minecraft:emerald_block") 

Console Error 3:
>[12:59:44] [main/ERROR] [SuperScript]: Failed to execute script command: set @ ScriptContext(scriptName=biomeTests.cfg, lineNumber=3). Reason: No property found for genInitialSnow
  
Despite the error, this script works almost as expected. Every biome in every dimension has a layer of snow-covered emerald blocks.
...except for the Galacticraft dimensions/biomes.
  
I tried changing a bunch of other things about the biomes too, but nothing works on GC biomes.

**Comment by AechtRob** [comment]
Galacticraft biomes actually have spaces in them, not underscores I think. Eg. I believe they are like this

Moon AND Mars: "galacticraftcore:outer space" [how messed up is that?]
Venus Mountain: "galacticraftplanets:outer space 1"
Venus Valley: "galacticraftplanets:outer space 2"

Given that the same biome is used to represent both Mars and the Moon I don't know how you'd use Biome Tweaker. Galacticraft uses a tonne of block variants instead of unique blocks and I have not been able to work out how to specify the correct metadata either. So I have also not managed to Galacticraft to play properly with BiomeTweaker at all.

**Comment by AechtRob** [comment]
Just in case it helps..... Galacticraft has an option in its own config to prevent/allow other mods from making changes to its world-gen. I think you'd need to set that to allow that to happen before BT could make changes. From looking at the config for Galacticraft it appears that the author only really wants you to use CofH world-gen-editing though? I'ts implied that that is better supported. But I don't know. Just check your GCraft configs.

**Comment by superckl** [comment]
BiomeTweaker for MC 1.12 is now EOL, so I will not be addressing bugs that are related to BT - MC interactions. If this bug persists in BiomeTweaker for MC 1.18, please submit a new issue.
