### ISSUE TITLE
Is there a way to remove Flowing Lava from nether generation?

### ISSUE THREAD

**Issue by KelleyEngineering** [superckl/BiomeTweaker#199]
I'm attempting to replace all Lava in the nether with Thermal Foundation mana, and so far I've succeeded, however Flowing Lava remains persistant. Is there a way to ensure that flowing lava gets replaced as well? I'd settle for it being completely removed as well. The script I'm using for the replacement is posted below.

```
Tweaker.setPlacementStage("PRE_POPULATE")
testUG.registerGenBlockRep("minecraft:lava", "thermalfoundation:fluid_mana")
testUG.registerGenBlockRep("minecraft:flowing_lava", "thermalfoundation:fluid_mana")
```

These are two pictures showing how Flowing lava continues to spawn upon initial Nether Generation. The Second picture shows that Lava was replaced in the ceiling but Flowing Lava pre-generated and doesn't update.
![2018-07-14_21 54 46](https://user-images.githubusercontent.com/27598014/42948722-1fbae820-8b3e-11e8-82ea-7072cafb5767.png)

![2018-07-14_21 54 58](https://user-images.githubusercontent.com/27598014/42948732-2401fed2-8b3e-11e8-8fc7-d71c50fbb759.png)

**Comment by superckl** [comment]
I would either remove flowing lava completely, or modify your replacement to not check metadata.

To remove the flowing lava, use the `removeFeature` command:
https://github.com/superckl/BiomeTweaker/wiki/Basic-Script-Commands#removefeature

To replace it, you need to use a block replacement object. See the `ingoreMeta` option in
https://github.com/superckl/BiomeTweaker/wiki/On-the-Topic-of-Block-Replacement#advanced-block-replacements

**Comment by KelleyEngineering** [comment]
CoolCool. I've opted to just remove the Nether_Lava feature. Thanks for the information.
