### ISSUE TITLE
New parsing is definitely messing up

### ISSUE THREAD

**Issue by keybounce** [superckl/BiomeTweaker#20]
Here's a "simple" config file

```
savannaMs = forBiomes(163, 164)
TF = forBiomes(40-58)
nether = forBiomesOfTypes("nether")
mesas = forBiomes(37-39, 165-167)

beaches = forBiomesOfTypes("BEACH")
rivers = forBiomesOfTypes("River")
mushroom=forBiomes(14)

plateauNonM = forBiomes(36, 38, 39)

unchanged = forBiomes(savannaMs, TF, nether, mesas)
sandyTops = forBiomes(beaches, rivers)
myceliumTops = forBiomes(mushroom)
hellify = forBiomes(plateauNonM)
sandAndClay = forBiomes(mesas)

yuckyTops = forAllBiomesExcept(unchanged, sandyTops, myceliumTops, hellify, sandAndClay)

yuckyTops.set("topBlock", "ganyssurface:coarse_dirt")
```

I've trimmed out everything not used. YuckyTops is getting coarse dirt, and it is excluding "sandAndClay"

Sand and clay is the mesas.

Mesas include 37

Mesa.json (all of them, actually) still have
  "Top Block": "ganyssurface:coarse_dirt",

Tested with Biome Tweaker 68

**Comment by superckl** [comment]
Yeah, this is indeed a bug and I see why. Give me a bit to move some things around in the parser.

**Comment by keybounce** [comment]
good (easy fix, I hope).

I was worried I'd have to go back to that older, messier config and try to patch it.

**Comment by superckl** [comment]
Try this build out:

http://jenkins.superckl.me/job/BiomeTweaker/71/

**Comment by keybounce** [comment]
yea

**Comment by keybounce** [comment]
Ahh ... nice ... Than you

**Comment by superckl** [comment]
I reworked it a bit more to be cleaner. The previous way created a new object for every parameter. Mind trying it out with your monstrous script?

http://jenkins.superckl.me/job/BiomeTweaker/75/

**Comment by keybounce** [comment]
Looks good.

**Comment by superckl** [comment]
http://minecraft.curseforge.com/mc-mods/228895-biometweaker/files/2238153
