### ISSUE TITLE
Removing Caves, Ravines, Dungeons, Lakes, ETC.

### ISSUE THREAD

**Issue by theDaleighChronicle** [superckl/BiomeTweaker#201]
Not really an issue, I'm just terrible with scripts and coding. What would I need to do to remove caves, ravines, dungeons, and lakes from the world generation for all biomes? I'm using BoP and the custom world gen for 1.12 won't work in this case, as it won't spawn the BoP biomes.

**Comment by superckl** [comment]
If you're looking to get started using BT, watch the first YouTube tutorial and join the discord channel. This isn't the place to ask how to get started.
