### ISSUE TITLE
Top block not appearing

### ISSUE THREAD

**Issue by WACriminalG2** [superckl/BiomeTweaker#203]
I'm building a custom world-gen that includes some biomes from Twilight Forest. I've got the biomes generating in the world, but now I'm encountering an odd error.

My intent/expectation:
The biome should generate with a thin layer/topblock of dirt or grass (I've tried both), with red foliage and grass, dotted here and there with Quark's nether smokers. Below that, it should be netherrack all the way to bedrock, dotted with Quark basalt and nether quartz.

What I'm getting:
No dirt or grass at all, and no smokers. Just a solid plain of netherrack, marked with the occasional obsidian column and mangrove trees -- the foliage of which seems normal and green. It does, however, look like the basalt and quartz are generating in small amounts.

Here's the scripting I'm using: https://pastebin.com/uF3Q1MDg

**Comment by superckl** [comment]
Do you have BiomeTweakerCore installed with the relevant option enabled in the config?

**Comment by WACriminalG2** [comment]
I do, yeah.

Further wrinkle: I remembered I could just pull grass blocks out of creative mode, so I put some down to test the grass color, and it's just a dark green instead of a shade of red.

**Comment by superckl** [comment]
I'll need a full log file then.

**Comment by WACriminalG2** [comment]
Here ya go: https://pastebin.com/U81ybf6z

**Comment by superckl** [comment]
It doesn't seem like BTCore is properly applying it's tweaks. This looks to be a problem with your setup not allowing some core mods to properly execute.

**Comment by superckl** [comment]
BiomeTweaker for MC 1.12 is now EOL, so I will not be addressing bugs that are related to BT - MC interactions. If this bug persists in BiomeTweaker for MC 1.18, please submit a new issue.
