### ISSUE TITLE
Custom biome crashing world

### ISSUE THREAD

**Issue by WACriminalG2** [superckl/BiomeTweaker#204]
I'm trying to make a biome to build a spawn town in that naturally has no hostile mobs. Unfortunately, it seems to be causing the game to time out (not crash, just time out and close the server), and even looking at the logs, I'm not sure why.

What I've done:

Initial biome creation script: https://pastebin.com/qB0mwWmj 
Biome selection script (running this as a single-biome world for testing purposes) : https://pastebin.com/piGT7U4e
Actual biome definition script: https://pastebin.com/3sDTSr2p

The log: https://pastebin.com/uA34v6pC

The lines from the log I think are most relevant, if I'm understanding them correctly:

> [02:31:10] [main/ERROR]: Failed to execute script command: set @ ScriptContext(scriptName=00015_BiomeSelection.cfg, lineNumber=37). Reason: null
> [02:31:10] [main/ERROR]: Failed to execute script command: set @ ScriptContext(scriptName=00300_IdyllicPlateau.cfg, lineNumber=2). Reason: null
> [02:31:10] [main/ERROR]: Failed to execute script command: set @ ScriptContext(scriptName=00300_IdyllicPlateau.cfg, lineNumber=11). Reason: Can not set boolean field net.minecraft.world.biome.Biome.field_76765_S to null value
> [02:31:10] [main/ERROR]: Failed to execute script command: set @ ScriptContext(scriptName=00300_IdyllicPlateau.cfg, lineNumber=12). Reason: Can not set boolean field net.minecraft.world.biome.Biome.field_76766_R to null value

However, the referenced line numbers, respectively, are:

> RepGroup34 = forBiomes("minecraft:mutated_birch_forest_hills")

> blank line

> idyllic.set("height",1.5)
> idyllic.set("heightVariation",0.025)

And (with the possible exception of the blank line) I don't understand how any of these could possibly be considered null.

**Comment by WACriminalG2** [comment]
Worth noting that I had almost the same problem when I wasn't running it as single-biome. That is, I was using Idyllic Plateau to replace a particular beach biome just to see if I could get it mixed into worldgen. World loaded fine, but I knew there was a problem because my scripts should make Idyllic the only valid spawn biome, and I wasn't anywhere near a plateau. Sure enough, debug menu showed I was in a simple Grasslands biome.

So I pulled out a Nature's Compass, selected Idyllic, searched...and the game timed out.

**Comment by superckl** [comment]
Try changing your true/false values to lowercase. `true` rather than `TRUE`. That should fix those errors. As for the timing out, that's likely caused by it not being able to find the biome. Use the BOP command to avoid that.

I'm not really sure why it's not appearing in your world. I'll have to look into it more, but you should verify the same happens in a non-BOP world type.

**Comment by WACriminalG2** [comment]
Actually, changing the TRUEs to trues fixed it. New world loaded right up with me in the Idyllic Plateau.

I...need to adjust the Exotic Birds swan spawn weight....

Anyway, thank you very much for the tip. I'll close this issue.
