### ISSUE TITLE
Height Not Working for BOP

### ISSUE THREAD

**Issue by talayawhite** [superckl/BiomeTweaker#205]
> makeHigher = forBiomes(79)
> 
> makeHigher.set("height", 2.0)
> makeHigher.set("topBlock", "minecraft:stone")
> 

Works just fine for vanilla biomes.
Does not work for BOP biomes. (I tried more than one in case it was just Sacred Springs.)

"topBlock", "minecraft:stone" works for BOP, but setting the height doesn't.

**Comment by superckl** [comment]
BOP biomes use their own config system. Can you not change it in BOP's settings?

**Comment by talayawhite** [comment]
that doesn't seem to be working either. -.-;
Also it's a pain to change every single biome config when I want to tweak
the height for more than one biome. I could maybe find a way around... I
was hoping that would be BT.
Thanks for answering. :)
-T
