### ISSUE TITLE
COULDN'T LOAD WORLD, shows biometweaker disabled

### ISSUE THREAD

**Issue by yaolin902** [superckl/BiomeTweaker#207]
I got this error when I try to load my single player world.
[https://pastebin.com/6PnxR4bx](https://pastebin.com/rT4bydBT)

Here is my mod list: [https://pastebin.com/rT4bydBT](https://pastebin.com/rT4bydBT)

I noticed that BiomeTweaker was disabled, but I don't know why.

Full fml-client-log-0: [https://paste.ee/p/LuwOI](https://paste.ee/p/LuwOI)

**Comment by superckl** [comment]
I have no idea what this... but it's also on 1.7.10 which is no longer supported.
