### ISSUE TITLE
How does setWorld work?

### ISSUE THREAD

**Issue by lobbienjonsji** [superckl/BiomeTweaker#209]
The description of the setWorld script command says, that the commands following will be only executed in the selected world, however, when I replaced the top and fillerblocks of all biomes in the selected dimension, biomes in other dimensions got changed by that replacement as well. 
https://github.com/lobbienjonsji/Scripts-n-stuff/blob/master/arcticunderground.txt

**Comment by superckl** [comment]
Read the description more carefully. Only certain commands can be done world-specific. Those are block replacements through the replacement system (not by the set command), and custom decorations.
