### ISSUE TITLE
Mysterious Holes [odd mod interaction]

### ISSUE THREAD

**Issue by PCSpinner** [superckl/BiomeTweaker#211]
forge-1.12.2-14.23.5.2768
BiomeTweaker-1.12.2-3.2.354
BiomeTweakerCore-1.12.2-1.0.39
worleycaves-1.3.0

I'm trying to build a world that is a barren wasteland and have come across an odd interaction between BiomeTweaker and WorlyCaves. When I use BT to change the topBlock to a modded block, wherever WC would have a cave break the surface, you instead get a pattern of 1 block holes.

Screenshots:  https://imgur.com/a/YvkcQqg

Each hole appears where both the X- and Z-coordinates are divisible by 4, and the bottom of the hole ends on an even Y value. Going into Spectator Mode, I can see that these holes form under the surface as well, not always breaking the topBlock. This only happens when the topBlock is a modded block; modded fillers with a minecraft topBlock work just fine.

My BT script:  https://pastebin.com/ptwR8JfZ

To be thorough, I've tested with multiple mod's blocks as the topBlock, and with a couple different cave generator mods (as well as vanilla) and this is the only combination where it happens.

EDIT: was going to report this to WorleyCaves as well, and it seems to be an iteration with any terrain gen mod + WC.

**Comment by superckl** [comment]
BiomeTweaker for MC 1.12 is now EOL, so I will not be addressing bugs that are related to BT - MC interactions. If this bug persists in BiomeTweaker for MC 1.18, please submit a new issue.
