### ISSUE TITLE
Decorations applying to all worlds

### ISSUE THREAD

**Issue by clubpetey** [superckl/BiomeTweaker#213]
BT version: 3.2.354
Forge: 2795

I used Tweaker.setWorld() in the script below to try and make sure all changes applied to my custom dimension (42).  However, when I switched back to the overworlds, the beaches had my "tree trunks" in them...  I would expect that any decorations that are done after setWorld() apply only to that world.

Also, question... Is the "count" setting a float? I want to place a tree trunk only once every 3-4 chunks. I was wondering if I can set Count to 0.25...

`Tweaker.setWorld(42)
beach = forBiomes(16)
beach.removeAllSpawns("CREATURE")
beach.addSpawn("net.minecraft.entity.passive.EntityChicken", "CREATURE", 100, 2, 2)
beach.addSpawn("net.minecraft.entity.passive.EntityCow", "CREATURE", 60, 1, 2)
beach.addSpawn("net.minecraft.entity.passive.EntitySheep", "CREATURE", 40, 2, 2)
beach.removeOre("CUSTOM")

Tweaker.setStage("PRE_INIT")
beach.set("clayPerChunk", 10)

Tweaker.setPlacementStage("POST_ORES")
dec = newTreeDecoration()
dec.set("count", 1)
dec.addSoilBlock("minecraft:sand")
dec.set("leafBlock", "minecraft:air")
dec.set("checkCanGrow", false)

beach.addDecoration(dec)`

**Comment by superckl** [comment]
The issue you are having is that that latter part of your script is executing before the former. You set the script stage to "PRE_INIT" halfway through your script, so anything after that will actually execute before anything before it which will default to "POST_INIT". There's no need for you to set the script stage like that.

To answer your question, no, count is not a float. Count determines how many times it attempts to generate per chunk.
