### ISSUE TITLE
[Suggestion] Control OreGen in biomes

### ISSUE THREAD

**Issue by clubpetey** [superckl/BiomeTweaker#214]
It would be great to be able to add ore-gen control to BiomeTweaker.  You already have the code in decorations to creating ore blobs, and commands to remove standard ore gen, so i'd love to be able to remove ore from mods and then re-inset it using the decoration functions so that different biomes could have different ore distributions.

Not looking for any fancy vein layouts.

**Comment by superckl** [comment]
Couldn't this be achieved by setting ore counts per biome? I'm not sure why you can't do this right now.

**Comment by clubpetey** [comment]
Where can you set ore counts? I see removeOre() only, and that applies to standard ores.  I'm talking about modded ores (Like Copper from Immersive Engineering, or Cobalt from Tinker's Construct).  Most mods have some ore-gen control in their config files, but not all, and most of the time you cannot control it per-biome.

A central place to setup ore gen when you have 6-10+ mods adding ores is helpful.

**Comment by superckl** [comment]
That's not straightforward to do. Many nods implement ores in their own way, making standardization pretty much impossible.

You can set ore counts when you create your own ore decorations. Remove the existing ore and add your own decoration with the desired count.

**Comment by clubpetey** [comment]
Well, that's a bummer, I supposed I can use the individual configs and turn off the ore gen, and then centralize it here.  That will be close enough.
