### ISSUE TITLE
Unable to replace tropicraft:water with minecraft:water

### ISSUE THREAD

**Issue by kriNon** [superckl/BiomeTweaker#217]
Error: https://pastebin.com/uDjDRJzP
Script: https://pastebin.com/tU96NWRc
Minecraft 1.12.2
Forge 14.23.5.2796
BiomeTweaker 3.2
Tropicraft 7.1.8.105

**Comment by superckl** [comment]
That error is from your file name, not a bug in BT. Remove the quotes from the file name.

**Comment by kriNon** [comment]
Fixed the error with my file name, however it still isn't working. Now I'm no longer getting an error in my log, however it just isn't doing anything.

**Comment by kriNon** [comment]
@superckl I did some further testing, and when Tweaker.setPlacementStage("BIOME_BLOCKS") the result is that the water from tropicraft gets removed entirely, but sand gets generated on top of where all the rivers and oceans would have been. However when I set it to Tweaker.setPlacementStage("POST_POPULATE") then nothing gets replaced and the tropicraft:water is not removed.
