### ISSUE TITLE
Biome removal problems

### ISSUE THREAD

**Issue by KevinVM1996** [superckl/BiomeTweaker#218]
So i am trying to remove all biomes exept for the ocean biome and adding animal spawns to the ocean biome. i tried to do it by doing this
otherBiomes = forBiomesexcept("minecraft.ocean")
oceanBiome = forBiome("minecraft.ocean")
otherBiomes.remove()

oceanBiome.addSpawn("net.minecraft.entity.passive.EntitySheep", "CREATURE", 12, 4, 4)
oceanBiome.addSpawn("net.minecraft.entity.passive.EntityPig", "CREATURE", 12, 4, 4)
oceanBiome.addSpawn("net.minecraft.entity.passive.EntityChicken", "CREATURE", 12, 4, 4)
oceanBiome.addSpawn("net.minecraft.entity.passive.EntityCow", "CREATURE", 12, 4, 4)

but that doesnt seem to work i get large oceans with small other biomes. any ideas where i went wrong ?

**Comment by KevinVM1996** [comment]
also where should i ask questions like this

**Comment by superckl** [comment]
There is a discord channel linked in the home page of the wiki.

**Comment by KevinVM1996** [comment]
a thanks

**Comment by KevinVM1996** [comment]
ill close this one then
