### ISSUE TITLE
Unable to remove all but one biome

### ISSUE THREAD

**Issue by ErroneousDictation** [superckl/BiomeTweaker#219]
I'm trying to remove all vanilla biomes so that I can add back a few of the vanilla biomes + a few of the biomes from Biomes O' Plenty. I made a test script to try to get removing all but one biome working, but it keeps giving me the divide by zero error. I've tried multiple things, but I don't know what's wrong. 

Minecraft version is 1.12.2 and BiomeTweaker is 1.12.2-3.2.354

![image](https://user-images.githubusercontent.com/43498968/51782959-9debd480-20f7-11e9-9ee9-76fa5ea06e85.png)

**Comment by ErroneousDictation** [comment]
I guess to save time, I should probably just ask how to create a script that generates a world with only the biomes in the list below. That way, I have a fully working script so fixing any issues or making a new script later on will be easier.
```
Vanilla Biomes:
Mountains			3	mountains
Taiga				5	taiga
Frozen River			11	frozen_river
Snowy Tundra			12	snowy_tundra
Snowy Mountains			13	snowy_mountains
Taiga Hills			19	taiga_hills
Snowy Taiga			30	snowy_taiga
Snowy Taiga Hills		31	snowy_taiga_hills
Giant Tree Taiga		32	giant_tree_taiga
Giant Tree Taiga Hills		33	giant_tree_taiga_hills
Wooded Mountains		34	wooded_mountains
Taiga Mountains			133	snowy_taiga_mountains
Snowy Taiga Mountains		158	snowy_taiga_mountains
Giant Spruce Taiga		160	giant_spruce_taiga
Giant Spruce Taiga Hills	161	giant_spruce_taiga_hills

BoP Biomes:
Alps				43	alps
Coniferous Forest		52	coniferous_forest
Grove				60	grove
Meadow				69	meadow
Mountain			71	mountain
Shield				83	shield
Snowy Coniferous Forest		85	snowy_coniferous_forest
Temperate Rainforest		88	temperate_rainforest
Alps Foothills			95	alps_foothills
```

**Comment by superckl** [comment]
Have you looked at your log at all? Your script syntax is incorrect. The log would tell you that.

**Comment by ErroneousDictation** [comment]
I am rather new to using mods like this, so I didn't really know that there were log files. Either way, I was able to get it working through trial and error:
```
desiredBiomes = forBiomes(5,7,12,19,31,32,33,133,158,160,161)
desiredBiomes.addToGeneration("DESERT", 2000)
desiredBiomes.addToGeneration("WARM", 2000)
desiredBiomes.addToGeneration("COOL", 2000)
desiredBiomes.addToGeneration("ICY", 2000)
desiredBiomes.set("enableSnow", true)
desiredBiomes.set("genWeight", 2000)

desiredBiomesThatAreNotCurrentlySnowyBiomesButWhichIWouldGreatlyPreferBecomeSnowyBiomes = forBiomes(33,161)
desiredBiomesThatAreNotCurrentlySnowyBiomesButWhichIWouldGreatlyPreferBecomeSnowyBiomes.set("temperature", -0.2)

undesiredBiomes = forAllBiomesExcept(desiredBiomes)
undesiredBiomes.registerGenBiomeRep(161)
undesiredBiomes.remove()
```
This only works on vanilla world generation, unfortunately. When using the Biomes O' Plenty generation with most BoP biomes disabled, it gives me the divide by zero error again despite the fact that all four biome types are filled via BiomeTweaker. I'd check logs to try to figure out what the issue is, but I don't know which log file specifically applies. 
https://cdn.discordapp.com/attachments/517162067086802946/538980266581032990/unknown.png

**Comment by superckl** [comment]
You need to use addToGenerationBOP for BOP worlds.

**Comment by ErroneousDictation** [comment]
I've added this to the end of my script:
```
desiredBiomes.addToGenerationBOP("ICE_CAP", 10)
desiredBiomes.addToGenerationBOP("TUNDRA", 10)
desiredBiomes.addToGenerationBOP("BOREAL", 10)
desiredBiomes.addToGenerationBOP("COLD_SWAMP", 10)
desiredBiomes.addToGenerationBOP("WET_TEMPERATE", 10)
desiredBiomes.addToGenerationBOP("DRY_TEMPERATE", 10)
desiredBiomes.addToGenerationBOP("COOL_TEMPERATE", 10)
desiredBiomes.addToGenerationBOP("WARM_TEMPERATE", 10)
desiredBiomes.addToGenerationBOP("HOT_SWAMP", 10)
desiredBiomes.addToGenerationBOP("TROPICAL", 10)
desiredBiomes.addToGenerationBOP("MEDITERANEAN", 10)
desiredBiomes.addToGenerationBOP("SAVANNA", 10)
desiredBiomes.addToGenerationBOP("HOT_DESERT", 10)
desiredBiomes.addToGenerationBOP("WASTELAND", 10)
desiredBiomes.addToGenerationBOP("HELL", 10)
```
It still seems to give me the divide by zero error, and still only on the BoP generation. I've tried making the names lowercase, but that didn't work.
