### ISSUE TITLE
Flat Bedrock seems to mess with bottom layer

### ISSUE THREAD

**Issue by hoklai1997** [superckl/BiomeTweaker#220]
I've been experimenting with flat bedrock using the mod bedrockbgone (that might not be the exact name) as well as cofh (world gen options), and while the bedrock will be flattened, there is a layer of stone and ores that look to be replacing the blocks where normal "jagged" bedrock would have otherwise spawned.

**Comment by superckl** [comment]
How is this a bug with BiomeTweaker? I'm going to need you to elaborate.
