### ISSUE TITLE
Command Tabbing Issue

### ISSUE THREAD

**Issue by SynexWolf** [superckl/BiomeTweaker#222]
Minecraft: 1.12.2
Forge: forge-14.23.5.2824
Mod Version: BiomeTweaker-1.12.2-3.2.354.jar
(BiomeTweaker Core has not be installed)

When BiomeTweaker is installed, when you type the command partially and tab the rest, it seems that the chat box gets cleared and if you keep tabbing it'll cycle through the command from the start, this minor bug is somewhat annoying when entering a command quickly and if you want to know the possible sub-commands for a command.
Would love to see this fixed, Thanks!

**Comment by superckl** [comment]
BiomeTweaker for MC 1.12 is now EOL, so I will not be addressing bugs that are related to BT - MC interactions. If this bug persists in BiomeTweaker for MC 1.18, please submit a new issue.
