### ISSUE TITLE
Problem with modded WATER_CREATURE entities ?

### ISSUE THREAD

**Issue by sebi225** [superckl/BiomeTweaker#223]
Hi guys! I'm using BiomeTweaker-1.12.2-3.2.354

I just want to spawn dolphins in the oceans, but I don't manage to do so.
 
Here is my script:

allBiomes = forAllBiomes()
ocean = forBiomes(0)
allBiomes.removeAllSpawns("CREATURE")
allBiomes.removeAllSpawns("WATER_CREATURE")
allBiomes.removeAllSpawns("CAVE_CREATURE")
allBiomes.removeAllSpawns("MONSTER")
ocean.addSpawn("drzhark.mocreatures.entity.aquatic.MoCEntityDolphin", "WATER_CREATURE", 100, 2, 8)

 
-If I replace the dolphin from mocreatures by the vanilla squid, it works
-If I try to spawn a land creature from mocreature (for example: Racoons) it works

 --> So, either the problem comes from WATER_CREATURE type, or it comes from the mocreature dolphin (but I don't think so, since other water creatures from other mods such as ZAWA or TheBetweenLand don't spawn too)

 
I need help please guys. Everything but that seems perfectly working!

**Comment by sebi225** [comment]
up

**Comment by sebi225** [comment]
up :/

**Comment by sebi225** [comment]
up

**Comment by superckl** [comment]
There has been a long standing issue with mocreatures. They have never played nice with spawning mechanics, since MoCreatures uses their own spawning system. You might want to try a different mod since this is something BT can't do.
