### ISSUE TITLE
lord of the rings

### ISSUE THREAD

**Issue by Shinerz** [superckl/BiomeTweaker#225]
Heya. Got a problem with 1.7.10 LOTR mod (v34.3) and BiomeTweaker (latest?). BiomeTweaker works, but doesn't generate any of the lotr biomes into the output folders - only the plain minecraft biomes. Doesn't generate scripts either. No entities or dimensions folder. Is the problem in 1.7.10 version or have I done something wrong? Downloaded from http://www.9minecraft.net/biometweaker-mod/ , replicated the situation with different modpacks (with the same two mods) - Twilight Forest creates biome files - no dimensions or entities folders from tutorial vid https://www.youtube.com/watch?v=hLPoo7irfg8

**Comment by superckl** [comment]
The problem is the 1.7.10 version. It is no longer supported.

Also, please never download any mods from 9minecraft. Download them from their official sites. CurseForge is the official site for BiomeTweaker.
