### ISSUE TITLE
block replacement doesn't work

### ISSUE THREAD

**Issue by LEWeee** [superckl/BiomeTweaker#227]
I have tried to make a desert world and replace all dirt/grass with sand, yet despite this dirt and grass still spawns in my world, especially near rivers. Everywhere else it's fine (which is expected when my word is desert biomes and nothing else) and it bothers me. Is this a bug or am I just doing something wrong?

Here is an image od dirt in my world.
![obrázok](https://user-images.githubusercontent.com/16687385/56750768-c631b080-6784-11e9-813f-8d31861c33ab.png)

And here is the code that I made to construct that world: https://hastebin.com/xosulilira

Minecraft 1.12
BiomeTweaker 3.2 (3.2.354)

**Comment by superckl** [comment]
Your script is incorrect. Please join the discord channel linked in the homepage of the wiki for help with scripts.
