### ISSUE TITLE
Dead link on FAQ.

### ISSUE THREAD

**Issue by sustained** [superckl/BiomeTweaker#229]
> When using BiomeTweaker with Biomes O' Plenty, make sure to read this post on mushroom biomes.

The link is dead. :sweat:

They did change the URL structure but even when I accounted for that... dead. Looks like they deleted the post?

I wonder what it said!

**Comment by superckl** [comment]
It talks about the world being overrun with mushroom biomes if you had settings incorrect. Shouldn't be an issue anymore.
