### ISSUE TITLE
Failed to find meaning in object assignment.

### ISSUE THREAD

**Issue by sustained** [superckl/BiomeTweaker#230]
My script looks like this:

```
biomes = forAllBiomesExcept("minecraft:plains")
vanilla = (biomes, 0-39)

vanilla.registerGenBiomeRep("minecraft:plains")

plains = forBiomes("minecraft:plains")
plains.addToGeneration("WARM", 2000)
plains.addToGeneration("COOL", 2000)
plains.addToGeneration("DESERT", 2000)
plains.addToGeneration("ICY", 2000)
```

This is the error:

```
[13:09:38] [Client thread/ERROR] [SuperScript]: Failed to find meaning in object assignment vanilla = (biomes, 0-39) @ ScriptContext(scriptName=DisableVanillaBiomesForTesting.cfg, lineNumber=2). Reason: No matching objects or registrations found.
```

I am pretty sure I'm doing this right:

![bild](https://user-images.githubusercontent.com/5995080/60590708-93afbf80-9d94-11e9-8704-2df955d50a02.png)

![bild](https://user-images.githubusercontent.com/5995080/60590748-b510ab80-9d94-11e9-9754-46f55fe19268.png)

**Comment by superckl** [comment]
Have you tried it without the numeric range? Please at least make an attempt to find the source of the issue before posting an issue.

**Comment by sustained** [comment]
The range should work, should it not? That's what the docs say.

`0-39` are all valid biome IDs...

If two lines of code...

```
biomes = forAllBiomesExcept("minecraft:plains")
vanilla = (biomes, 0-39)
```

...cause it to blow up then clealy there's a problem, wouldn't you say?. It's literally comprised of two examples from the docs.

I'll try without but I don't see why this wouldn't work... hence the issue.

**Comment by superckl** [comment]
I'm asking you to test if it is the range that is the issue, and not something else. There is no way to tell what is causing the issue from what you posted, only that there is an issue.

**Comment by sustained** [comment]
Ah... well, yeah! I misunderstood. :sweat_smile: I shall do so and report back.

**Comment by superckl** [comment]
I just realized, You need to replace the line `vanilla = (biomes, 0-39)` with `vanilla = forBiomes(biomes, 0-39)`. That should fix the issue.
