### ISSUE TITLE
World Gen Crash

### ISSUE THREAD

**Issue by mxnmnm** [superckl/BiomeTweaker#231]
So the issue seems to involve biometweaker and biomes o plenty.  Since biomes o plenty stopped working on 1.12.2 I hope the issue was on biome tweaker's end so here's the crash report https://paste.dimdev.org/baqosayola.mccrash

**Comment by superckl** [comment]
Do you have any scripts active?

**Comment by mxnmnm** [comment]
Hmmmm this was a while ago, and I have massively changed my scripts since then (less of them and I've kept better track of them) so yea. I'll reopen this if I run into a similar enough issue but it doesn't seem to have happened since (probably even with the older scripts otherwise I would have mentioned that). If you want peace of mind I can send the older scripts (or something that should be close enough) but ik it probably has a bunch of junk code in it that doesn't do much from when I wasn't too sure how things worked which might have contributed to the problem.
