### ISSUE TITLE
Taint

### ISSUE THREAD

**Issue by mitchngwen** [superckl/BiomeTweaker#232]
I am trying to add taint from Thaumcraft to every biome my world, how can I do this?

**Comment by superckl** [comment]
This is a place to report bugs, not ask questions. Ask in the discord channel linked on the wiki or seek help from someone that knows Thaumcraft.

**Comment by mitchngwen** [comment]
I do not use Discord. What do I put in the script to make a specific plant to spawn in every biome?

**Comment by superckl** [comment]
Based on the very sparse information you've given me, I would suggest a cluster decoration.

**Comment by mitchngwen** [comment]
So what I am trying to do is cover everything with taint which is like vines or grass it's a thin layer, I know the ID of it, I have no idea what to put it the config file at all I have tried: forAllBiomes.addFlower("thaumcraft:taint_feature", 200) but it did nothing. I am really stuck any help would be awesome.

**Comment by mitchngwen** [comment]
So where can I donate?

**Comment by superckl** [comment]
The `addFlower` command doesn't do anything unless another mod uses, as detailed in the command description. 

To cover everything with tainted soil, all you need to do is use the `set` command to set the `topBlock` field to tainted soil.

To cover the world with taint fiber, I would recommend simply using a cluster decoration with a very large count (so it generates nearly everywhere) and the soil block set to tainted soil.

To spawn monsters, you only need to use the `addSpawn` command.

See:
https://github.com/superckl/BiomeTweaker/wiki/Basic-Script-Commands#set
https://github.com/superckl/BiomeTweaker/wiki/Custom-Decorations
https://github.com/superckl/BiomeTweaker/wiki/Basic-Script-Commands#addspawn

If you are not sure where to even start, there is a (slightly out of date) Youtube video tutorial linked on the homepage of the wiki.

**Comment by mitchngwen** [comment]
This is my script so far but it is not working, well the addspawn command
works just fine but other than that no luck.

all = forAllBiomes()

all.addSpawn("thaumcraft.common.entities.monster.tainted.EntityTaintSeed",
"MONSTER", 700, 4, 8)
all.addActualFillerBlock("thaumcraft:taint_soil")

taint = forBlock("minecraft:grass")

taint.setProperty("variant", "taint")
all.registerGenBlockRep("minecraft:grass", taint)
all.registerGenBlockRep(4, "minecraft:grass", "thaumcraft:taint_soil")
all.set("contiguousReplacement", true)

**Comment by superckl** [comment]
I don't think you quite understand what most of the commands are doing. To set the top block to tainted soil, all you need to do is `all.set("topBlock", "thaumcraft:taint_soil")`, assuming that is the correct resource location.

For the taint fiber, you need to find the resource location for taint fiber. I don't know it offhand, and then use that to make a cluster decoration. You seem to have not even attempted a cluster decoration.
