### ISSUE TITLE
Root Height and Height Variation Reset on World Generation

### ISSUE THREAD

**Issue by Wackywee** [superckl/BiomeTweaker#235]
Every time I save the .json for the ocean file it resets when I generate the world. Thanks for any help.

Actually, now that I've tested it, NOTHING seems to work. Everything just gets reset. I tried changing the block in Biomes O' Plenty Kelp Forest to "minecraft:sand" and it just got replaced again.

**Comment by superckl** [comment]
You're editing the "output" files. They are output, not input. You need to write scripts to interact with Biometweaker.

**Comment by Wackywee** [comment]
Oh shoot, thanks my man.
