### ISSUE TITLE
Can't Height with set("height", X)

### ISSUE THREAD

**Issue by Wackywee** [superckl/BiomeTweaker#236]
This is just additional information regarding the problem.

![2019-07-22_16 45 08](https://user-images.githubusercontent.com/52543173/61667802-9cfbc000-aca0-11e9-8f23-a26aa3e6983f.png)
![2019-07-22_16 36 12](https://user-images.githubusercontent.com/52543173/61667803-9cfbc000-aca0-11e9-9992-e99453c84efe.png)

The top image is 
deepocean.set("height", -1.999)

The bottom image is
deepocean.set("height", -2.0)

I'm failing to understand the problem here. Any help is appreciated.

**Comment by superckl** [comment]
I dunno man, that's Minecraft, not me. I guess things get wild when you set the base height to 0. I'd recommend not doing that.

**Comment by Wackywee** [comment]
Ah, that's a shame. Thanks anyways tho

**Comment by Wackywee** [comment]
> I dunno man, that's Minecraft, not me. I guess things get wild when you set the base height to 0. I'd recommend not doing that.

By the way, in case you didn't catch what I was asking about, I meant that the ocean height doesn't drop at all unless I drop it to -2.0. Is that intentional? Does the mod only work with integers?
