### ISSUE TITLE
Can't Change Height with set("height", X)

### ISSUE THREAD

**Issue by Wackywee** [superckl/BiomeTweaker#237]
Back again to harass you some more.

So, in contingency with my last post: https://github.com/superckl/BiomeTweaker/issues/236

What I was trying to say was that any height other than -2.0 had no effect. In fact, the input of -2.0 had affected the deep ocean biome exactly as I had expected. I've put in -1.5, -1.75, -1.8, -1.999, and they all have no effect- the deep ocean biome ends at y=32. Is that intentional? Does the mod only work with integers? The heightVariation tool seems to work as expected, so is there an issue with the height tool?

Anyways, here's the code

deepocean = forBiomes("minecraft:deep_ocean")
deepocean.set("height", -1.8)
deepocean.set("heightVariation", 0.7)
deepocean.set("oceanTopBlock", "minecraft:sand")

The oceanTopBlock tool also works as well.

________________________________________________
I recently added this line to my script, and it had no affect.
deepocean.set("genWeight", 1000)

___
I also can't seem to edit the Biomes O' Plenty Kelp Forest biome at all either.
Here's the biome ID (found in the BoP config file) and the script:

"kelp_forest": 99,

kelp = forBiomes(biomesoplenty:kelp_forest)
kelp.set("oceanTopBlock", "minecraft:sand")
kelp.set("topBlock", "minecraft:sand")
kelp.set("genWeight", 1000)

I have also tried
kelp = forBiomes(99)

**Comment by superckl** [comment]
BiomeTweaker for MC 1.12 is now EOL, so I will not be addressing bugs that are related to BT - MC interactions. If this bug persists in BiomeTweaker for MC 1.18, please submit a new issue.
