### ISSUE TITLE
[Enchancement] Custom gamma per-biome

### ISSUE THREAD

**Issue by clubpetey** [superckl/BiomeTweaker#239]
In addition to the fog setting, using the set() function to change the gamma level on a per-biome basis would create some cool lighting effects, especially when set very low.  Here some quick code I used in another project that changes gamma per dimension. 

	@SubscribeEvent
	public void onClientTick(ClientTickEvent event) {

		int dim = Minecraft.getMinecraft().thePlayer.dimension;

		if (config.setLightLevel) {

			float lightLevel = config.getGamma(dim); // try 0.7F

			Minecraft.getMinecraft().gameSettings.gammaSetting = lightLevel;

		}

	}

**Comment by superckl** [comment]
BiomeTweaker for MC is now EOL, so I will not be addressing bugs that are related to BT - MC interactions. If this bug persists in BiomeTweaker for MC 1.18, please submit a new issue.
