### ISSUE TITLE
genWeight doesn't seem to work

### ISSUE THREAD

**Issue by Qohelethh** [superckl/BiomeTweaker#24]
I'm using BiomeTweaker 0.9.97 with Biomes O' Plenty. I'm trying to increase how many Savanna M biomes there are in the world. I tried realistic values first, then upped genWeight to 1000. I still can't get it to work.

>savannaM = forBiomes(163)
>savannaM.set("genWeight", 1000)

**Comment by superckl** [comment]
Biomes O' Plenty doesn't use the BiomeManager for it's generation weights. They provide a config for setting gen weights.

**Comment by superckl** [comment]
I will look into making the set command work for them, but it is not pressing since you can set them in their config.

**Comment by Qohelethh** [comment]
Ah, thanks. That makes sense. Unfortunately, BOP doesn't let you set biome
weights for vanilla biomes; only for BOP biomes, which is why I was trying
to use BiomeTweaker.

**Comment by superckl** [comment]
BiomeTweaker works for vanilla biomes. Biomes O' Plenty uses the BiomeManager for those.

**Comment by Qohelethh** [comment]
Hmm, I was only trying to alter the weight of vanilla biomes in BOP worlds,
but I couldn't get it to work.

**Comment by superckl** [comment]
I've tested with Biomes O' Plenty and it seemed to work fine. Not sure why it's not for you.
