### ISSUE TITLE
Cyclops Spawn - Controlling Spawning Using BiomeTweaker

### ISSUE THREAD

**Issue by MokahTGS** [superckl/BiomeTweaker#240]
Weights in Biome Tweaker don't seem to be working for me.  I'm using this on a server:

cyclops = forBiomes(37, 38, 39, 165, 166, 167)
cyclops.addSpawn("com.github.alexthe666.iceandfire.entity.EntityCyclops", "MONSTER", 100, 1, 1)

Doing this gets Cyclops to spawn, but too many of them.  So I change the weight number to 10, and reload the scripts using BTReload and nothing changes, even after clearing out mobs and resetting the difficulty to easy.  Is there a better way to be using this to get mobs to spawn naturally in a biome, without dozens of them spawning?

**Comment by tyon2006** [comment]
bump.

**Comment by superckl** [comment]
Reloading the scripts won't clear out your previous entries. You need to restart. Let me know if it still happens with a lower weight after restarting

**Comment by MokahTGS** [comment]
Reloading/restarting does not change anything.

**Comment by superckl** [comment]
I am not experiencing this issue in test worlds. Here is a standard mob distribution I've seen, never more than 2 cyclops in view.
![2020-05-02_22 11 30](https://user-images.githubusercontent.com/2230216/80897756-f5e19580-8cc1-11ea-9458-2c344b56688e.png)

If you are reloading a lot, you are adding the entry to the mob list many times without removing it. Perhaps that is why you are seeing inflated spawn rates?
