### ISSUE TITLE
BiomeTweaker not working

### ISSUE THREAD

**Issue by WarPhoenix** [superckl/BiomeTweaker#242]
I'm currently playing with Minecolonies 1.12.2. This requires lots of flat, clean space to put houses down for a village. So, I added BiomeTweaker and BiomeTweakerCore to my modpack which currently holds 12 mods: Better Builder's Wands, Bibliocraft, BiomeTweaker, BiomeTweakerCore, Chisel, ConnectedTexturesMod, Inventory Tweaks, JEI, Minecolonies, Neat, OreExcavation and Waystones.  
BiomeTweaker ver is is 1.12.2-3.2.354 made by superckl
Forge ver is 14.23.5.2847

I'm hoping to create a world that is mostly roofed forest with mountains and rivers so I can create a nice village in a green valley. Removing grass decoration and flowers would also be ideal. 
Alternatively, just turn every grass into roofed forest color and not care about biomes.

After two hours of trying to do this (it's just a few lines, innit?!), I used the sample script to turn the world into mostly desert so it was easier to see where my errors were. 
I put it in the script folder, relaunched the game, created a new world. 

Aaaaand discovered that biome tweaks itself does not seem to be functioning as I was met with a face full of forest. I'm missing a simple "turn this mod on" or "look at this script" or maybe even a version incompatibility. It should just.... work, right? plop scripts in scripts folder, run game, start new world. 
I'm not sure what I'm missing and it's a little disheartening that I can't even get the example to work. Thank you in advance for any advice/help.

**Comment by superckl** [comment]
The example is quite old, but even so, BiomeTweaker is not meant for overhauls like this. You're better off using a mod meant to create world generation from the ground up.
