### ISSUE TITLE
Constant "Biome ID does not correspond to a biome" errors

### ISSUE THREAD

**Issue by LighttronPrime** [superckl/BiomeTweaker#244]
I just spent about eight hours fully rewriting mob spawning from scratch for my upcoming modpack. When I opened a world, none of the changes had applied whatsoever. I tried several attempts at diagnosing the problem, before eventually finding a huge number of errors in the log stating

[20:17:21] [Client thread/INFO]: Error applying tweaks. Biome ID 138 does not correspond to a biome! Check the output files for the correct ID!

There are over 100 similar errors. These errors cannot be correct, I'm using Biomes O' Plenty, and have confirmed that there are no biome ID conflicts with AntiIDConflict. I'm using Climate Control to cause Biomes O' Plenty biomes to generate in the default world type, based off of climate control's world generation, which could be the source of the problem. I'm attach my biometweaker script as well as the relevant log to help diagnose this issue.

Any help would be greatly appreciated!

`Desert = forBiomes(2, 130, 150, 58, 17)
HotPlains = forBiomes(35, 36, 163, 164, 73, 193, 146, 190)
Mesa = forBiomes(37, 38, 39, 165, 166, 167, 208)
Jungle = forBiomes(21, 22, 188, 64, 199, 252, 171, 172)
Swamp = forBiomes(6, 109, 134, 153, 203, 205, 206, 251)
Plains = forBiomes(1, 48, 129, 215, 201, 202, 217)
Forest = forBiomes(4, 18, 27, 28, 132, 152, 155, 156, 174, 187, 195, 216, 227, 213)
Ocean = forBiomes(0, 212, 24, 71)
Mountain = forBiomes(3, 214, 34, 131, 162, 199)
ColdForest = forBiomes(5, 19, 32, 33, 41, 40, 60, 66, 133, 144, 204, 145, 160)
SnowyForest = forBiomes(30, 31, 47, 148, 158)
SnowyMountain = forBiomes(13, 254, 255)
Mushroom = forBiomes(14, 15)
SnowyPlains = forBiomes(12, 140, 253)
Dead = forBiomes(49, 238, 250, 236, 170, 173, 175)
MagicForest = forBiomes(29, 61, 62, 97, 157, 198, 243)
Origin = forBiomes(194)
Ender = forBiomes(110)
Rainbow = forBiomes(114)
Tainted = forBiomes(98)
Beach = forBiomes(16, 25, 26)
River = forBiomes(7, 11)
Luminous = forBiomes(112, 113)
Crag = forBiomes(239)
Sacred = forBiomes(186)
MagicPlains = forBiomes(219, 209)
Evil = forBiomes(142, 196, 147, 159)

OverworldBiomes = forBiomes(Desert, HotPlains, Mesa, Jungle, Swamp, Plains, Forest, Ocean, Mountain, ColdForest, SnowyForest, SnowyMountain, SnowyPlains, Dead, MagicForest, Ender, Rainbow, Beach, River, Luminous, Crag, Sacred, MagicPlains, Evil)
Butter = forBiomes(HotPlains, Jungle, Swamp, Plains, Forest, Mountain, ColdForest, MagicForest, Ender, Rainbow, Beach, Luminous, Sacred, MagicPlains)
SkelWar = forBiomes(Desert, HotPlains, Mesa, Dead)
Trx = forBiomes(Desert, Mesa, SnowyPlains, Dead)
Conc = forBiomes(Desert, Jungle, Swamp, Forest, ColdForest, SnowyPlains, Dead, Ender)
Sup = forBiomes(Desert, HotPlains, Forest, Mountain, ColdForest, SnowyMountain, SnowyPlains, Sacred)
Fest = forBiomes(Desert, Mesa, Plains, Forest, ColdForest, SnowyMountain, SnowyForest, SnowyPlains, Sacred)
Roc = forBiomes(Mesa, Jungle, Plains, Forest, Mountain, ColdForest, SnowyForest, SnowyMountain, SnowyPlains)
Plain = forBiomes(Plains, HotPlains, MagicPlains)
Arm = forBiomes(Hot, Plain, Rainbow)//error
Bas = forBiomes(Mesa, Mountain, Dead, Luminous, Crag)
Har = forBiomes(Mesa, Plains, MagicPlains)
Earth = forBiomes(Mesa, Jungle, Mountain, SnowyMountain, Dead, Luminous, Crag)
Cou = forBiomes(Mesa, Mountain, Crag)
Jun = forBiomes(Jungle, Sacred)
Wet = forBiomes(Jungle, Swamp, River, Beach, Sacred)
Gross = forBiomes(Swamp, Dead)
Dee = forBiomes(Forest, MagicForest, Ender, Rainbow)
Goo = forBiomes(Swamp, Beach, River)
For = forBiomes(Forest, Ender)
AllFor = forBiomes(Forest, ColdForest, SnowyForest, MagicForest)
Miny = forBiomes(AllFor, Ender)
Dire = forBiomes(Forest, ColdForest, Mountain, SnowyMountain, Rainbow)
Wit = forBiomes(MagicForest, Evil, Swamp)
Water = forBiomes(Ocean, Beach, River)
Mount = forBiomes(Mountain, SnowyMountain, Luminous, Crag)
Mou = forBiomes(Mountain, Luminous, Crag)
Snowy = forBiomes(SnowyForest, SnowyMountain, SnowyPlains)
Mage = forBiomes(Evil, MagicForest)
Dark = forBiomes(Mage, Dead)
Ars = forBiomes(MagicForest, MagicPlains, Crag, Sacred, Luminous, Evil)
Dry = forBiomes(MagicForest, Luminous, Ender, Rainbow)
Pix = forBiomes(Dry, Crag)
Pech = forBiomes(Mage, Sacred, Crag, Luminous)
Rose = forBiomes(Sacred, MagicPlains, Rainbow)
Bird = forBiomes(Sacred, Crag, Luminous, Jungle, MagicPlains)

Desert.addSpawn("gaia.entity.monster.EntityGaiaAnubis", "MONSTER", 3, 1, 2)
Desert.addSpawn("gaia.entity.monster.EntityGaiaSphinx", "MONSTER", 1, 1, 1)
Desert.addSpawn("com.wildmobsmod.entity.monster.tarantula.EntityTarantula", "MONSTER", 5, 1, 4)
Jungle.addSpawn("com.wildmobsmod.entity.monster.tarantula.EntityTarantula", "MONSTER", 5, 1, 4)
Desert.addSpawn("gaia.entity.monster.EntityGaiaCockatrice", "MONSTER", 5, 1, 4)
HotPlains.addSpawn("gaia.entity.monster.EntityGaiaCockatrice", "MONSTER", 5, 1, 4)
SkelWar.addSpawn("net.daveyx0.primitivemobs.entity.monster.EntityDSkeletonWarrior", "MONSTER", 5, 1, 4)
Trx.addSpawn("lcrdrfs.entities.EntityRoboDino", "MONSTER", 3, 1, 3)
Conc.addSpawn("crazypants.enderzoo.entity.EntityConcussionCreeper", "MONSTER", 5, 1, 4)
Sup.addSpawn("net.daveyx0.primitivemobs.entity.monster.EntitySupportCreeper", "MONSTER" 5, 1, 4)//error
Fest.addSpawn("net.daveyx0.primitivemobs.entity.monster.EntityFestiveCreeper", "MONSTER" 5, 1, 4)//error
Desert.addSpawn("com.wildmobsmod.entity.passive.hyena.EntityHyena", "CREATURE", 5, 1, 5)

HotPlains.addSpawn("com.wildmobsmod.entity.passive.hyena.EntityHyena", "CREATURE", 5, 1, 5)
Plain.addSpawn("crazypants.enderzoo.entity.EntityFallenMount", "MONSTER", 3, 1, 4)
Plain.addSpawn("crazypants.enderzoo.entity.EntityFallenKnight", "MONSTER", 5, 1, 4)
Plain.addSpawn("gaia.entity.monster.EntityGaiaMinotaur", "MONSTER", 1, 1, 1)
Plain.addSpawn("gaia.entity.monster.EntityGaiaMinotaurus", "MONSTER", 3, 1, 2)
Plain.addSpawn("gaia.entity.monster.EntityGaiaSatyr", "MONSTER", 5, 1, 4)
Plain.addSpawn("gaia.entity.monster.EntityGaiaCentaur", "MONSTER", 5, 1, 4)
Plain.addSpawn("com.wildmobsmod.entity.passive.bison.EntityBison", "CREATURE", 5, 2, 6)
Arm.addSpawn("com.wildmobsmod.entity.passive.armadillo.EntityArmadillo", "CREATURE", 5, 1, 4)
HotPlains.addSpawn("com.wildmobsmod.entity.passive.cheetah.EntityCheetah", "CREATURE", 3, 1, 1)

Bas.addSpawn("cofh.thermalfoundation.entity.monster.EntityBasalz", "MONSTER", 5, 1, 4)
Har.addSpawn("gaia.entity.monster.EntityGaiaHarpy", "MONSTER", 5, 1, 4)
Roc.addSpawn("net.daveyx0.primitivemobs.entity.monster.EntityRocketCreeper", "MONSTER", 5, 1, 4)
Earth.addSpawn("am2.entities.EntityEarthElemental", "MONSTER", 5, 1, 4)
Cou.addSpawn("com.wildmobsmod.entity.passive.cougar.EntityCougar", "CREATURE", 3, 1, 1)

Jun.addSpawn("biomesoplenty.common.entities.EntityJungleSpider", "MONSTER", 7, 1, 6)
Jun.addSpawn("gaia.entity.monster.EntityGaiaCobbleGolem", "MONSTER", 5, 1, 4)
Jun.addSpawn("gaia.entity.monster.EntityGaiaCobblestoneGolem", "MONSTER", 3, 1, 2)
Jun.addSpawn("gaia.entity.monster.EntityGaiaShaman", "MONSTER", 3, 1, 2)
Jun.addSpawn("gaia.entity.monster.EntityGaiaHunter", "MONSTER", 5, 1, 4)
Wet.addSpawn("com.wildmobsmod.entity.passive.dragonfly.EntityDragonfly", "AMBIENT", 10, 1, 4)//error
Jun.addSpawn("net.daveyx0.primitivemobs.entity.passive.EntityChameleon", "CREATURE", 5, 1, 3)

Gross.addSpawn("biomesoplenty.common.entities.EntityGlob", "MONSTER", 6, 1, 4)
Swamp.addSpawn("net.daveyx0.primitivemobs.entity.monster.EntityLilyLurker", "CREATURE", 5, 1, 1)
Swamp.addSpawn("gaia.entity.monster.EntityGaiaNaga", "MONSTER", 3, 1, 2)
Swamp.addSpawn("gaia.entity.monster.EntityGaiaSiren", "MONSTER", 5, 1, 4)
Swamp.addSpawn("gaia.entity.monster.EntityGaiaSludgeGirl", "MONSTER", 5, 1, 4)
Swamp.addSpawn("gaia.entity.monster.EntityGaiaSwamper", "MONSTER", 3, 1, 2)

Dee.addSpawn("com.wildmobsmod.entity.passive.deer.EntityDeer", "CREATURE", 5, 1, 4)
Goo.addSpawn("com.wildmobsmod.entity.passive.goose.EntityGoose", "CREATURE", 4, 1, 8)
For.addSpawn("gaia.entity.monster.EntityGaiaWerecat", "MONSTER", 5, 1, 4)
For.addSpawn("gaia.entity.monster.EntityGaiaSpriggan", "MONSTER", 3, 1, 2)
For.addSpawn("gaia.entity.monster.EntityGaiaDryad", "MONSTER", 5, 1, 4)
For.addSpawn("gaia.entity.passive.EntityGaiaPropFlowerCyan", "MONSTER", 5, 1, 4)
AllFor.addSpawn("net.daveyx0.primitivemobs.entity.monster.EntityMotherSpider", "MONSTER", 5, 1, 4)
Miny.addSpawn("crazypants.enderzoo.entity.EntityEnderminy", "CREATURE", 3, 1, 1)
Dire.addSpawn("com.wildmobsmod.entity.passive.direwolf.EntityDireWolf", "CREATURE", 3, 1, 1)
Wit.addSpawn("net.minecraft.entity.monster.EntityWitch", "MONSTER", 5, 1, 3)
Dire.addSpawn("com.wildmobsmod.entity.passive.ocelot.EntityWMOcelot", "CREATURE", 3, 1, 1)

Ocean.addSpawn("com.wildmobsmod.entity.monster.seascorpion.EntitySeaScorpion", "WATER_CREATURE", 3, 1, 2)
Water.addSpawn("gaia.entity.monster.EntityGaiaMermaid", "MONSTER", 3, 1, 2)
Water.addSpawn("gaia.entity.monster.EntityGaiaSharko", "MONSTER", 3, 1, 2)
Water.addSpawn("gaia.entity.monster.EntityGaiaSahuagin", "MONSTER", 5, 1, 4)
Water.addSpawn("am2.entities.EntityWaterElemental", "WATER_CREATURE", 5, 1, 4)
Ocean.addSpawn("com.wildmobsmod.entity.passive.jellyfish.EntityJellyfish", "WATER_CREATURE" 5, 1, 4)//error
Ocean.addSpawn("com.tmtravlr.jaff.entities.EntityFishPufferfish", "WATER_CREATURE", 2, 1, 3)
Ocean.addSpawn("com.tmtravlr.jaff.entities.EntityFishClownfish", "WATER_CREATURE", 2, 1, 3)
Water.addSpawn("com.tmtravlr.jaff.entities.EntityFishSalmon", "WATER_CREATURE", 8, 1, 4)
Water.addSpawn("com.tmtravlr.jaff.entities.EntityFishCod", "WATER_CREATURE", 10, 1, 4)

Mount.addSpawn("cofh.thermalfoundation.entity.monster.EntityBlitz", "MONSTER", 5, 1, 4)
Mou.addSpawn("gaia.entity.monster.EntityGaiaValkyrie", "MONSTER", 1, 1, 1)
Mou.addSpawn("gaia.entity.monster.EntityGaiaDullahan", "MONSTER", 5, 1, 4)
Mou.addSpawn("gaia.entity.monster.EntityGaiaGryphon", "MONSTER", 5, 1, 4)
Mou.addSpawn("gaia.entity.monster.EntityGaiaBanshee", "MONSTER", 3, 1, 2)
Mount.addSpawn("com.wildmobsmod.entity.passive.goat.EntityGoat", "CREATURE", 5, 1, 4)

ColdForest.addSpawn("gaia.entity.monster.EntityGaiaCyclops", "MONSTER", 5, 1, 4)
ColdForest.addSpawn("gaia.entity.monster.EntityGaiaNineTails", "MONSTER", 3, 1, 2)
ColdForest.addSpawn("gaia.entity.monster.EntityGaiaYukiOnna", "MONSTER", 3, 1, 2)
ColdForest.addSpawn("gaia.entity.monster.EntityGaiaFutakuchiOnna", "MONSTER", 5, 1, 4)

Snowy.addSpawn("cofh.thermalfoundation.entity.monster.EntityBlizz", "MONSTER", 5, 1, 4)
SnowyForest.addSpawn("gaia.entity.monster.EntityGaiaVampire", "MONSTER", 1, 1, 1)
SnowyForest.addSpawn("gaia.entity.monster.EntityGaiaDhampir", "MONSTER", 3, 1, 2)
Snowy.addSpawn("gaia.entity.monster.EntityGaiaYeti", "MONSTER", 5, 1, 4)
Snowy.addSpawn("gaia.entity.monster.EntityGaiaKobold", "MONSTER", 5, 1, 4)
Snowy.addSpawn("gaia.entity.monster.EntityGaiaSelkie", "MONSTER", 3, 1, 2)

Mage.addSpawn("net.daveyx0.primitivemobs.entity.monster.EntityDSummoner", "MONSTER", 3, 1, 2)
Dark.addSpawn("crazypants.enderzoo.entity.EntityWitherWitch", "MONSTER", 5, 1, 2)
Dark.addSpawn("com.wildmobsmod.entity.monster.faded.EntityFaded", "MONSTER", 7, 1, 4)
Ars.addSpawn("am2.entities.EntityManaCreeper", "MONSTER", 5, 1, 4)
Ars.addSpawn("am2.entities.EntityManaElemental", "MONSTER", 5, 1, 4)
Mage.addSpawn("gaia.entity.monster.EntityGaiaWitch", "MONSTER", 3, 1, 2)
Dark.addSpawn("com.wildmobsmod.entity.monster.dreath.EntityDreath", "MONSTER", 3, 1, 2)
Dry.addSpawn("am2.entities.EntityDryad", "CREATURE", 3, 1, 4)
Pix.addSpawn("biomesoplenty.common.entities.EntityPixie", "AMBIENT", 3, 1, 4)//error
Pix.addSpawn("am2.entities.EntityLightMage", "CREATURE", 1, 1, 1)
Pech.addSpawn("thaumcraft.common.entities.monster.EntityPech", "CREATURE", 1, 1, 1)
Evil.addSpawn("am2.entities.EntityHecate", "MONSTER", 5, 1, 4)
Dead.addSpawn("am2.entities.EntityHecate", "MONSTER", 5, 1, 4)

Beach.addSpawn("net.daveyx0.primitivemobs.entity.monster.EntityBrainSlime", "MONSTER", 10, 1, 4)
Rose.addSpawn("biomesoplenty.common.entities.EntityRosester", "CREATURE", 5, 1, 4)
Ender.addSpawn("chylex.hee.entity.mob.EntityMobEnderman", "MONSTER", 5, 1, 4)
Ender.addSpawn("gaia.entity.monster.EntityGaiaEnderDragonGirl", "MONSTER", 4, 1, 4)
Ender.addSpawn("thehippomaster.MutantCreatures.MutantEnderman", MONSTER", 2, 1, 1)
Butter.addSpawn("com.wildmobsmod.entity.passive.butterfly.EntityButterfly", "AMBIENT", 5, 1, 4)
Butter.addSpawn("twilightforest.entity.passive.EntityTFTinyBird", "AMBIENT", 5, 1, 5)//error
Bird.addSpawn("biomesoplenty.common.entities.EntityBird", "AMBIENT", 5, 1, 4)//error
OverworldBiomes.addSpawn("thehippomaster.MutantCreatures.MutantCreeper", "MONSTER", 1, 1, 1)
OverworldBiomes.addSpawn("thehippomaster.MutantCreatures.MutantZombie", "MONSTER", 1, 1, 1)
OverworldBiomes.addSpawn("thehippomaster.MutantCreatures.MutantEnderman", "MONSTER", 1, 1, 1)
OverworldBiomes.addSpawn("thehippomaster.MutantCreatures.MutantSkeleton", "MONSTER", 1, 1, 1)`

[latest.log](https://github.com/superckl/BiomeTweaker/files/3990929/latest.log)

**Comment by superckl** [comment]
Have you confirmed the biomes actually correspond to the IDs you are using? Verify this by looking in the Biometweaker output files
