### ISSUE TITLE
Biome generation in custom worldgen types (1.12.2)

### ISSUE THREAD

**Issue by GutontheInternet** [superckl/BiomeTweaker#245]
I'm having troubles with removing biomes from modded world types.
Specifically I'm trying to remove all savanna-type biomes, roofed forest biomes and flower forest biomes from Beta+ and RTG-Realistic world types. My script seems to work fine with vanilla world types but not with modded ones. 
I've tried several scripts, but none of them appear to be working properly outside of vanilla worldgen, here are my most recent ones:

1)
SavannaBiomes = forBiomesOfTypes("SAVANNA")
SavannaBiomes.registerGenBiomeRep(1)

2)
SavannaBiome = forBiomes("minecraft:savanna")
MSavannaBiome = forBiomes("minecraft:mutated_savanna")
PSavannaBiome = forBiomes("minecraft:savanna_rock")
MPSavannaBiome = forBiomes("minecraft:mutated_savanna_rock")
FlowerBiome = forBiomes("minecraft:mutated_forest")
SavannaBiome.registerGenBiomeRep(21)
PSavannaBiome.registerGenBiomeRep(21)
MSavannaBiome.registerGenBiomeRep(2)
MPSavannaBiome.registerGenBiomeRep(2)
FlowerBiome.registerGenBiomeRep(4)

Please send help.

**Comment by superckl** [comment]
Those mods use their own biome generation, so you need to remove biomes through that mod. BiomeTweaker cannot have special cases for each generation mod.
