### ISSUE TITLE
Can't replace stone.

### ISSUE THREAD

**Issue by Gliese-832-c** [superckl/BiomeTweaker#250]
This is my biome config:

Tweaker.setScriptStage("BIOME_REGISTRY")
Tweaker.createBiome("moon_flats", "minecraft:plains")

moon_flats = forBiomes("biometweaker:moon_flats")
others = forAllBiomesExcept(moon_flats)

moon_flats.registerGenBlockRep("minecraft:water", "minecraft:air")
moon_flats.removeDecoration("CACTUS")
moon_flats.removeDecoration("DEAD_BUSH")
moon_flats.removeDecoration("DESERT_WELL")
moon_flats.removeDecoration("FLOWERS")
moon_flats.removeDecoration("FOSSIL")
moon_flats.removeDecoration("GRASS")
moon_flats.removeDecoration("LAKE_LAVA")
moon_flats.removeDecoration("LAKE_WATER")
moon_flats.removeDecoration("TREE")
moon_flats.removeFeature("LAKE")
moon_flats.removeFeature("LAVA")

moon_flats.set("name", "Moon Flats")
moon_flats.set("topBlock", "contenttweaker:electron_matter")
moon_flats.set("fillerBlock", "contenttweaker:proton_matter")
moon_flats.set("skyColor", 16772324)
moon_flats.set("fogColor", 16772324)
moon_flats.set("grassColor", 9470285)
moon_flats.set("foliageColor", 9470285)
moon_flats.set("enableRain", false)
moon_flats.set("GRASSPERCHUNK", 0)
moon_flats.set("genVillages", false)
moon_flats.set("genStrongholds", false)

moon_flats.removeAllSpawns("CREATURE")
moon_flats.removeAllSpawns("MONSTER")
moon_flats.removeAllSpawns("AMBIENT")
moon_flats.removeAllSpawns("WATER_CREATURE")

moon_flats.registerGenBlockRep("minecraft:stone", contenttweaker:moon_regolith)

moon_flats.addActualFillerBlock("contenttweaker:moon_regolith")

The stone doesn't get replaced with contenttweaker:moon_regolith.

**Comment by PCSpinner** [comment]
> moon_flats.registerGenBlockRep("minecraft:stone", contenttweaker:moon_regolith)

You forgot the quotation marks around contenttweaker:moon_regolith

**Comment by Gliese-832-c** [comment]
I tried fixing that, it still doesn't work.

**Comment by PCSpinner** [comment]
Try setting 
Tweaker.setPlacementStage("BIOME_BLOCKS")

I know scripts are supposed to default to that, but sometimes it helps to explicitly set it.

**Comment by Gliese-832-c** [comment]
Where should I put this?

**Comment by PCSpinner** [comment]
Anywhere before 

> moon_flats.registerGenBlockRep("minecraft:stone", contenttweaker:moon_regolith)
> 
> moon_flats.addActualFillerBlock("contenttweaker:moon_regolith")

should work. Personally, I have it just after all my Tweaker.createBiome(). It might also help to put the stone replacement in before the topBlock and fillerBlock changes.

**Comment by Gliese-832-c** [comment]
Thanks, I'll try.

**Comment by Gliese-832-c** [comment]
Sorry for the long silence. I've finally come around to working on the biomes of my pack again, and it still doesn't seem to work.

These are my biome scripts: 

Moon Flats:
https://hastebin.com/gifekuviso.cpp

Moon Hills:
https://hastebin.com/uvehikaqip.cpp

(Note that contenttweaker:electron_matter is just a placeholder, it's easy for me to see if the script has worked. I'll replace it with something that makes more sense on the moon like moon_surface_rock or something once I manage to get it working. Unfortunately that's not the case.)

**Comment by PCSpinner** [comment]
I just loaded up your script, replacing the contenttweaker blocks with a couple I already had made, and it worked fine. You're problem seems to lie elsewhere. The two most likely problems that I can think of off hand are either

A)  Your content tweaker blocks are not registered the way you think they are. I assume the topBlock is properly coming out as "contenttweaker:electron_matter"; if so, try replacing stone with that.

B)  Whatever mod you are using to create your "moon" dimension is populating blocks in a way that BiomeTweaker can't catch the stone. I know that Lost Cities' "cavern" world type does this.

**Comment by Gliese-832-c** [comment]
contenttweaker:electron_matter loads just fine. Here's the proof: https://i.imgur.com/0JcEWjq.png

I am using Advanced Rocketry to generate the dimension. This is how the dimension looks: https://i.imgur.com/KEchJa8.png

**Comment by PCSpinner** [comment]
> contenttweaker:electron_matter loads just fine. Here's the proof: https://i.imgur.com/0JcEWjq.png

Is contenttweaker:moon_regolith loading fine? 
Did you try replacing stone with contenttweaker:electron_matter?

I can't get AR to load, so I can't really comment on whether that's the problem or not.

**Comment by superckl** [comment]
I'm closing this for lack of a response. You can respond even though the issue if closed if you want to pursue this further.
