### ISSUE TITLE
The "Creating a Desert World" example script doesn't actually remove all biomes

### ISSUE THREAD

**Issue by colby-boucher** [superckl/BiomeTweaker#252]
This is for the most recent 1.12.2-1.0.39 version.

For reference, I'm talking about [this](https://github.com/superckl/BiomeTweaker/wiki/Example-Scripts), and I don't just mean edge biomes, mutations and oceans. Despite including the following code:

`#Remove other biomes
all = forAllBiomes()
all.set("genWeight", 11)
all.set("isSpawnBiome", false)`

Biomes other than desert, river and ocean end up spawning. Just flying around in creative mode, I've found jungle and plains biomes appearing so far. Edit: Also taiga. It's probably just about everything.

**Comment by superckl** [comment]
The script is likely outdated. Have you checked your log for errors?

**Comment by otakup0pe** [comment]
Hmm I'm seeing this behavior as well. Not seeing any errors. I tend to see what seems to be the normal amount of oceans / rivers, with the _occasional_ other biome.

**Comment by superckl** [comment]
BiomeTweaker for MC is now EOL, so I will not be addressing bugs that are related to BT - MC interactions. If this bug persists in BiomeTweaker for MC 1.18, please submit a new issue.
