### ISSUE TITLE
[Enhancement] Allow unlocalized names for biome name

### ISSUE THREAD

**Issue by yezhiyi9670** [superckl/BiomeTweaker#253]
Sometimes I need to use unlocalized names for biome name because I need to change to a biome name which can fit different languages (or simply to allow localizing biome names).

EDIT: I mean a function to translate the name instantly when it's set, because localizing a name when it's used will be difficult (maybe).

**Comment by superckl** [comment]
This is not very easy to do, since localization only happens on the client. However, biome names are not only client side. I'll look into how this might be accomplished, but how crucial is it for what you want to do?

**Comment by superckl** [comment]
BiomeTweaker for MC is now EOL, so I will not be addressing bugs that are related to BT - MC interactions. If this bug persists in BiomeTweaker for MC 1.18, please submit a new issue.
