### ISSUE TITLE
[Enhancement] Show biome registry names in the biome list command

### ISSUE THREAD

**Issue by yezhiyi9670** [superckl/BiomeTweaker#254]
Mojang removed support for numeric item ids in 1.8, and completely removed numeric ids in 1.13. What do they mean? They mean that we should use understandable registry names instead of numeric ids.

In fact, using numeric ids not only makes the code unreadable, but is also very dangerous under modded environment. Removing or adding a mod might cause major changes to biome ids, and the ids may randomly vary on each startup even if we don't add or remove a mod.

So here I suggest adding registry names to biome list, and optionally remove numeric ids.

**Comment by superckl** [comment]
... what? BiomeTweaker uses registry names, and optionally numeric IDs.

**Comment by yezhiyi9670** [comment]
I mean add registry names to the biome list command.
