### ISSUE TITLE
topBlock replacement coding bug

### ISSUE THREAD

**Issue by AechtRob** [superckl/BiomeTweaker#257]
When I use the .set "topBlock" for a biome I receive an error in my log file telling me that BiomeTweaker has tried to locate the block minecraft:grass_block

This block does not exist in MC 1.12.2. It should be just minercraft:grass in that version. It wasn't named grass_block until a later minecraft version.

(I'm also unclear on why it just tries to locate grass, as that is not the topblock in all biomes)

**Comment by superckl** [comment]
I'll need to see the full error and your script.

**Comment by AechtRob** [comment]
I can't find my old scripts and logs. It was part of a large modded pack which I had to move on with. In vanilla it seems to work fine. I'll let you know if/when I find it again, but the error log definitely stated that BiomeTweaker couldn't find the resource minecraft:grass_block

Apologies - I'll provide more info next time.

**Comment by superckl** [comment]
All right, well I'm closing this issue until you can find those scripts then.

**Comment by Dinerell** [comment]
The resource location is "minecraft:grass"!
