### ISSUE TITLE
caves won't generate when vanilla filler block, stone usually, is replaced by another block

### ISSUE THREAD

**Issue by Nathan22211** [superckl/BiomeTweaker#259]
I've only noticed it in the plains since that's the only biome I've changed, but this will likely happen in any biome.

here's the script: https://gist.github.com/Nathan22211/4d4f9782d72606e2768318fb46dbe739 line 25 wasn't there originally but even with that it hasn't worked.

also, your discord link in the wiki is invalid.

**Comment by superckl** [comment]
This is a known issue, and can't be fixed without replacing the cave generator. The generator looks only for a specific set of blocks that it can replace:

```
Stone
Dirt
Grass
(Stained )Hardened Clay
(Red) Sandstone
Mycelium
Snow
```

I would rather avoid replacing the cave generator, but I can look into it.

**Comment by superckl** [comment]
BiomeTweaker for MC is now EOL, so I will not be addressing bugs that are related to BT - MC interactions. If this bug persists in BiomeTweaker for MC 1.18, please submit a new issue.
