### ISSUE TITLE
Water/Lava lake removal not working (BoP)

### ISSUE THREAD

**Issue by KannyChan** [superckl/BiomeTweaker#260]
Trying to run a script that will remove the water/lava lakes from _all_ biomes. I'm using 1.12.2 Minecraft Forge with Biomes o' Plenty installed, but I'm not directly referencing any BoP biomes, so I used forAllBiomes(), as below:

```
lakeRemover = forAllBiomes()

lakeRemover.removeDecoration("LAKE_WATER")
lakeRemover.removeDecoration("LAKE_LAVA")
lakeRemover.removeFeature("LAKE")
lakeRemover.removeFeature("LAVA")
lakeRemover.removeGeneratorBOP("LAVA")
lakeRemover.removeGeneratorBOP("LAKE")
```

I started with just the removeDecoration at first, then went all out with each line, individually dedicated to removing the lakes (just to be absolutely sure it wasn't an out-of-place comma or something). Log files show no errors with BiomeTweaker:

```
[17:53:28] [main/INFO] [biometweaker]: Beginning script parsing...
[17:53:28] [main/INFO] [biometweaker]: Finished script parsing.
```

No other lines from [biometweaker] in the log file reference a failure to run/read the script. Any time I test with a map -- default, BOP generation, superflat, etc. -- it still spawns in the lakes. The script is placed in the .minecraft/config/BiomeTweaker/scripts folder as 'removelakes.cfg'.

I'm not much of a coder -- I watched the tutorial video several times and sifted through the internet for about an hour with little to no luck.

**Comment by Dinerell** [comment]
You have to look into a biome file in the output folder (open it with Notepad++) that generates lakes like Mountain. There you find the generators at the end of the file with their names. The name of the BOP-Generator for lakes ist "lakes".

**Comment by superckl** [comment]
BiomeTweaker for MC is now EOL, so I will not be addressing bugs that are related to BT - MC interactions. If this bug persists in BiomeTweaker for MC 1.18, please submit a new issue.
