### ISSUE TITLE
[Question] Structure disabling

### ISSUE THREAD

**Issue by Gandalf360one** [superckl/BiomeTweaker#265]
Is it possible to disable the ocean monuments with Biome Tweaker and when then HOW ?

**Comment by superckl** [comment]
No, I can look into it though.

**Comment by superckl** [comment]
BiomeTweaker for MC is now EOL, so I will not be addressing bugs that are related to BT - MC interactions. If this bug persists in BiomeTweaker for MC 1.18, please submit a new issue.
