### ISSUE TITLE
BiomeTweaker keeps deleting script from script list 

### ISSUE THREAD

**Issue by AGiLE-EaGLE1994** [superckl/BiomeTweaker#266]
[test.txt](https://github.com/superckl/BiomeTweaker/files/5184157/test.txt)
[postgaianbiomes.txt](https://github.com/superckl/BiomeTweaker/files/5184158/postgaianbiomes.txt)
[BiomeTweaker.txt](https://github.com/superckl/BiomeTweaker/files/5184162/BiomeTweaker.txt)
[latest.log](https://github.com/superckl/BiomeTweaker/files/5184163/latest.log)

the latest.log says that the list property is malformed at line 14, even though I entered it exactly like that once before and it worked. I can't figure out how I made it work. 
Minecraft version: 1.12.2
BiomeTweaker version: 1.12.2 3.2.368
Forge version: 14.23.5.2838
I have Biomes 'O Plenty installed.

**Comment by superckl** [comment]
Is something preventing you from dropping these scripts in the scripts folder? It's much easier than figuring out where your syntax is wrong.

**Comment by AGiLE-EaGLE1994** [comment]
They ARE in the scripts folder. But I DID have copies of them in the BiomeTweaker folder too.
Also, THANK YOU in advance for helping me because I was really confused.
I've deleted the copies in the BT folder, so they're gone now.

**Comment by superckl** [comment]
You only need them in the scripts folder. They must end in ".cfg" as well.

**Comment by AGiLE-EaGLE1994** [comment]
Mine do. What I'm curious about is what's wrong with the main config file's script list.
Also, I thought that having `Tweaker.setStage("BIOME_REGISTRY")` in the script cfg multiple times would be a problem so I fixed that too. I've rebooted the game countless times and can't figure out what's wrong, and I'd really appreciate any help with this.

**Comment by superckl** [comment]
I'm not sure, I haven't touched Forge config files in a while. It's formatted however Forge wants you to format lists.

**Comment by AGiLE-EaGLE1994** [comment]
I'll go look up Forge list format.

**Comment by AGiLE-EaGLE1994** [comment]
I've seen other lists in Forge config files and the syntax seems to be like: 
< 
thing
thing1 
thing2
(greater than sign)
And that's very different from the example on the wiki.
EDIT: I laid out the list like that, with the greater/less than symbols on separate rows, with the scripts in between each on their own rows with no punctuation marks and it worked. Can you update the example in the wiki to match that?
