### ISSUE TITLE
i tried to change some dimension id's using this mod but, it didn't register. anything i can do?

### ISSUE THREAD

**Issue by PercyJames** [superckl/BiomeTweaker#267]
title says it all. i want to change a dimension id cause mcreator has no config files. but when i did and put another mod in i still got the same error of two dimensions sharing the same ID

**Comment by superckl** [comment]
Not sure how you tried that, because BT can't change dimension IDs. Not sure any mod can. That's something you'll have to ask the mod author to account for.
