### ISSUE TITLE
RE: i tried to change some dimension id's using this mod but, it didn't register. anything i can do?

### ISSUE THREAD

**Issue by PercyJames** [superckl/BiomeTweaker#268]
to add context i tried to change the dimension ids by going to .minecraft > config > BiomeTweaker > output > dimension

and then tried to change the dimension id from the files there. this mainly if not only for context. feel free to close the issue without answering.

**Comment by superckl** [comment]
Those are output files. They are not read in as config. BiomeTweaker cannot change dimension IDs.
