### ISSUE TITLE
[BUG] Realistic Terrain Generation, Advanced Rocketry scripts incompatibility

### ISSUE THREAD

**Issue by juraj-hrivnak** [superckl/BiomeTweaker#269]
## Version of Biome Tweaker
>BiomeTweaker-1.12.2 3.2.369
>BiomeTweakerCore-1.12.2 1.0.39

>This bug/crash happened to me when transporting to other dimensions using Advanced Rocketry rocket

**Probably Advanced Rocketry is reading Realistic Terrain Generation scripts
and resolving to crash. The crash happens every time any planet is generated**

## Version of Realistic Terrain Generation, Advanced Rocketry are the latest
>AdvancedRocketry-1.12.2-1.7.0-235-universal
>LibVulpes-1.12.2-0.4.2-75-universal
>RTG-1.12.2-6.1.0.0-snapshot.1

## Version of Minecraft
>1.12.2
>Forge - 14.23.5.2854

## Does this occur without other mods installed
> Only mods needed are AdvancedRocketry, Realistic Terrain Generation and Biome Tweaker

## Description of the problem
>The configuration for Biome Tweaker is intended for Realistic Terrain Generation mod, but AdvancedRocketry is taking these scripts for themselves.
Maybe this can't be fixed, but I rather make an Issue

## Additional files
> These are the Biome Tweaker scripts:
[scripts.zip](https://github.com/zmaster587/AdvancedRocketry/files/5458576/scripts.zip)

**Comment by miad2401** [comment]
@juraj-hrivnak Please tell me how you fixed this, I am having the same issue.

**Comment by juraj-hrivnak** [comment]
Hi @miad2401! I will reopen this issue till I properly explain the bug.

**Comment by juraj-hrivnak** [comment]
I just need some time to test it out again.

**Comment by juraj-hrivnak** [comment]
@miad2401 Sorry for the late reply.
### Explanation
- So when running `/biometweakerreload` you should check for errors in the **Latest.log**
If there are some **errors**, the Advanced Rocketry will crash of the above-explained conditions.

- Example of errors in BiomeTweaker: 
> [Server thread/INFO] [biometweaker]: Beginning script parsing...
> [18:23:21] [Server thread/ERROR] [SuperScript]: Failed to handle a script line! toMarble.set("block", "divergentunderground:quark_marble_cobblestone") @ ScriptContext(scriptName=cobblestone_layers.cfg, lineNumber=4). Reason: Object not found: toMarble
> [18:23:21] [Server thread/ERROR] [SuperScript]: Failed to execute script command: registerGenBlockRep @ ScriptContext(scriptName=cobblestone_layers.cfg, lineNumber=17). Reason: Cannot register block replacement with no block specified!
> [18:23:21] [Server thread/INFO] [biometweaker]: Finished script parsing.

- If there are no errors, the issue should be **fixed**.
