### ISSUE TITLE
Unable to obtain an output file for a biome defined by createBiome

### ISSUE THREAD

**Issue by MicahHaack** [superckl/BiomeTweaker#271]
I have recently been attempting to learn how to use BiomeTweaker, so apologies in advanced if I am missing something obvious.

I have been attempting to register a new biome type using the `createBiome()` function, with the following script sequence.

`Tweaker.setScriptStage("BIOME_REGISTRY")`
`Tweaker.createBiome("frost_forest", "advancedrocketry:moon")`
`frostForest = forBiomes("biometweaker:frost_forest")`

`frostForest.set("name", "Frost Forest")`

`Tweaker.setWorld(2)`
`# this is to select the moon as the world to apply future tweaks`
`# no other tweaks are currently being run, however`

I have run the commands to reload the specific script, and regenerate the output files, which can be verified below:
![image](https://user-images.githubusercontent.com/44842363/102839400-6d3d7400-43ce-11eb-80fe-727b8be8bcdb.png)

However, when I go to check the output files, I am unable to find the corresponding file for the frost forest.  Am I missing something important here?
I have also run this script without the
`Tweaker.setWorld(2)`
function in case this was causing issues. No luck.

**Comment by superckl** [comment]
The biome you are copying might be the issue. Try again without copying the Advanced Rocketry biome. Otherwise check your log file for any errors.

**Comment by MicahHaack** [comment]
Ah, I was unaware errors were placed in the log file.  I found this output line:
`[21:02:34] [Server thread/ERROR]: Failed to execute script command: createBiome @ ScriptContext(scriptName=moonBiomes.cfg, lineNumber=2). Reason: No biome registry avilable! Make sure you're using the biome registry script stage!`

Which seems slightly strange considering I have set the stage to BIOME_REGISTRY prior to running the createBiome function.

For reference I am running MC 1.12 with v3.2.369 of BiomeTweaker and v1.0.39 of BiomeTweakerCore.

**Comment by superckl** [comment]
Because you are reloading the script. Staging is not applied when you reload because all the stages have already happened. If you are doing something that requires staging, you must restart your game to properly apply tweaks.

**Comment by MicahHaack** [comment]
I see.  I searched for the earlier instance of the error on startup, and found this error:
`[20:59:14] [Client thread/ERROR]: Failed to execute script command: createBiome @ ScriptContext(scriptName=moonBiomes.cfg, lineNumber=2). Reason: It appears the biome advancedrocketry:moon is setting its registry name during construction. This biome cannot be copied! Contact the mod author.`

It seems I was missing something obvious.  Thank you.  Now to see if I can manually copy the biome over.
