### ISSUE TITLE
set skycolor not taking effect but fogcolor does

### ISSUE THREAD

**Issue by farnoods** [superckl/BiomeTweaker#272]
I'm trying to set the sky color, and I've followed the steps in the wiki to the dot, but for whatever reason, it's not taking effect. I was able to change the fog color using the 'set' function but its not working for the sky. I have BiomeTweaker Core as well and I've enabled the skycolor and fogcolor options in the configs.
`
myBiomes = forBiomes("nuclearcraft:nuclear_wasteland")
`
`
myBiomes.set("skyColor", 13868622)
`
`
myBiomes.set("fogColor", 13868622)
`

**Comment by superckl** [comment]
BiomeTweaker for MC is now EOL, so I will not be addressing bugs that are related to BT - MC interactions. If this bug persists in BiomeTweaker for MC 1.18, please submit a new issue.
