### ISSUE TITLE
Main config not working

### ISSUE THREAD

**Issue by Rsambeek** [superckl/BiomeTweaker#273]
When I try to create a new script in the main config it throws an error and turns the main config into BiomeTweaker.cfg_$DATE_$TIME.errored

**Comment by superckl** [comment]
You do not place scripts in the main config. They are placed in their own file in scripts folder.

**Comment by Rsambeek** [comment]
yes, I get how that works but if I add it the way the wiki says I should it throws an error

**Comment by superckl** [comment]
Are you sure you are using proper formatting? The main config uses Forge's config formatting. You can look at packs such as Project Ozone 3 that do this as examples as well.
