### ISSUE TITLE
Scripts not loading into game at all, including example script. No errors in logs.

### ISSUE THREAD

**Issue by zediious** [superckl/BiomeTweaker#274]
MC: 1.7.10
Forge: 10.13.4.1558
BiomeTweaker: 1.2.128

I am having an issue having the scripts load at all. I inititally tested on a modpack I am making, but am now testing with no mods enabled besides BiomeTweaker. I've entered "ExampleTweaks.cfg" into the "include" brackets at the bottom.

 It is supposed to turn that biome into a netherrack top with ghasts, etc, no dice. Any indication about why this may be happening? Am I doing something wrong? I found no answers on the wiki. 

biometweaker.cfg: https://pastebin.com/X1RPmYsm
ExampleTweaks.cfg: https://pastebin.com/buTw3ftB (biome changed to ice plains)
latest log: https://pastebin.com/rw0AJNWh

biometweaker config folder: https://imgur.com/a/Le9rHOw

**Comment by superckl** [comment]
Support for 1.7.10 was dropped a long time ago, especially for such an old version of the mod. I have no clue what state the mod was in at the time since it has changed a lot.

**Comment by zediious** [comment]
I imagine, figured I would shoot my shot here with this. Thank you for the swift reply!
