### ISSUE TITLE
Minor Ore Generation Problem

### ISSUE THREAD

**Issue by Drathonix** [superckl/BiomeTweaker#276]
The ore decorations I am generating have been given a block to replace that isn't stone, however despite this, the ores still replace stone. They also replace the desired block, but the desired is not stone.

Below is an example of the issue. On the left is the ore generating in vanilla stone as unintended. On the right is the ore generating in the custom block as intended.
![Ores in stone](https://user-images.githubusercontent.com/52723768/109367800-17b99380-7865-11eb-8d51-42864fa126dc.jpg)

**Comment by juraj-hrivnak** [comment]
@Drathonix Your script?

**Comment by Drathonix** [comment]
`Tweaker.setPlacementStage("POST_ORES")
thorium = newOreDecoration()
thorium.set("mainblock", "contenttweaker:dsthoriumore")
thorium.addBlockToReplace("contenttweaker:deathstone")
thorium.set("count", 24)
thorium.set("size", 8)
thorium.set("minY", 0)
thorium.set("maxY", 48)
uranium = newOreDecoration()
uranium.addBlockToReplace("contenttweaker:deathstone")
uranium.set("mainblock", "contenttweaker:dsuraniumore")
uranium.set("count", 20)
uranium.set("size", 7)
uranium.set("minY", 0)
uranium.set("maxY", 40)
neptunium = newOreDecoration()
neptunium.addBlockToReplace("contenttweaker:deathstone")
neptunium.set("mainblock", "contenttweaker:dsneptuniumore")
neptunium.set("count", 16)
neptunium.set("size", 5)
neptunium.set("minY", 0)
neptunium.set("maxY", 32)
plutonium = newOreDecoration()
plutonium.addBlockToReplace("contenttweaker:deathstone")
plutonium.set("mainblock", "contenttweaker:dsplutoniumore")
plutonium.set("count", 12)
plutonium.set("size", 4)
plutonium.set("minY", 0)
plutonium.set("maxY", 24)
americium = newOreDecoration()
americium.addBlockToReplace("contenttweaker:deathstone")
americium.set("mainblock", "contenttweaker:dsamericiumore")
americium.set("count", 8)
americium.set("size", 3)
americium.set("minY", 0)
americium.set("maxY", 16)
//Addition
radioactiveBog.addDecoration(thorium)
radioactiveBog.addDecoration(uranium)
radioactiveBog.addDecoration(neptunium)
radioactiveBog.addDecoration(plutonium)
radioactiveBog.addDecoration(americium)`

**Comment by Drathonix** [comment]
https://pastebin.com/RNZuu7GD

**Comment by juraj-hrivnak** [comment]
Hmm, did you disabled the ores from generation entirely before generating them with BiomeTweker?

Also, for generating ores it's probably better to use OSV or COFH World mod.
https://www.curseforge.com/minecraft/mc-mods/ore-stone-variants

**Comment by Drathonix** [comment]
I created the ore blocks with content tweaker, I put them into world gen only with biometweaker. And yeah, you're probably right to be fair.

**Comment by superckl** [comment]
BiomeTweaker for MC is now EOL, so I will not be addressing bugs that are related to BT - MC interactions. If this bug persists in BiomeTweaker for MC 1.18, please submit a new issue.
