### ISSUE TITLE
genInitialSnow/enableSnow false does not disable snow on elevations

### ISSUE THREAD

**Issue by honkfriend** [superckl/BiomeTweaker#279]
extremehills.set("genInitialSnow", false)
extremehills.set("enableSnow", false)

i would like to disable snow on altitudes. it still generates on the peaks of extreme hills with this command. for now i will simply change the temperature and grass color.

**Comment by honkfriend** [comment]
problem has been resolved. genInitialSnow needs to be enabled in biometweakercore and the wiki states nothing of it.

**Comment by superckl** [comment]
Thanks, I've clarified this on the wiki.
