### ISSUE TITLE
"removeDecoration("LAKE")" not working properly

### ISSUE THREAD

**Issue by KrakenLord** [superckl/BiomeTweaker#28]
Here is the script used and the world generated:
Void = forBiomes(125)
all = forAllBiomes()
Void.create("DESERT", 20000)
Void.addToGeneration("WARM", 20000)
Void.addToGeneration("COOL", 20000)
Void.addToGeneration("ICY", 20000)
all.set("color", 16421912)
all.set("name", "Void")
all.set("enableRain", false)
all.set("temperature" 0.0)
all.set("humidity", 0.0)
all.set("height", 0.125)
all.set("heightVariation", 0.05)
all.removeAllSpawns("CREATURE")
all.removeAllSpawns("MONSTER")
all.removeAllSpawns("CAVE_CREATURE")
all.removeAllSpawns("WATER_CREATURE")
all.set("topBlock", "minecraft:obsidian")
all.set("fillerBlock", "minecraft:obsidian")
Void.removeDecoration("LAKE")
Tweaker.setStage("PRE_INIT")
Tweaker.setStage("FINISHED_LOAD")

all.set("genWeight", 30)

all.set("isSpawnBiome", false)

Void.set("isSpawnBiome", true)
Void.set("genWeight", 20000)

all.registerGenBlockRep("minecraft:water", "minecraft:air")
all.registerGenBlockRep("minecraft:stone", "minecraft:obsidian", 0)
![2015-06-09_14 43 40](https://cloud.githubusercontent.com/assets/12818673/8066544/34a1b56e-0eb6-11e5-8554-260129da2653.png)
As you can see, the world generates fine, except for the fact that there are still lakes.

**Comment by superckl** [comment]
You are only removing lake generation in the Void biome, not in all biomes. However, you are setting everything to obsidian. Those lakes are appearing in other biomes.

**Comment by KrakenLord** [comment]
I changed the command to affect "all", but I still get lakes and lava lakes.

**Comment by superckl** [comment]
Hmm, not really sure on this one. Some testing reveals that the LAKE generation is being cancelled, but it appears lakes are still generating. Looking into it.

**Comment by superckl** [comment]
It turns out that Minecraft actually generates lakes in two separate places. Once as a decoration and once as a feature. I have now added a [new command](https://github.com/superckl/BiomeTweaker/wiki/Basic-Script-Commands#removefeature) that you can use with the [latest build](http://jenkins.superckl.me/job/BiomeTweaker/118/).

You'll want to add the following to your script:

    all.removeFeature("LAKE")

Removing lake generation in both places should stop their generation.

**Comment by KrakenLord** [comment]
Works perfectly! Thank you!
