### ISSUE TITLE
[Feature request] Bring back the BTSetBiome command

### ISSUE THREAD

**Issue by jamesjimmy88** [superckl/BiomeTweaker#284]
Would it be possible to port the in-game BTSetBiome command to 1.18.2? It would be quite useful for mapmaking and in conjunction with other mods like CrT that allow you to run commands under certain conditions. It would obviously require the biome's ID instead of its numeric ID.
A ton of stuff changed between versions and I have no idea if it's even possible to implement it, but I guess it doesn't hurt to ask.

**Comment by superckl** [comment]
Unfortunately not. Biomes are noise based in the default world and thus are not actually stored anywhere. Every time a biome is needed, the noise value is computed and the biome retrieved. What you want would require a custom noise source. I'm not opposed to discussing this, but this request is not possible as phrased.

**Comment by jamesjimmy88** [comment]
I thought something like this would be the case, thanks for confirming it.
This also means that there's no way to precisely define areas with a different biome in a single-biome world; I guess I could use CraftTweaker to prevent spawns in those areas.
Thank you for the info.
