### ISSUE TITLE
removeBOP() only works intermittently [1.12.2]

### ISSUE THREAD

**Issue by Desymoo** [superckl/BiomeTweaker#286]
Hello! I'm not sure how much support you're still planning on providing for the 1.12 version but I'll drop this in here just in case :)

I seem to be having an issue almost identical to #206, the only difference being that I'm using [Traverse](https://www.curseforge.com/minecraft/mc-mods/traverse-reforged/files/all?filter-game-version=2020709689%3A6756) and [Environs](https://www.curseforge.com/minecraft/mc-mods/environs/files) along with BoP (the latest 1.12 builds on both).

My script looks very similar and I check my log files every time I start my instance to make sure no BT errors are popping up, but for some strange reason the removeBOP() function only seems to work intermittently on biomes from both mods. In other words, my output files look exactly the same as this:
```
"BOP Climate Weights": {
    "WARM_TEMPERATE": [
      5
    ]
  },
```
VS
```
"BOP Climate Weights": {
    "WET_TEMPERATE": [
      2
    ],
    "DRY_TEMPERATE": [
      2
    ],
    "WARM_TEMPERATE": [
      2,
      5
    ],
    "HOT_SWAMP": [
      2
    ],
    "MEDITERANEAN": [
      2
    ]
  },
```
There doesn't seem to be any consistent pattern on when the scripts will work and when they won't so it's been difficult to test. The only thing I can say for certain is that it seems to happen any time I edit a BT script (it doesn't even have to be the one that references removeBOP()) or add/remove a mod containing biomes. It usually takes a few reloads after that for the climate weights to fix themselves.

Any advice or a workaround would be very appreciated :) I'd like to use these scripts in a modpack but I'm concerned that they will break people's worlds any time I try to push updates.

**Comment by superckl** [comment]
Unfortunately I'm not updating 1.12 anymore, but I'm happy to help try to find a work around. Are you able to join the discord linked on the homepage of the wiki?
