### ISSUE TITLE
Water is not removed

### ISSUE THREAD

**Issue by shady2k** [superckl/BiomeTweaker#29]
How can I completely remove any water from world?

![image](https://cloud.githubusercontent.com/assets/3366415/8485160/567fc03a-2104-11e5-8e8d-c9acc78b6852.png)

Config:
Void = forBiomes(125)
all = forAllBiomes()
Void.create("DESERT", 20000)
Void.addToGeneration("WARM", 20000)
Void.addToGeneration("COOL", 20000)
Void.addToGeneration("ICY", 20000)
all.set("color", 16421912)
all.set("name", "Void")
all.set("enableRain", false)
all.set("temperature" 0.0)
all.set("humidity", 0.0)
all.set("height", 0.125)
all.set("heightVariation", 0.05)
all.removeAllSpawns("CREATURE")
all.removeAllSpawns("MONSTER")
all.removeAllSpawns("CAVE_CREATURE")
all.removeAllSpawns("WATER_CREATURE")
all.removeFeature("LAKE")
all.removeDecoration("LAKE")
all.set("topBlock", "minecraft:obsidian")
all.set("fillerBlock", "minecraft:obsidian")
all.set("liquidFillerBlock", "minecraft:obsidian")
Void.removeDecoration("LAKE")
Tweaker.setStage("PRE_INIT")
Tweaker.setStage("FINISHED_LOAD")

all.set("genWeight", 30)
all.set("isSpawnBiome", false)

Void.set("isSpawnBiome", true)
Void.set("genWeight", 20000)

all.registerGenBlockRep("minecraft:water", "minecraft:air")
all.registerGenBlockRep("minecraft:stone", "minecraft:obsidian", 0)

**Comment by superckl** [comment]
How often are those pockets appearing?

**Comment by shady2k** [comment]
Quite often. It's difficult to describe how often them spawn, maybe 1-2 per 10 chunks. This pockets contains water from bedrock to surface.

**Comment by superckl** [comment]
Could you try not setting the name of all biomes to "Void", and tell me the name of the biome(s) those pockets are appearing in? I have a guess they will all be some form of ocean.

I'd test this myself normally,but I'm out until Monday.

**Comment by shady2k** [comment]
I'm very sorry, this is BuildCraft Water Spring black caused this.
