### ISSUE TITLE
Cannot seem to remove a biome nor replace it in 1.19.2

### ISSUE THREAD

**Issue by zachsai** [superckl/BiomeTweaker#291]
I tried
toxic_jungle = forBiomes(dreamland:toxic_jungle)
jungle = forBiomes(minecraft:jungle)

toxic_jungle.registerGenBiomeRep(jungle)

also tried 

toxic_jungle = forBiomes("dreamland:toxic_jungle")
toxic_jungle.remove()

both did not work.
I am knew to this mod and tried to follow the wiki as best as I could.

furthermore, this is my file structure
![image](https://user-images.githubusercontent.com/63996164/209465105-a9a29d50-481f-4132-bedc-0e3bb42ab142.png)

**Comment by superckl** [comment]
These commands do not exist in 1.18+. You must accomplish this through a datapack.

**Comment by zachsai** [comment]
Is there any info on the wiki on how to do it with datapack structure?
Or do you have a dummy file with  vanilla examples that can be used in reference?
