### ISSUE TITLE
addSpawn doesn't work

### ISSUE THREAD

**Issue by ghost** [superckl/BiomeTweaker#306]
I created a script in the file`NetherSpawnrate.script`:

```
netherBiomes = forBiomes("minecraft:hell")

netherBiomes.addSpawn("minecraft:wither_skeleton", "MONSTER", 1100, 3, 50)
netherBiomes.addSpawn("minecraft:ghast", "MONSTER", 6666, 8, 120)
```
The `BiomeTweaker.cfg` file looks like this:

```
# Configuration file

"output files" {
    # If true, BiomeTweaker will not generate any output files. [default: false]
    B:"Disable Output Files"=false

    # If true, BiomeTweaker will generate separate files for each item when creating the status report. [default: true]
    B:"Output Seperate Files"=true
}


scripting {
    # A list of script files to include that are not in the scripts folder. An example script file is created along with this configuration file. [default: ]
    S:"Script Files" <
        "WorldSpawnBlackList.script", "DisableClovers.script", "NetherSpawnrate.script"
     >
}


```

I expect to see a significantly increased number of ghasts and wither skeletons in the Nether dimension. But wither skeletons appear only in fortresses, and I never saw ghasts.
I also have the BetterNether mod installed.

**Comment by Dinerell** [comment]
Normal spawn rules still apply, if you want to spawn Wither Skeletons or Ghasts elsewhere you need a mod which implements its own set of spawning rules bypassing the normal spawning rules (like InControl).
