### ISSUE TITLE
[1.12] Biome Tweaker is probably just f*cking with me

### ISSUE THREAD

**Issue by RohnekKdosi** [superckl/BiomeTweaker#309]
On a script that goes as follows:

1. `Tweaker.setStage("BIOME_REGISTRY")
2. Tweaker.createBiome("io", "advancedrocketry:moon")
3. io = forBiomes("biometweaker:io")
4. io.set("name", "Io")
5. io.set("topBlock", "contenttweaker:sulfur_rich_turf")
6. io.set("fillerBlock", "contenttweaker:sulfur_rich_turf")
7. Tweaker.createBiome("europa", "minecraft:frozen_ocean")
8. europa = forBiomes("biometweaker:europa")
9. europa.set("name", "Europa")
10. europa.set("topBlock", "minecraft:stone")
11. europa.set("fillerBlock", "minecraft:stone")
12. europa.set("oceanTopBlock", "minecraft:stone")
13. europa.set("oceanFillerBlock", "minecraft:stone")
14. blockRep = newBlockReplacement()
15. ice = forBlock("minecraft:packed_ice")
16. blockRep.set("block", ice)
17. blockRep.set("minY", 120)
18. europa.registerGenBlockRep("minecraft:water", blockRep)
19. Tweaker.createBiome("mercury", "minecraft:plains")
20. mercury = forBiomes("biometweaker:mercury")
21. mercury.set("name", "Mercury")
22. mercury.set("topBlock", "contenttweaker:mercury_rock")
23. mercury.set("fillerBlock", "contenttweaker:mercury_rock")
24. mercury.set("oceanTopBlock", "contenttweaker:mercury_rock")
25. mercury.set("oceanFillerBlock", "contenttweaker:mercury_rock")
26. Tweaker.createBiome("venus", "minecraft:plains")
27. venus = forBiomes("biometweaker:venus")
28. venus.set("name", "Venus")
29. venus.set("topBlock", "contenttweaker:sulfur_rich_turf")
30. venus.set("fillerBlock", "contenttweaker:sulfur_rich_turf")
31. venus.registerGenBlockRep("minecraft:water", "minecraft:lava")
32. Tweaker.createBiome("phobos", "advancedrocketry:moon")
33. phobos = forBiomes("biometweaker:phobos")
34. phobos.set("name", "Phobos")
35. phobos.set("topBlock", "contenttweaker:phobos_regolith")
36. phobos.set("fillerBlock", "contenttweaker:phobos_regolith")
37. phobos.set("fillerBlock", "contenttweaker:phobos_regolith")
38. biomes = forAllBiomes()
39. biomes.set("enableRain", false)
40. biomes.set("genInitialSnow",false)
41. biomes.removeAllSpawns("CREATURE")
42. biomes.removeAllSpawns("MONSTER")
43. biomes.removeAllSpawns("AMBIENT")
44. biomes.removeAllSpawns("WATER_CREATURE")
45. biomes.removeDecoration("GRASS")
46. biomes.removeDecoration("PUMPKIN")
47. biomes.removeDecoration("REED")
48. biomes.removeDecoration("CACTUS")
49. biomes.removeDecoration("DEAD_BUSH")
50. biomes.removeDecoration("BIG_SHROOM")
51. biomes.removeDecoration("LILYPAD")
52. biomes.removeDecoration("FLOWERS")
53. biomes.removeDecoration("SHROOM")
54. biomes.removeDecoration("LAKE_WATER")
55. plainsBiomes = forBiomesOfTypes("FOREST","MOUNTAIN","JUNGLE","MUSHROOM","OCEAN","WATER","PLAINS","SAVANNA","WET")
56. plainsBiomes.set("topBlock", "minecraft:dirt")
57. Tweaker.set("minecraft:ice_flats", "topBlock", "minecraft:dirt")
58. Tweaker.set("minecraft:extreme_hills", "topBlock", "minecraft:dirt")
59. biomes = subtractFrom(biomes, io)
60. biomes = subtractFrom(biomes, europa)
61. biomes = subtractFrom(biomes, mercury)
62. biomes = subtractFrom(biomes, venus)
63. biomes = subtractFrom(biomes, phobos)
64. biomes.registerGenBlockRep("minecraft:water", "minecraft:air")
65. Tweaker.setPlacementStage("POST_POPULATE")
66. biomes.registerGenBlockRep("minecraft:water", "minecraft:air")
67. biomes.registerGenBlockRep("minecraft:waterlily", "minecraft:air")
68. biomes.registerGenBlockRep("minecraft:leaves", "minecraft:air")
69. biomes.registerGenBlockRep("minecraft:leaves2", "minecraft:air")
70. mercury.removeDecoration("TREE")
71. venus.removeDecoration("TREE")
72. phobos.removeDecoration("TREE")
73. mercury.registerGenBlockRep("minecraft:dirt", "contenttweaker:mercury_rock")
74. venus.registerGenBlockRep("minecraft:dirt", "contenttweaker:sulfur_rich_turf")
75. phobos.registerGenBlockRep("minecraft:dirt", "contenttweaker:phobos_regolith")`
The Venus biome has the top block set as Phobos Regolith. I should probably note that these custom biomes are used in conjunction with Advanced Rocketry, WGBlock Replacer (to fix whatever this mod refuses to do, because f*ck me, I guess) and Content Tweaker.

Anyway, I'm off to get some rest, because I spent way too long trying to FITFO. I managed to isolate the problem to the line
`phobos.registerGenBlockRep("minecraft:dirt", "contenttweaker:phobos_regolith")` without which the top block is just dirt.
Why does it do it? No f*cking idea. I hope I gave all the information needed.

**Comment by superckl** [comment]
Can you join the discord listed on the wiki? I think we can work through the cause of this more easily there. This doesn't seem like a "bug" with BiomeTweaker.
