### ISSUE TITLE
an issue with an unknown mod causing biometweeker to crash

### ISSUE THREAD

**Issue by meelock** [superckl/BiomeTweaker#34]
the issue happens when i generate a world and the error in general is that its attempting to divide by 0
the error log is here: http://pastebin.com/GfGkKtUa

please help me.
Meelock

**Comment by superckl** [comment]
Can I see the script you're running? If you're removing all biomes from generation, it's going to crash.

**Comment by meelock** [comment]
not all but a lot like taigas and all the boring biomes. heres the script:
DumbBiomes = forBiomes(156, 28, 155, 27, 26, 31, 158, 30, 194, 20, 131, 3, 162, 34, 132, 4, 18, 10, 11, 13, 140, 12, 193, 160, 33, 32, 1, 157, 29, 163, 164, 36, 35, 25, 129, 134, 6, 133, 5, 19, 192)
DumbBiomes.remove()

**Comment by superckl** [comment]
I should say "all biomes of a certain type". Do you have a full log I can see. If you are removing all biomes of a type, BiomeTweaker will let you know in the log.

**Comment by meelock** [comment]
here it is: https://www.dropbox.com/s/19zmmai1xp6bo0i/fml-client-latest.log?dl=0
sorry for the dropbox, it was to big to put in pastebin

**Comment by meelock** [comment]
wow k found it 


[BiomeTweaker/BiomeTweaker]: Viable generation biomes for type ICY is empty! This will cause Vanilla generation to crash! You've been warned!
[18:47:08] [Client thread/WARN] [BiomeTweaker/BiomeTweaker]: Viable generation biomes for type WARM is empty! This will cause Vanilla generation to crash! You've been warned!
[18:47:08] [Client thread/WARN] [BiomeTweaker/BiomeTweaker]: Viable generation biomes for type COOL is empty! This will cause Vanilla generation to crash! You've been warned!

**Comment by meelock** [comment]
uggg, i just want a jungle planet!!

**Comment by superckl** [comment]
You still can! There's a simple way around this. This script creates a desert world. It adds desert to all the generation types so everything else can be removed.

https://github.com/superckl/BiomeTweaker/wiki/Example-Scripts#creating-a-desert-world

**Comment by meelock** [comment]
so i could just add jungles, and every thing else that it want: to all the heats?

**Comment by superckl** [comment]
Yep. Keep in mind that some biomes are hard-coded. There is an issue about that:

https://github.com/superckl/BiomeTweaker/issues/32

**Comment by meelock** [comment]
ok testing it now!

**Comment by meelock** [comment]
nope still crashes: heres the new code:
```
coolbiomes = forBiomes(16, 7, 0)
coolbiomes.addToGeneration("ICY", 2000)
coolbiomes.addToGeneration("COOL", 2000)
jungles = forbiomes(21)
jungles.addToGeneration("WARM", 2000)
```
plus all the previus stuff

**Comment by meelock** [comment]
same crash

**Comment by meelock** [comment]
oh wait sorry ill add the stuff from the previous guys crash

**Comment by meelock** [comment]
k added jungles.registerGenBiomeRep(5)

**Comment by meelock** [comment]
nope still crashes
let me remove galacticraft.

**Comment by meelock** [comment]
this might mean something 

[20:35:20] [Server thread/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1862]: Galacticraft successfully injected bytecode into: ms (1 / 1)
[20:35:21] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception preparing structure feature

**Comment by nanakisan** [comment]
I don't think BiomeTweaker can alter another mods generation. The mod itself would have to support it. Believe me I would know right well. ATG only affects the overworld. What you want is affecting another dimension solely controlled by another mod.

**Comment by superckl** [comment]
If you're editing the moon, nothing will work, but I don't think that is the case here. I'll wrote a script soon that does what you want. I've been a bit busy lately.

**Comment by meelock** [comment]
thanks!

if you want i can give you the Biometweeker folder?

**Comment by superckl** [comment]
Sorry this took so long. I keep forgetting to do this. Here is the script I wrote to create a jungle planet:

```
#Remove all biomes from the BiomeManager so they don't appear in generation. BiomeTweaker will complain about this,
#but we are adding more later so it's fine.
allBiomes = forAllBiomes()
allBiomes.remove()

#Add jungle to the BiomeManager for all types so we don't crash.
jungle = forBiomes(21)
jungle.addToGeneration("WARM", 20000)
jungle.addToGeneration("COOL", 20000)
jungle.addToGeneration("DESERT", 20000)
jungle.addToGeneration("ICY", 20000)

#Replace any leftover hard-coded biomes with jungle.
allButJungle = subtractFrom(allBiomes, jungle)
allButJungle.set("height", 0.1)
allButJungle.set("heightVariation", 0.2)
allButJungle.registerGenBiomeRep(21)
```

![2015-08-18_01 04 17](https://cloud.githubusercontent.com/assets/2230216/9325162/40f856a4-4545-11e5-87c3-78e2bd3d7486.png)
