### ISSUE TITLE
[1.2.128]"CAVE_CREATURE" spawn type overly trigger happy.

### ISSUE THREAD

**Issue by thephoenixlodge** [superckl/BiomeTweaker#35]
it may be specifically an interaction with Grimoire of Gaia, but using cave creature mob spawn type results in ridiculously high spawn rates, up to about 500 of that type of mob, with it filling back up to that point in less than a minute if culled using commands or peaceful mode.
http://imgur.com/a/hwzNb
This is the config file:
forest = forBiomesOfTypes("FOREST")
cold = forBiomesOfTypes("COLD")
coniferous1 = forBiomesOfTypes("CONIFEROUS")
beach1 = forBiomesOfTypes("BEACH")

all = forAllBiomes()
nether = forBiomes(8)
end = forBiomes(9)
twilightForest = forBiomes(98-116)
erebus = forBiomes(72-79, 200-207)
mushroomIsle = forBiomes(14, 15)
taint = forBiomes(96)
outerLands = forBiomes(94)
overworld = subtractFrom(all, nether, end, erebus, mushroomIsle, taint, outerLands)

ocean = forBiomesOfTypes("OCEAN")
beach = subtractFrom(beach1, mushroomIsle)
river = forBiomesOfTypes("RIVER")
plains = forBiomesOfTypes("PLAINS")
desert = forBiomesOfTypes("SANDY", "MESA")
mountain = forBiomesOfTypes("MOUNTAIN")
temperateForest = subtractFrom(forest, cold, coniferous1)
coniferous = forBiomes(coniferous1, 158, 160, 161)
swamp = forBiomesOfTypes("SWAMP")
snowy = forBiomesOfTypes("SNOWY")
jungle = forBiomesOfTypes("JUNGLE")
wasteland = forBiomesOfTypes("WASTELAND")
magical = forBiomesOfTypes("MAGICAL")
nonTaintedMagical = subtractFrom(magical, taint)
spooky = forBiomesOfType("SPOOKY")

overworld.removeAllSpawns("CREATURE")
overworld.removeAllSpawns("MONSTER")
overworld.removeAllSpawns("WATER_CREATURE")
overworld.removeAllSpawns("CAVE_CREATURE")

overworld.addSpawn("net.minecraft.entity.monster.EntityZombie", "MONSTER", 20, 1, 6)
overworld.addSpawn("thaumcraft.common.entities.monster.EntityBrainyZombie", "MONSTER", 8, 1, 3)
overworld.addSpawn("net.minecraft.entity.monster.EntitySkeleton", "MONSTER", 20, 1, 4)
overworld.addSpawn("mekanism.common.entity.EntityBabySkeleton", "MONSTER", 6, 1, 2)
overworld.addSpawn("net.minecraft.entity.monster.EntityCreeper", "MONSTER", 15, 1, 3)
overworld.addSpawn("net.minecraft.entity.monster.EntitySpider", "MONSTER", 15, 2, 4)
overworld.addSpawn("net.minecraft.entity.monster.EntityEnderman", "MONSTER", 8, 1, 3)
overworld.addSpawn("net.mcft.copy.betterstorage.entity.EntityFrienderman", "MONSTER", 1, 1, 1)
overworld.addSpawn("net.minecraft.entity.monster.EntityWitch", "MONSTER", 6, 1, 2)
overworld.addSpawn("clickme.animals.entity.ambient.EntityMoth", "MONSTER", 8, 2, 5)
overworld.addSpawn("clickme.animals.entity.water.EntityFish", "WATER_CREATURE", 15, 3, 8)
overworld.addSpawn("net.minecraft.entity.monster.EntitySlime", "CAVE_CREATURE", 6, 1, 3)
overworld.addSpawn("net.minecraft.entity.monster.EntityBat", "CAVE_CREATURE", 12, 1, 3)
overworld.addSpawn("gaia.entity.EntityGaiaMimic", "CAVE_CREATURE", 5, 1, 1)
overworld.addSpawn("gaia.entity.EntityGaiaFleshLich", "CAVE_CREATURE", 3, 1, 3)
overworld.addSpawn("gaia.entity.EntityGaiaEnderEye", "CAVE_CREATURE", 5, 1, 2)
overworld.addSpawn("gaia.entity.EntityGaiaCreep", "CAVE_CREATURE", 5, 1, 3)
overworld.addSpawn("gaia.entity.EntityGaiaJorogumo", "CAVE_CREATURE", 5, 1, 2)
overworld.addSpawn("gaia.entity.EntityGaiaBoneKnight", 'CAVE_CREATURE", 3, 1, 3)

plains.addSpawn("gaia.entity.EntityGaiaMinotaurus", "MONSTER", 3, 1, 3)
plains.addSpawn("gaia.entity.EntityGaiaMinotaur", "MONSTER", 1, 1, 1)
plains.addSpawn("net.minecraft.entity.passive.EntityCow", "CREATURE", 16, 2, 5)
plains.addSpawn("net.minecraft.entity.passive.EntityPig", "CREATURE", 8, 2, 5)
plains.addSpawn("net.minecraft.entity.passive.EntitySheep", "CREATURE", 12, 2, 5)
plains.addSpawn("net.minecraft.entity.passive.EntityChicken", "CREATURE", 12, 2, 5)
plains.addSpawn("net.minecraft.entity.passive.EntityHorse", "CREATURE", 15, 2, 5)
plains.addSpawn("com.emoniph.witchery.entity.EntityGoblin", "CREATURE", 8, 1, 3)
plains.addSpawn("clickme.animals.entity.passive.EntityMouse", "CREATURE", 16, 1, 5)
plains.addSpawn("clickme.animals.entity.passive.EntityLizard", "CREATURE", 12, 1, 3)
plains.addSpawn("clickme.animals.entity.ambient.EntityButterfly", "CREATURE", 10, 1, 3)
plains.addSpawn("clickme.animals.entity.passive.EntitySnake", "CREATURE", 6, 1, 2)
plains.addSpawn("clickme.animals.entity.ambient.EntityCricket", "CREATURE", 10, 1, 3)
plains.addSpawn("gaia.entity.EntityGaiaSatyr", "CREATURE", 5, 2, 5)
plains.addSpawn("gaia.entity.EntityGaiaCentaur", "CREATURE", 5, 2, 5)
plains.addSpawn("gaia.entity.EntityGaiaHunter", "CREATURE", 8, 1, 3)

temperateForest.addSpawn("net.minecraft.entity.passive.EntityCow", "CREATURE", 8, 2, 5)
temperateForest.addSpawn("net.minecraft.entity.passive.EntityPig", "CREATURE", 16, 2, 5)
temperateForest.addSpawn("net.minecraft.entity.passive.EntitySheep", "CREATURE", 12, 2, 5)
temperateForest.addSpawn("net.minecraft.entity.passive.EntityChicken", "CREATURE", 10, 2, 5)
temperateForest.addSpawn("com.emoniph.witchery.entity.EntityOwl", "CREATURE", 3, 1, 2)
temperateForest.addSpawn("clickme.animals.entity.passive.EntityBird", "CREATURE", 16, 2, 4)
temperateForest.addSpawn("clickme.animals.entity.ambient.EntityCentipede", "CREATURE", 12, 1, 6)
temperateForest.addSpawn("clickme.animals.entity.passive.EntityMouse", "CREATURE", 16, 1, 5)
temperateForest.addSpawn("clickme.animals.entity.ambient.EntityButterfly", "CREATURE", 10, 1, 3)
temperateForest.addSpawn("clickme.animals.entity.ambient.EntityCricket", "CREATURE", 10, 1, 3)
temperateForest.addSpawn("gaia.entity.EntityGaiaPropFlowerCyan", "CREATURE", 5, 2, 5)

forest.addSpawn("gaia.entity.EntityGaiaWerecat", "MONSTER", 5, 1, 3)
forest.addSpawn("gaia.entity.EntityGaiaSpriggan", "MONSTER", 3, 1, 2)
forest.addSpawn("net.minecraft.entity.passive.EntityWolf", "CREATURE", 12, 1, 4)
forest.addSpawn("gaia.entity.EntityGaiaHunter", "CREATURE", 8, 1, 3)
forest.addSpawn("gaia.entity.EntityGaiaDryad", "CREATURE", 8, 1, 3)

coniferous.addSpawn("gaia.entity.EntityGaiaNineTails", "MONSTER", 3, 1, 2)
coniferous.addSpawn("gaia.entity.EntityGaiaFutakuchiOnna", "MONSTER", 5, 1, 3)
coniferous.addSpawn("gaia.entity.EntityGaiaCyclops", "CREATURE", 1, 1, 3)
coniferous.addSpawn("net.minecraft.entity.passive.EntityCow", "CREATURE", 12, 2, 5)
coniferous.addSpawn("net.minecraft.entity.passive.EntityPig", "CREATURE", 12, 2, 5)
coniferous.addSpawn("net.minecraft.entity.passive.EntitySheep", "CREATURE", 10, 2, 5)
coniferous.addSpawn("clickme.animals.entity.passive.EntityBird", "CREATURE", 16, 2, 4)

mountain.addSpawn("gaia.entity.EntityGaiaBanshee", "MONSTER", 3, 1, 2)
mountain.addSpawn("gaia.entity.EntityGaiaDullahan", "MONSTER", 5, 1, 3)
mountain.addSpawn("net.minecraft.entity.passive.EntityCow", "CREATURE", 10, 2, 5)
mountain.addSpawn("net.minecraft.entity.passive.EntityPig", "CREATURE", 10, 2, 5)
mountain.addSpawn("net.minecraft.entity.passive.EntitySheep", "CREATURE", 20, 2, 5)
mountain.addSpawn("net.minecraft.entity.passive.EntityChicken", "CREATURE", 10, 2, 5)
mountain.addSpawn("clickme.animals.entity.ambient.EntityCricket", "CREATURE", 10, 1, 3)
mountain.addSpawn("gaia.entity.EntityGaiaValkyrie", "CREATURE", 1, 1, 2)
mountain.addSpawn("gaia.entity.EntityGaiaGryphon", "CREATURE", 5, 1, 2)

desert.addSpawn("gaia.entity.EntityGaiaAnubis", "MONSTER", 3, 1, 3)
desert.addSpawn("gaia.entity.EntityGaiaSphinx", "MONSTER", 1, 1, 2)
desert.addSpawn("gaia.entity.EntityGaiaCockatrice", "CREATURE", 5, 1, 3)
desert.addSpawn("gaia.entity.EntityGaiaHarpy", "CREATURE", 5, 1, 3)
desert.addSpawn("clickme.animals.entity.passive.EntityLizard", "CREATURE", 13, 1, 3)
desert.addSpawn("clickme.animals.entity.passive.EntitySnake", "CREATURE", 8, 1, 2)

swamp.addSpawn("net.minecraft.entity.monster.EntityWitch", "MONSTER", 12, 1, 2)
swamp.addSpawn("net.minecraft.entity.monster.EntitySlime", "MONSTER", 16, 1, 3)
swamp.addSpawn("gaia.entity.EntityGaiaWitch", "MONSTER", 3, 1, 1)
swamp.addSpawn("gaia.entity.EntityGaiaSwamper", "MONSTER", 3, 1, 2)
swamp.addSpawn("gaia.entity.EntityGaiaSludgeGirl", "MONSTER", 5, 1, 2)
swamp.addSpawn("com.emoniph.witchery.entity.EntityToad", "CREATURE", 8, 1, 4)
swamp.addSpawn("clickme.animals.entity.passive.EntityBird", "CREATURE", 12, 2, 4)
swamp.addSpawn("clickme.animals.entity.ambient.EntityCentipede", "CREATURE", 12, 1, 3)
swamp.addSpawn("clickme.animals.entity.passive.EntityDuck", "CREATURE", 10, 2, 5)
swamp.addSpawn("clickme.animals.entity.passive.EntitySnake", "CREATURE", 8, 1, 2)
swamp.addSpawn("gaia.entity.EntityGaiaNaga", "CREATURE", 3, 1, 2)
swamp.addSpawn("gaia.entity.EntityGaiaSiren", "CREATURE", 5, 1, 2)
swamp.addSpawn("clickme.animals.entity.water.EntityTropiFish", "WATER_CREATURE", 8, 1, 10)
swamp.addSpawn("net.minecraft.entity.passive.EntitySquid", "WATER_CREATURE", 5, 1, 3)
swamp.addSpawn("clickme.animals.entity.water.EntityMantaRay", "WATER_CREATURE", 4, 1, 3)
swamp.addSpawn("clickme.animals.entity.water.EntityPiranha", "WATER_CREATURE", 6, 2, 5)

ocean.addSpawn("net.minecraft.entity.passive.EntitySquid", "WATER_CREATURE", 10, 1, 6)
ocean.addSpawn("clickme.animals.entity.water.EntityTropiFish", "WATER_CREATURE", 12, 1, 8)
ocean.addSpawn("clickme.animals.entity.water.EntityMantaRay", "WATER_CREATURE", 8, 1, 3)
ocean.addSpawn("clickme.animals.entity.water.EntityWhale", "WATER_CREATURE", 3, 1, 1)
ocean.addSpawn("clickme.animals.entity.water.EntityShark", "WATER_CREATURE", 4, 1, 2)
ocean.addSpawn("clickme.animals.entity.water.EntityAngler", "WATER_CREATURE", 2, 1, 2)
ocean.addSpawn("gaia.entity.EntityGaiaMermaid", "CAVE_CREATURE", 3, 1, 3)
ocean.addSpawn("gaia.entity.EntityGaiaSahuagin", "CAVE_CREATURE", 5, 1, 3)
ocean.addSpawn("gaia.entity.EntityGaiaSharko", "CAVE_CREATURE", 3, 1, 2)

beach.addSpawn("clickme.animals.entity.passive.EntityPenguin", "CREATURE", 15, 1, 5)
beach.addSpawn("clickme.animals.entity.passive.EntityDuck", "CREATURE", 10, 2, 5)
beach.addSpawn("clickme.animals.entity.water.EntityTropiFish", "WATER_CREATURE", 12, 1, 10)
beach.addSpawn("net.minecraft.entity.passive.EntitySquid", "WATER_CREATURE", 5, 1, 3)
beach.addSpawn("clickme.animals.entity.water.EntityMantaRay", "WATER_CREATURE", 8, 1, 3)

river.addSpawn("clickme.animals.entity.passive.EntityDuck", "CREATURE", 15, 2, 5)
river.addSpawn("clickme.animals.entity.water.EntityTropiFish", "WATER_CREATURE", 12, 1, 10)
river.addSpawn("clickme.animals.entity.water.EntityShark", "WATER_CREATURE", 2, 1, 1)
river.addSpawn("clickme.animals.entity.water.EntityPiranha", "WATER_CREATURE", 6, 2, 5)

jungle.addSpawn("gaia.entity.EntityGaiaCobblestoneGolem", "MONSTER", 3, 1, 2)
jungle.addSpawn("gaia.entity.EntityGaiaShaman", "MONSTER", 3, 1, 2)
jungle.addSpawn("net.minecraft.entity.passive.EntityOcelot", "CREATURE", 30, 2, 5)
jungle.addSpawn("clickme.animals.entity.passive.EntityBird", "CREATURE", 16, 2, 4)
jungle.addSpawn("clickme.animals.entity.ambient.EntityCentipede", "CREATURE", 12, 1, 3)
jungle.addSpawn("clickme.animals.entity.passive.EntityLizard", "CREATURE", 13, 1, 3)
jungle.addSpawn("clickme.animals.entity.ambient.EntityButterfly", "CREATURE", 10, 1, 3)
jungle.addSpawn("clickme.animals.entity.ambient.EntityCricket", "CREATURE", 10, 1, 3)
jungle.addSpawn("gaia.entity.EntityGaiaHunter", "CREATURE", 8, 1, 3)
jungle.addSpawn("gaia.entity.EntityGaiaCobbleGolem", "CREATURE", 5, 1, 2)
jungle.addSpawn("clickme.animals.entity.water.EntityPiranha", "WATER_CREATURE", 6, 2, 5)

snowy.addSpawn("cofh.thermalfoundation.entity.monster.EntityBlizz", "MONSTER", 8, 1, 3)
snowy.addSpawn("gaia.entity.EntityGaiaSelkie", "MONSTER", 3, 1, 2)
snowy.addSpawn("gaia.entity.EntityGaiaVampire", "MONSTER", 1, 1, 1)
snowy.addSpawn("gaia.entity.EntityGaiaDhampir", "MONSTER", 3, 1, 2)
snowy.addSpawn("clickme.animals.entity.passive.EntityPenguin", "CREATURE", 15, 1, 5)
snowy.addSpawn("gaia.entity.EntityGaiaYeti", "CREATURE", 5, 1, 1)
snowy.addSpawn("gaia.entity.EntityGaiaYukiOnna", "CREATURE", 3, 1, 3)

magical.addSpawn("thaumcraft.common.entities.monster.EntityPech", "MONSTER", 10, 1, 3)
magical.addSpawn("thaumcraft.common.entities.monster.EntityWisp", "MONSTER", 8, 1, 2)
magical.addSpawn("com.emoniph.witchery.entity.EntityGoblin", "CREATURE", 8, 1, 3)
magical.addSpawn("com.emoniph.witchery.entity.EntityCovenWitch", "CREATURE", 4, 1, 1)

nether.removeSpawn("gaia.entity.EntityGaiaWitherCow", "MONSTER")
nether.addSpawn("gaia.entity.EntityGaiaWitherCow", "MONSTER", 5, 1, 3)
nether.removeSpawn("gaia.entity.EntityGaiaSuccubus", "MONSTER")
nether.addSpawn("gaia.entity.EntityGaiaSuccubus", "MONSTER", 5, 1, 2)
nether.removeSpawn("gaia.entity.EntityGaiaBaphomet", "MONSTER")
nether.addSpawn("gaia.entity.EntityGaiaBaphomet", "MONSTER", 3, 1, 2)

**Comment by superckl** [comment]
If you take your script out, do bats spawn in such quantities?

**Comment by thephoenixlodge** [comment]
From what I'm seeing, no, neither slimes or bats are spawning in such high numbers. I haven't tested it overly thoroughly yet though. I definitely observed it with GoG creeps, mimics, ender eyes, jorogumo and sahuagin though.

**Comment by superckl** [comment]
Hmm, well unfortunately the mod isn't open source, so I'm fairly powerless to do an debugging. All BiomeTweaker does is modify the spawnlist, it doesn't do any spawning itself. I'd recommend contacting the author and pointing him/her here.

**Comment by superckl** [comment]
I'm going to go ahead and close this with the 'wontfix' tag. It's not in my control.
