### ISSUE TITLE
Add ability to specify "fillerBlockMeta"

### ISSUE THREAD

**Issue by superckl** [superckl/BiomeTweaker#37]
It's in the title. Requested here:

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2391123-biometweaker-customize-your-biomes?page=3#c58

**Comment by superckl** [comment]
Feature is in build 147:

http://jenkins.superckl.me/job/BiomeTweaker/147/

**Comment by resinate** [comment]
feature does not make sense im sorry

**Comment by superckl** [comment]
Example:

```
allBiomes = forAllBiomes()
allBiomes.set("fillerBlock", "minecraft:sandstone")
allBiomes.set("fillerBlockMeta", 1)
```
This will cause smooth sandstone (metadata 1) to generate as the filler block.

**Comment by resinate** [comment]
so the meta id has to come after the block declared?

**Comment by superckl** [comment]
http://minecraft.curseforge.com/projects/biometweaker/files/2266494
