### ISSUE TITLE
"separate files" setting not working 1.2.128

### ISSUE THREAD

**Issue by Teibidh** [superckl/BiomeTweaker#38]
As the title says, this setting has no effect, separate files are generated whether the settings is "true" or "false"

**Comment by superckl** [comment]
Turns out I misspelled it in the code. You can either change the field in your config to `seperate files`,
or update to the latest build:

http://jenkins.superckl.me/job/BiomeTweaker/150/

**Comment by Teibidh** [comment]
Awesome, thank you for the reply

**Comment by Teibidh** [comment]
I can confirm that the update provided in the link did resolve the issue.

**Comment by superckl** [comment]
http://minecraft.curseforge.com/projects/biometweaker/files/2266494
