### ISSUE TITLE
Mod disabled

### ISSUE THREAD

**Issue by Rocketblaster37** [superckl/BiomeTweaker#39]
The mod loads but is not enabled I believe this is a bug if not please help.

**Comment by superckl** [comment]
BiomeTweakerCore gets disabled. Not BiomeTweaker. Different things.

**Comment by Rocketblaster37** [comment]
None of my scripts do anything though i've been following your tutorial on youtube

**Comment by Rocketblaster37** [comment]
Sorry looked at my script again it was really broken i sent this at the middle of the night i was tired im sorry for wasting your time.
