### ISSUE TITLE
delete me

### ISSUE THREAD

**Issue by resinate** [superckl/BiomeTweaker#42]
issue fixed here my bad

**Comment by superckl** [comment]
What are you expecting that 
```mountainousWasteland.set("fillerBlock", "minecraft:netherrack", "registerGenBlockRep")```
does? The set command only takes two arguments... and `registerGenBlockRep` is it's own command, not an argument for the `set` command. These commands don't work because they don't exist.

**Comment by resinate** [comment]
prob i have is meta datas dont work at all on any command i use. sry for the newb coding part stuff like this dont work at all.

Void = forBiomes(0-39,85,106,129-134,140,149,151,155-158,160-167,192-195)
Void.set("topBlock", "minecraft:sand")
Void.set("topBlockMeta", 1)
and Void.registerGenBlockRep("minecraft:stone", "minecraft:sand", 1)

i dont get what im doing wrong here is full script

Void = forBiomes(0-39,85,106,129-134,140,149,151,155-158,160-167,192-195)

Void.create("DESERT", 20000)
Void.set("color", 2434341)
Void.set("name", "Burntlands")
Void.set("enableRain", false)
Void.set("temperature" 2.0)
Void.set("humidity", 0.0)
Void.set("height", 2.0)
Void.set("heightVariation", 0.25)
Void.set("grassColor", 2434341)
Void.set("foliageColor", 2434341)
Void.set("waterColor", 2434341)
Void.set("waterTint", 2434341)
Void.removeAllSpawns("CREATURE")
Void.removeFeature("LAVA")
Void.removeFeature("LAKE")
Void.set("genVillages", true)

Void.set("topBlock", "minecraft:sand")
Void.set("topBlockMeta", 1)

Void.set("fillerBlock", "minecraft:coal_block")
Void.registerGenBlockRep("minecraft:water", "minecraft:coal_block")
Void.registerGenBlockRep("minecraft:lava", "minecraft:coal_block")
Void.registerGenBlockRep("minecraft:stone", "minecraft:coal_block")
Void.registerGenBlockRep("minecraft:gravel", "minecraft:coal_block")
Void.registerGenBlockRep("minecraft:cobblestone", "minecraft:coal_block")
Void.addSpawn("net.minecraft.entity.monster.Zombie", "MONSTER", 10, 8, 16)
Void.set("isSpawnBiome", true)
Void.set("genWeight", 20000)

**Comment by superckl** [comment]
What exactly do you want to happen? Coal and sand blocks don't have any different forms based on metadata...
