### ISSUE TITLE
adding meta ids for fillers

### ISSUE THREAD

**Issue by resinate** [superckl/BiomeTweaker#43]
Void.set("topBlock", "minecraft:coal_block")
Void.set("fillerBlock", "minecraft:coal_block")
Void.set("actualFillerBlock", "Railcraft:cube")

change to:

X= meta id
Void.set("topBlock", "minecraft:coal_block", x)
Void.set("fillerBlock", "minecraft:coal_block", x)
Void.set("actualFillerBlock", "Railcraft:cube", x)

should be very easy to do since u have this code with replace blocks.
also
"Void.registerGenBlockRep("minecraft:dirt", "railcraft:cube", 6)"
meta datas dont work on this code anymore, do not know why.

**Comment by superckl** [comment]
Not doing that for the set command modification. They already exist in the form of `fillerBlockMeta` and `topBlockMeta` for the `set` command.

I have no idea why you can't specify metadatas. They work for me.

**Comment by resinate** [comment]
becuase it doesnt work
can u full example of u using it
