### ISSUE TITLE
not able to replace nether castle blocks?

### ISSUE THREAD

**Issue by resinate** [superckl/BiomeTweaker#45]
i wanted to do,
Void.registerGenBlockRep("minecraft:nether_brick", "Railcraft:brick.abyssal", 0)
Void.registerGenBlockRep("minecraft:nether_brick_fence", "Railcraft:wall.beta", 5)
Void.registerGenBlockRep("minecraft:nether_brick_stairs", "Railcraft:stair", 13)

but no replacements work..

**Comment by superckl** [comment]
Nether fortresses are features. They are placed after block replacement happens. That's not really biome tweaking, is it?

**Comment by resinate** [comment]
aww man lol come on lol
