### ISSUE TITLE
some features load some dont - its random

### ISSUE THREAD

**Issue by resinate** [superckl/BiomeTweaker#47]
did i make this script in correct order, cuz im getting massive fps drops and stuff like water color not changing. if its in bad order can someone re-order it? some things load and some things dont its random. 

also when using Void.set("topBlockMeta", 4) and Void.set("fillerBlockMeta", 4) its whats causing the huge fps drops, normally i run 300 fps and with those 2 lines i run 40 fps when i move

Void = forBiomes(0-39,129-134,140,149,151,155-158,160-167,192-195)
Void.create("LAND", 100000)
Void.set("color", 2434341)
Void.set("name", "Abyssal Lands")
Void.set("enableRain", false)
Void.set("enableSnow", false)
Void.set("temperature", 1.0)
Void.set("humidity", 1.0)
Void.set("height", 1.0)
Void.set("heightVariation", 0.25)
Void.set("grassColor", 2434341)
Void.set("foliageColor", 2434341)
Void.set("waterColor", 65280)
Void.set("waterTint", 65280)
Void.set("topBlock", "TConstruct:Smeltery")
Void.set("topBlockMeta", 4)
Void.set("fillerBlock", "TConstruct:Smeltery")
Void.set("fillerBlockMeta", 4)
Void.addActualFillerBlock("TConstruct:Smeltery")
Void.registerGenBlockRep("minecraft:stone", "TConstruct:Smeltery", 4)
Void.registerGenBlockRep("minecraft:water", "TConstruct:Smeltery", 2)
Void.registerGenBlockRep("minecraft:netherrack", "Railcraft:cube", 6)
Void.registerGenBlockRep("minecraft:lava", "TConstruct:Smeltery", 2)
Void.set("genVillages", true)
Void.set("isSpawnBiome", true)
Void.removeDecoration("FLOWERS")
Void.removeDecoration("REED")
Void.removeDecoration("PUMPKIN")
Void.removeDecoration("LAKE")
Void.removeFeature("LAVA")
Void.removeFeature("LAKE")
Void.removeFeature("CUSTOM")
Void.removeFeature("DUNGEON")
Void.removeFeature("RAVINE")
Void.removeFeature("CAVES")
Void.removeAllSpawns("CREATURE")
Void.removeAllSpawns("MONSTER")
Void.removeAllSpawns("CAVE_CREATURE")
Void.removeAllSpawns("WATER_CREATURE")
Void.set("genWeight", 100000)

ALSO:
[FML/]: The world 6068b35c (Searing lands) may have leaked: seen 10 times.
is the errors im getting from this mod. i dont know where its coming from.

**Comment by superckl** [comment]
What block is "TConstruct:Smeltery", 4?
