### ISSUE TITLE
replacing biomes are not working

### ISSUE THREAD

**Issue by resinate** [superckl/BiomeTweaker#48]
Void = forBiomes(1-7,10-39,129-134,140,149,151,155-158,160-167,192-195)
Void.regiserGenBiomeRep(0)

trying to replace all overworld biomes with ocean doesnt work.

and this is what wiki says
biome2 = forBiomes(2)
biome9.regiserGenBiomeRep(10)

where is biome2 and biome9 referenced at to declare these statements valid?

**Comment by superckl** [comment]
The wiki had a few typos. The correct command is detailed in #32, you should be using `registerBiomeGenRep`.
