### ISSUE TITLE
way to disable caves and ravines?

### ISSUE THREAD

**Issue by resinate** [superckl/BiomeTweaker#51]
is there a way to disable all these and stuff like mineshafts?

**Comment by superckl** [comment]
No. Those are generated independent of biome. Check out a mod called Dimensional Control for that kind of stuff:

http://minecraft.curseforge.com/projects/dimensional-control

**Comment by resinate** [comment]
mod author quit the mod. so its up to u now.

**Comment by superckl** [comment]
I'm on the development team that writes that mod. Where did find that information?
