### ISSUE TITLE
huge fps drops on biome tweaker

### ISSUE THREAD

**Issue by resinate** [superckl/BiomeTweaker#52]
when i remove it i make a world with 800 fps, and when i make a world with ur mod i get 40-60 fps. i dunno where and why it does this. doesnt matter what block i use to replace, gives same results

**Comment by nanakisan** [comment]
are you dead certain it is BiomeTweaker causing the issue? I've done the same numerous times myself. No FPS loss or gain was ever noted.

**Comment by superckl** [comment]
Your going to have to give me your scripts if you want any help.

**Comment by resinate** [comment]
ok
https://drive.google.com/file/d/0B21rvpke5kB3WjExLUE1QTRyRlk/view?usp=sharing

thats the whole pack. i dont know what it is,  ive had mod devs look around and cant find the source of the error. all i know is tps and fps drop instantly when in a village.

pack uses at launcher

seriously if u can find it ill be glad to fix it on the spot

**Comment by superckl** [comment]
I'm not going to fix your pack for you. This tracker is for issues with BiomeTweaker. If the fps drops occur when you add BiomeTweaker, then it's my issue. Otherwise, don't concern me with it. Nobody has reported fps drops, and I highly doubt anything BiomeTweaker does could cause them.
