### ISSUE TITLE
Double village glitch

### ISSUE THREAD

**Issue by resinate** [superckl/BiomeTweaker#53]
village generate off a seed number, what i found when using climate control plus this mod is its generating 2 villages in same spots. when u disable one the lag and tps issue goes away.

reason why u cant see it is cuz its running the excat same village builder 2 times.

**Comment by superckl** [comment]
How do you know this? BiomeTweaker doesn't run any village generation. It uses methods built into Forge to add biomes to the list of viable generation biomes.

**Comment by resinate** [comment]
does this code enable villages to generate? Void.set("genVillages", true), whats going is ur mod runs village spawn then climate runs village again. u can see by looking at chests in village notice the have double the amount of loot in them. TC, smith, railcraft houses. so i have no idea how either u or them will go about fixing the bug if i report it to them also

**Comment by nanakisan** [comment]
This makes little to no sense at all. I can confirm what superckl has said about village generation. It never does generation at all. All BT does is say "Hey this biome can now generate villages! HAVE FUN!" After that it is up to Forge and MC to determine if the village should be a desert (Sandstone) or normal village.

So this seems to be entirely the fault of Climate Control. As that mod I know for a fact does black magic voodoo stuff in regards to biome management. Among other things it does a lot more than what it lets on about.
