### ISSUE TITLE
Villages problem.

### ISSUE THREAD

**Issue by demon-goxa** [superckl/BiomeTweaker#55]
Im using Realistic World Generation in my modpack and decided to disable villages at all. 

allBiomes = forAllBiomes()
allBiomes.set("genVillages", false)

This script doesnt effect. Nothing happens. They generating in same biomes and not generating everythere if set True. Is it a bug?

oh and version is 128
i guess its conflict with rwg, is it possible to disable villages?

**Comment by superckl** [comment]
Please try with the latest dev version to see if the issue still persists. I would expect it does, but just to make sure.

http://jenkins.superckl.me/job/BiomeTweaker/156/

**Comment by demon-goxa** [comment]
Yes it does. =( I reeeally need a solution for villages. Compatibility with RWG is very requered

**Comment by superckl** [comment]
I found the issue. It's in a method called `areBiomesViable`. In Vanilla, the method goes something like this
```
    public boolean areBiomesViable(int p_76940_1_, int p_76940_2_, int p_76940_3_, List p_76940_4_)
    {
        IntCache.resetIntCache();
        int l = p_76940_1_ - p_76940_3_ >> 2;
        int i1 = p_76940_2_ - p_76940_3_ >> 2;
        int j1 = p_76940_1_ + p_76940_3_ >> 2;
        int k1 = p_76940_2_ + p_76940_3_ >> 2;
        int l1 = j1 - l + 1;
        int i2 = k1 - i1 + 1;
        int[] aint = this.genBiomes.getInts(l, i1, l1, i2);

        try
        {
            for (int j2 = 0; j2 < l1 * i2; ++j2)
            {
                BiomeGenBase biomegenbase = BiomeGenBase.getBiome(aint[j2]);

                if (!p_76940_4_.contains(biomegenbase))
                {
                    return false;
                }
            }

            return true;
        }
        catch (Throwable throwable)
        {
            // Omitted
        }
    }
```

In RWG, it goes something like [this](https://github.com/Ted80-Minecraft-Mods/Realistic-World-Gen/blob/master/rwg/world/ChunkManagerRealistic.java#L574) (although that repo is far out of date). There's no feasible way to fix this on my end, considering I don't have access to updated source code. You need to ask @ted80.

**Comment by demon-goxa** [comment]
Okay,got it, ty. I guess ted80 is no longer active (so nobody will see fixes/updates for rwg)

**Comment by superckl** [comment]
The only other terrain mod I know is Alternate Terrain Generation by TTFTCUTS. I'm not sure what is and what isn't compatible.

**Comment by demon-goxa** [comment]
Thanks, i'll try.
