### ISSUE TITLE
Can't remove trees from Roofed Forest

### ISSUE THREAD

**Issue by CcytherR** [superckl/BiomeTweaker#59]
allBiomes = forAllBiomes()
allBiomesbut = forAllBiomesExcept(0, 3, 7, 8, 9, 10, 11, 12, 13, 16, 20, 24, 34, 37, 38, 39, 52, 83, 85, 99, 100, 102, 115, 116, 117, 118, 119, 120, 121, 122, 123)
problemgrassBiomes = forBiomes(3, 131, 34, 162, 20, 35, 163, 32, 160, 33, 13, 17, 18, 19, 22, 28, 31, 156, 161)
desertHills = forBiomes(17)
allBiomes.set("topBlock", "minecraft:hardened_clay")
allBiomes.set("fillerBlock", "minecraft:stone")
allBiomes.removeAllSpawns("CREATURE")
allBiomes.removeAllSpawns("WATER_CREATURE")
allBiomes.removeAllSpawns("CAVE_CREATURE")
allBiomes.removeDecoration("GRASS")
allBiomes.removeDecoration("BIG_SHROOM")
allBiomes.removeDecoration("CACTUS")
allBiomes.removeDecoration("DEAD_BUSH")
allBiomes.removeDecoration("LILYPAD")
allBiomes.removeDecoration("FLOWERS")
allBiomes.removeDecoration("PUMPKIN")
allBiomes.removeDecoration("REED")
allBiomes.removeDecoration("SHROOM")
allBiomes.removeDecoration("TREE")
allBiomes.removeDecoration("LAKE")
allBiomes.removeFeature("LAKE")
allBiomes.removeFeature("LAVA")
problemgrassBiomes.removeDecoration("GRASS")
allBiomes.removeFeature("GRASS")
allBiomesbut.set("heightVariation", -0.1)
desertHills.set("height", 1.0)

This doesn't seem to remove all trees and grass from Roofed forest/Extreme hills and Mega Taiga hills biomes maybe 1 or 2 other biomes too trying to generate a wasteland basically with biometweaker and climate control, im going to try with just your mod and see if its still an issue, Mods also included currently with those: NEI, Streams, RecurrentComplex, Waila.

Thanks.

**Comment by superckl** [comment]
Tree generation is hard-coded into forest biomes, unfortunately. Setting the top and filler block to something trees can't live on will stop them generating. Otherwise, you're out of luck.

Are you running 1.7.10 or 1.8?

**Comment by CcytherR** [comment]
Yeah this is with 1.7.10 it's just as though roofed forest, savanna and mega taiga seem to ignore the remove grass part hence also getting trees randomly spawning in roofed forest biome, the rest just has spawned grass but no tree issues.

**Comment by superckl** [comment]
The "GRASS" decoration doesn't refer to the thin layer of grass on top of the ground, if that's what you think. That determines if tall grass generates. To remove the full block grass, you need to set the "topBlock" to something else.

**Comment by superckl** [comment]
Regarding the issue of not being able to set the topBlock in some biomes. Open BiomeTweaker's config and locate the `remove late block assignments` fields:

```
    //Enable this if you want BiomeTweaker to force topBlock and fillerBlock overrides in most biomes.
    //This is done by using ASM to strip some assignments that happen in the "genTerrainBlocks" blocks. This will not work for all biomes.
    //This WILL cause issues where some biomes will have incorrect top and filler blocks if you do not override them (Extreme Hills (M), Mutated Savannah, Taiga).
    //light ASM must be disabled for this to have any effect.
    "remove late block assignments":false,
```
Set it to true.
