### ISSUE TITLE
addDicType not working

### ISSUE THREAD

**Issue by SirWilli** [superckl/BiomeTweaker#60]
hey,
addDicType does somehow not work for me. The generated json file only shows OCEAN but not WATER

Script:
```
Water = forBiomes(0, 7, 10, 11, 24)
Water.set("name", "Bloody Water")
Water.addDicType("WATER")
```

**Comment by superckl** [comment]
Yep. That's a bug. Fixed in latest build.

1.7.10:
http://jenkins.superckl.me/job/BiomeTweaker/164/

1.8:
http://jenkins.superckl.me/job/BiomeTweaker%201.8/163/

**Comment by SirWilli** [comment]
Works now, thanks :)
