### ISSUE TITLE
Change lake liquid?

### ISSUE THREAD

**Issue by SirWilli** [superckl/BiomeTweaker#61]
Hey,
is there any way to change the liquid in lakes? 
I tried the following but it doesn't work:
```
Blood.set("liquidFillerBlock", "AWWayofTime:lifeEssence")
Blood.registerGenBlockRep("minecraft:water", "AWWayofTime:lifeEssence")
```

**Comment by superckl** [comment]
No. I don't have that degree of control over lake generation without completely completely replacing it. Sorry.

I'm considering adding a command to allow for later block replacements, once everything has been placed, but don't count on it.

**Comment by SirWilli** [comment]
Ouh ok, I will have to remove the late then for now. :/
