### ISSUE TITLE
Disable Jungle/Desert Temple?

### ISSUE THREAD

**Issue by SirWilli** [superckl/BiomeTweaker#62]
is there any way to disable temples?

**Comment by superckl** [comment]
Use the `removeFeatureCommand` to remove "DUNGEON" from Jungles.

https://github.com/superckl/BiomeTweaker/wiki/Basic-Script-Commands#removefeature

**Comment by SirWilli** [comment]
Oh okay, I first thought it removes caves and spawner rooms.
