### ISSUE TITLE
topBlock + fillerBlock + addActualFillerBlock issue

### ISSUE THREAD

**Issue by SirWilli** [superckl/BiomeTweaker#64]
so the wiki says to use addActuaFillerBlock so that topBlock works but then generates default stuff like grass, grass, gravel..

```
allBiomes.set("topBlock", "ExtrabiomesXL:terrain_blocks1")
allBiomes.set("fillerBlock", "Quadrum:redrock")
allBiomes.addActualFillerBlock("Quadrum:redrock")
```
![](https://i.imgur.com/tQpRoBz.png)

Is this a bug or issue in my script? For few areas it works somehow

**Comment by superckl** [comment]
No, `actualFillerBlock` and `fillerBlock` are different things. `fillerBlock` and `topBlock` are what generate that layer of dirt of grass you usually see in world. the `actuaFillerBlock` is the 60+ layers of stone underneath that. Unless you're doing what's detailed [here](https://github.com/superckl/BiomeTweaker/wiki/On-the-Topic-of-Block-Replacement), don't use the `addActuallFillerBlock` command.

**Comment by SirWilli** [comment]
Hm, how do I generate it then correctly? Because if I remove the `actualFillerBlock` it will not generate the `topBlock`. Everything will be out of the `Quadrum:redrock` block.

**Comment by superckl** [comment]
Have you tried it, or are you just guessing?

**Comment by SirWilli** [comment]
You mean tried without `actualFillerBlock`? Yes I did.

**Comment by superckl** [comment]
What exactly are you trying to achieve with the script?

**Comment by SirWilli** [comment]
I generate grass via cofh but the issue is that it generates in water too so I thought I just generate a different block below the topBlock like it is with grass, dirt and stone.

**Comment by superckl** [comment]
Do you want to replace the grass, dirt, or stone?

**Comment by SirWilli** [comment]
Grass

**Comment by superckl** [comment]
What do you mean by the grass generates in water as well?

**Comment by SirWilli** [comment]
I mean the decoration of grass not the grass block.

**Comment by superckl** [comment]
Have you tried the `removeDecoration` command? Use the parameter "GRASS".

**Comment by SirWilli** [comment]
I don't want to remove grass I want to add custom grass. For that I need a layer of `ExtrabiomesXL:terrain_blocks1` above `Quadrum:redrock`. That's why I'm trying to get the `topBlock` and `fillerBlock` to work.

**Comment by superckl** [comment]
Why doesn't the script

```
all.set("topBlock", "ExtraBiomesXL:terrain_blocks1)
all.set("fillerBlock", " Quadrum:redrock") 
```

work? Run that script and show me a picture as well as a log file if it doesn't work.

**Comment by SirWilli** [comment]
![](https://i.imgur.com/tXXrXmP.png)
https://gist.github.com/SirWilli/c5393e90dddf238e0cf3

I also spawned in the ocean again and couldn't find any error about this in the log

**Comment by superckl** [comment]
I was able to properly set the topBlock to "ExtrabiomesXL:terrain_blocks1", with a different fillerBlock. I had Quadrum installed as well, but I'll need your configuration to test it properly on my side. I'm honestly not sure what the problem is for you.

![2015-11-22_13 52 26](https://cloud.githubusercontent.com/assets/2230216/11325924/55ad6cd4-9120-11e5-9f4a-bc8a815ee964.png)

**Comment by SirWilli** [comment]
Hm, that's weird. That's my complete script: http://pastebin.com/z63tj4Q6
I also tried it with `minecraft:dirt` instead of the quadrum block and also no effect.

**Comment by superckl** [comment]
Oh! I wasn't aware you were replacing all stone with "Quadrum:redrock"... My bad! Then you'll definitely want to add `allBiomes.addActualFillerBlock("Quadrum:redrock")` to your script. Sorry!

**Comment by SirWilli** [comment]
Okay but what to do about the grass, dirt and so on

**Comment by superckl** [comment]
Umm, I'm not entirely sure where that's coming from. Does it seem to be random or is it a specific biome? Only near water?

**Comment by SirWilli** [comment]
Seems to be specific biomes, beach and swampland looks fine while extreme hills does have grass as topBlock

**Comment by SirWilli** [comment]
I found the issue. It's because of this:
```
# removes other biomes
notWantedBiomes = forBiomes(21, 3, 140, 158, 3, 131, 133, 34, 162, 25, 149, 151, 156, 157, 163, 37, 165, 20, 28, 192, 164, 166, 167)
notWantedBiomes.remove()
```
Shouldn't that remove the biomes from the generation?

**Comment by superckl** [comment]
"should"

BiomeTweaker tells Forge that those biomes shouldn't generate. Whether or not whatever generation you're using (or if they're hardcoded) asks Forge for that information is not up to me. That's why I added the `registerGenBiomeRep` command... which also may fail in modded generation if they don't fire the proper events...

**Comment by SirWilli** [comment]
`registerGenBiomeRep `? I can't find anything about that in the wiki.

**Comment by superckl** [comment]
It's the first command you use in your script...

**Comment by SirWilli** [comment]
Yea, I realized that after I created the comment.

**Comment by SirWilli** [comment]
Hm, now I found a biome which does have the issue too but is not in the list. (Mega Spruce Taiga = 160) and in the ocean it somehow generates a layer of gravel and stone.

**Comment by SirWilli** [comment]
The weird thing is all that only happens if I use addActualFillerBlock, I couldn't find any worldgen "bug" without it. Everything was out of Quadrum:redrock

**Comment by SirWilli** [comment]
@superckl any idea what causes the issue?

**Comment by superckl** [comment]
The thing you just described is detailed [here](https://github.com/superckl/BiomeTweaker/wiki/On-the-Topic-of-Block-Replacement#now-the-top-and-filler-blocks-arent-generating). As for the actual weirdness, no, I don't have a clue.

**Comment by SirWilli** [comment]
After removing the first 10 lines the issue exists too, so seems it is not related to the `remove()` or `registerGenBiomeRep`

**Comment by superckl** [comment]
Regarding the issue of not being able to set the topBlock in some biomes. Open BiomeTweaker's config and locate the `remove late block assignments` field:

```
    //Enable this if you want BiomeTweaker to force topBlock and fillerBlock overrides in most biomes.
    //This is done by using ASM to strip some assignments that happen in the "genTerrainBlocks" blocks. This will not work for all biomes.
    //This WILL cause issues where some biomes will have incorrect top and filler blocks if you do not override them (Extreme Hills (M), Mutated Savannah, Taiga).
    //light ASM must be disabled for this to have any effect.
    "remove late block assignments":false,
```
Set it to true.

**Comment by SirWilli** [comment]
I think that fixed it but I need to do some more testing soon, thanks.

**Comment by superckl** [comment]
Let me know if it doesn't work out. Anything else still a problem?

**Comment by SirWilli** [comment]
I couldn't find any biome with grass blocks so it looks all fine but the gravel issue in the ocean is still there.

**Comment by superckl** [comment]
Are you sure you're setting the topBlock in the ocean?

**Comment by SirWilli** [comment]
Yea, `allBiomes = forAllBiomesExcept(8, 9)`

**Comment by superckl** [comment]
Do you have any other mods installed that change oceans? It's working fine for me.

**Comment by superckl** [comment]
I take that back, it's not. Looking into it.

**Comment by superckl** [comment]
Going to make a new command for this when I have time.

**Comment by superckl** [comment]
The layer of gravel is hard-coded into biomes. Give this build a shot:

http://jenkins.superckl.me/job/BiomeTweaker/176/

It adds `oceanBlock` to the `set` command. It's nearly identical to `topBlock` in how you use it. e.g.

    allBiomes.set("oceanBlock", "minecraft:sand")

This should change that layer of gravel to whatever you set. It may have other consequences elsewhere, but I'm really not sure. I couldn't find anywhere else that the layer of gravel appeared.

**Comment by SirWilli** [comment]
Looks fine thanks but there seems to be another layer which doesn't get replaced:

![](https://i.imgur.com/uEAWlUx.png)

**Comment by superckl** [comment]
All of the hardcoding... *sigh*

http://jenkins.superckl.me/job/BiomeTweaker/177/

"oceanTopBlock" and "oceanFillerBlock". They do what you would expect. They *are* different than regular "topBlock" and "fillerBlock", though I would recommend still setting those as well.

**Comment by SirWilli** [comment]
I assume this 2 replace oceanBlock?

**Comment by SirWilli** [comment]
Is there any way to override the meta ID of the mesa biomes?

**Comment by superckl** [comment]
No. Mesas are a hard-coded mess of generation badness. If they aren't necessary, I would recommend replacing them.
