### ISSUE TITLE
Plains only world and disabling double plants?

### ISSUE THREAD

**Issue by smcnabb** [superckl/BiomeTweaker#66]
I'm not sure if this is a bug or a limitation of the game but I'm having trouble getting a Plains only world to generate and don't seem to be able to remove double plants e.g. Double Tallgrass, Sunflowers etc.

Here's my current config:

    # Remove all biomes
    allBiomes = forAllBiomes()
    allBiomes.remove()
    allBiomes.set("genWeight", 1)
    allBiomes.set("isSpawnBiome", false)

    # Remove flowers and grass
    allBiomes.removeDecoration("FLOWERS")
    allBiomes.removeDecoration("GRASS")

    # Try and get rid of double plants
    allBiomes.removeFlower("minecraft:double_plant", 0) # Doesn't seem to work
    allBiomes.removeFlower("minecraft:double_plant", 1) # Doesn't seem to work
    allBiomes.removeFlower("minecraft:double_plant", 2) # Doesn't seem to work
    allBiomes.removeFlower("minecraft:double_plant", 3) # Doesn't seem to work
    allBiomes.removeFlower("minecraft:double_plant", 4) # Doesn't seem to work
    allBiomes.removeFlower("minecraft:double_plant", 5) # Doesn't seem to work

    # Create tweaked version of Plains biome
    newPlains = forBiomes(1)
    newPlains.set("name", "NewPlains")
    newPlains.set("enableRain", false)
    newPlains.set("enableSnow", false)
    newPlains.set("genWeight", 1000)
    newPlains.set("genVillages", false)

    # Each biome type needs at least one biome
    newPlains.addToGeneration("WARM", 2000)
    newPlains.addToGeneration("COOL", 2000)
    newPlains.addToGeneration("DESERT", 2000)
    newPlains.addToGeneration("ICY", 2000)

    # Override hardcoded biomes
    newPlains.registerGenBiomeRep(2) # Desert
    newPlains.registerGenBiomeRep(3) # Extreme Hills
    newPlains.registerGenBiomeRep(4) # Forest (Doesn't seem to work)
    newPlains.registerGenBiomeRep(5) # Taiga
    newPlains.registerGenBiomeRep(6) # Swamplands
    newPlains.registerGenBiomeRep(14) # Mushroom Island
    newPlains.registerGenBiomeRep(18) # Forest Hills (Doesn't seem to work)
    newPlains.registerGenBiomeRep(21) # Jungle
    newPlains.registerGenBiomeRep(32) # Mega Taiga
    newPlains.registerGenBiomeRep(35) # Savanna
    newPlains.registerGenBiomeRep(38) # Mesa Plateau F
    newPlains.registerGenBiomeRep(39) # Mesa Plateau

And here's a sample screenshot:

https://i.imgur.com/K72zFye.png

As you can see I'm standing in my NewPlains biome but to the right is a Forest biome and up ahead is a Forest Hills biome, and Double Tallgrass is generating (as are sunflowers etc.).

Is it possible to get rid of the Forest and ForestHill biomes and stop double plants from generating?

**Comment by superckl** [comment]
To replace biome 4 with biome 1, you should call `registerBiomeGenRep` on biome 4. e.g.

```
forest = for biomes(4)
forest.registerGenBiomeRep(1)
```

or just

```
Tweaker.registerGenBiomeRep(4,1)
```

It may be simpler to just do

```
allButPlains = forAllBiomesExcept(1)
allButPlains.registerGenBiomeRep(1)
```
to generate a one-biome world.

I'll look into the double-tall grass.

**Comment by smcnabb** [comment]
Thanks for the quick reply.

Unfortunately neither of those seemed to work. I dug around in the logs a bit and found something that might point to the problem.

I reduced my config to:

    allButPlains = forAllBiomesExcept(1)
    allButPlains.registerGenBiomeRep(1)

And found the following in the log file:

    [16:51:18] [Client thread/INFO] [BiomeTweaker/BiomeTweaker]: Beginning script parsing...
    [16:51:18] [Client thread/ERROR] [BiomeTweaker/BiomeTweaker]: Failed to find meaning in command registerGenBiomeRep(1). It will be ignored.
    [16:51:18] [Client thread/INFO] [BiomeTweaker/BiomeTweaker]: Finished script parsing.

**Comment by smcnabb** [comment]
I've figured out what the biome problem was - I was using the latest Release version 1.2.128 from Curse which must not have the registerGenBiomeRep command. I updated to the latest Beta version 2.0.161 and I got my Plains world.

The double plants don't get removed though and there are no errors in the log.

Thanks for a great mod by the way!

**Comment by superckl** [comment]
Is this on 1.7.10 or 1.8?

**Comment by smcnabb** [comment]
Minecraft 1.7.10
Forge 10.13.4.1566

**Comment by superckl** [comment]
http://minecraft.curseforge.com/projects/biometweaker/files/2268813

Give that version a try. Use `biome.set("genDoublePlants", false)`.

**Comment by smcnabb** [comment]
Yeah, that worked perfectly. Thanks for adding that.
