### ISSUE TITLE
What is wrong with this script?

### ISSUE THREAD

**Issue by Sunconure11** [superckl/BiomeTweaker#69]
I'm trying to create several sets of scripts to make twilight forest mobs spawn in the overworld. However, they simply won't spawn. What am I doing wrong?

I also had the same issue with erebus mobs.

http://pastebin.com/X22tbC4e

**Comment by Sunconure11** [comment]
I seem to have figured it out. However, it appears they will only spawn at night. Would it be possible to make a spawn override the time it spawns at? So I can make Twilight Forest deer and such spawn during the day.

**Comment by superckl** [comment]
Not really. The light level checks are hard-coded into the spawning mechanics. I'm guessing the mobs check for the light levels of the Twilight Forest when spawning, which is around twilight (naturally) in the overworld. I'm not aware of any mods that could make that happen, and Twilight Forest isn't open source for me to look at the exact reason.

**Comment by nanakisan** [comment]
I would say this is not an issue for BT to directly address. Perhaps try using Just Another Spawner instead. It's specifically designed to handle mob spawning and customizing those spawns. It even overrides other mods spawning systems to achieve this. You could use that as a means of getting what you want.
