### ISSUE TITLE
Using "minecraft:sandstone" as the top or filler generates creeper-face chiseled sandstone.

### ISSUE THREAD

**Issue by keybounce** [superckl/BiomeTweaker#7]
I get creeper-face, chiseled sandstone, when I use "minecraft:sandstone".

```
Sandstone filler marker, lava oceans
allBiomes = forAllBiomesExcept(40-58, 163, 164, 166, 167)
## EXCLUDE TF !! **
# Also exclude Mesa Plateau M (normal 166 and FM 167),
# and Savanna M (normal 163 and plateau 164)
### allBiomes.set("topBlock", "ganyssurface:coarse_dirt")
allBiomes.set("fillerBlock", "minecraft:sandstone")
allBiomes.set("liquidFillerBlock","minecraft:lava")

mesaAlters = forBiomes(37, 165)
# 37 is normal mesa, to change. 165 is bryce, to change
# 38 is Plateau F, 39 is Plateau, both are hellified below.
# 166 and 167 are the M plateuas, left unchanged
# These biomes are low enough to have all that red sand.
# They default to sand and hardened clay.
mesaAlters.set("topBlock", "minecraft:sandstone")
```

**Comment by superckl** [comment]
Hope you don't mind, I edited your comment to use formatting for code.

I was unable to produce this in plain installation. It seems like something else you have installed is editing metadata. I recommend you try removing mods until you find the one messing it up. I'd also like a mod 
![2015-04-23_01 45 57](https://cloud.githubusercontent.com/assets/2230216/7291809/cac52516-e95a-11e4-891b-e1db54dfc1ba.png)
list.

**Comment by keybounce** [comment]
And the funny thing: it's biome dependent. It was messing up in mesas.

Mod list? 

total 32664
    0 1.7.10/
    8 1.7.10-AmazingChicken-0.1.0s.jar
   68 1.7.10-ExpandedIndustry-0.5.2b.jar
  420 1.7.10-HardLibCOG-0.5.2a.jar
  776 1.7.10-HarderOres-0.5.2d.jar
  252 1.7.10-HarderUnderground-0.5.2d.jar
  188 1.7.10-HarderWildlife-0.5.2e.jar
  804 AncientTrees-1.7.10-1.3.1.jar
   88 AppleCore-mc1.7.10-1.1.0.jar
   28 BetterSprinting.jar*
  156 BiomeTweaker-1.7.10-0.7.49.jar
   24 CaveControl 1.7.10 V6a.jar
 1032 CoFHCore-[1.7.10]3.0.2-268.jar.off
  268 CoFHLib-[1.7.10]1.0.1-151.jar.off
  156 CodeChickenCore-1.7.10-1.0.4.35-universal.jar
  400 CustomOreGen-1.7.10-1.2.18.jar.off
 1528 DragonAPI 1.7.10 V6f.jar
   60 FiniteFluids 1.7.10 Concept Mod.jar.off
  504 Ganys End-1.8.8.jar
  768 Ganys Nether-1.7.8.jar
  924 Ganys Surface-1.10.0.jar.off
  324 InGameInfoXML-1.7.10-2.8.1.80-universal.jar
   48 KoreSample-1.7.10-1.2.5.jar
   60 LegacyCraft 1.7.10 V6a.jar
  204 Loot++-0.12.jar
   60 LunatriusCore-1.7.10-1.1.2.21-universal.jar
   40 MobiusCore-1.2.3_1.7.10.jar
   92 MystNEI-Plugin-1.7.10-02.01.00.00.jar
  272 NEIPlugins-MC1.7.10-1.1.0.11-unofficial.jar
    4 NoVoidFog_1.7.10.zip
  500 NotEnoughItems-1.7.10-1.0.4.94-universal.jar
  176 OpenEye-0.6-1.7.10.jar
 5004 Opis-1.2.3_1.7.10.jar
  252 PlayerAPI-1.7.10-1.0.jar*
 6436 RotaryCraft 1.7.10 V6f.jar
  172 SpACore-1.7.10-01.05.01.00.jar
   20 UpdateCheckerMod-1.7.10.jar
   48 WAILAPlugins-MC1.7.10-0.0.1-10.jar
  536 Waila-1.5.10_1.7.10.jar
   28 WailaNBT-1.7.10-1.4.jar
   80 Wawla-1.2.1_1.7.10.jar
  132 XRay-3.0.1.beta.jar
    8 ZoomMod-1.2_1.7.10.jar
    8 [1.7.2] ChickenShed (v1.1.3).jar
  116 fastcraft-1.21.jar
   32 lloverlay-0.23a-10.12.0.1007-forge.jar
 2080 mystcraft-1.7.10-0.11.5.00.jar*
   56 mystcraft-panels-1.7.10-0.0.0.10.jar*
  132 neiaddons-mc1710-1.12.3.11.jar
    0 resources/
 2348 rftools-2.80.jar.off
  128 ttCore-MC1.7.10-0.1.0-67.jar
 3504 twilightforest-1.7.10-2.3.5.jar
 1312 worldedit-forge-mc1.7.10-6.0-beta-01.jar

**Comment by superckl** [comment]
Turns out mesa biomes set some blocks metadata to 1 (among other values). That is how they get the colored clay layers. Unfortunately, the code in which this is set is run after any Forge hook, so there's no direct way I can fix this.

I'll keep thinking of ways to fix this, but I can't guarantee anything.

**Comment by keybounce** [comment]
No problem.

I wound up having to leave mesas as sand/clay, and doing some work with COG to make them the way I wanted. It's good enough.

**Comment by superckl** [comment]
Fixing this would require overhauling a portion of the generation code, something I'm not going to do with BiomeTweaker. I'm going to consider it as an unfortunate side effect.
