### ISSUE TITLE
Actual Filler Metadata

### ISSUE THREAD

**Issue by ghost** [superckl/BiomeTweaker#75]
Is it possible to set the meta data for an actual filler block and if so how would one go about it?

**Comment by superckl** [comment]
You can specify the metadata when you register the replacement. I assume that's what you mean.

https://github.com/superckl/BiomeTweaker/wiki/Basic-Script-Commands#registergenblockrep
https://github.com/superckl/BiomeTweaker/wiki/On-the-Topic-of-Block-Replacement#whats-new-in-20152

**Comment by ghost** [comment]
Sorry. I should've  been more specific.

When you use the script command

object.addActualFillerBlock("minecraft:sandstone") how would I go about adding a meta data value to the sandstone? Or is that not possible.

**Comment by superckl** [comment]
Not currently possible. I can add it to the 1.8+ branches, but not to 1.7.10 (which I've stopped development for, except large bugs).

To clarify, it's not even possible to add it to 1.7.10, not that I just don't want to.
