### ISSUE TITLE
Bug adding and removing biome dictionary types for biomes created with BiomeTweaker

### ISSUE THREAD

**Issue by Zarzuf** [superckl/BiomeTweaker#76]
Hi,
I'm having some difficulty adding and removing biome dictionary types for biomes created with this mod.

For example I added a desert made of red sand with this config:

> RedDesert = forBiomes(210)
> RedDesert.create("DESERT", 10)
> RedDesert.set("name", "Vermilion Sands") 
> RedDesert.set("height", 1.44)
> RedDesert.set("heightVariation" , 0.05)
> RedDesert.set("topBlock", "minecraft:sand")
> RedDesert.set("topBlockMeta", 1)
> RedDesert.set("fillerBlock", "minecraft:sand")
> RedDesert.set("fillerBlockMeta", 1)
> RedDesert.set("color", 13369395)
> RedDesert.set("grassColor", -2106786)
> RedDesert.set("foliageColor", -4871594)
> RedDesert.set("temperature", 2.0)
> RedDesert.set("humidity", 0.0)
> RedDesert.set("enableRain", "false")
> RedDesert.set("genVillages", "true")
> RedDesert.set("isSpawnBiome", "true")
> RedDesert.removeDecoration("LAKE")
> RedDesert.removeFeature("LAKE")
> RedDesert.addDicType("[color=#ff0000]DESERT[/color]")
> RedDesert.removeDicType("[color=#ff0000]PLAINS[/color]")

but if I go look in the output files I always find this:

> {
>  "ID": 210,
>  "Name": "Vermilion Sands",
>  "Class": "me.superckl.biometweaker.common.world.biome.BiomeTweakerBiome",
>  "Color": 13369395,
>  "Root Height": 1.44,
>  "Height Variation": 0.05,
>  "Top Block": "minecraft:sand",
>  "Filler Block": "minecraft:sand",
>  "Grass Color": "-2106786",
>  "Foliage Color": "-4871594",
>  "Water Color": "16777215",
>  "Temperature": 2.0,
>  "Humidity": 0.0,
>  "Water Tint": 16777215,
>  "Enable Rain": false,
>  "Enable Snow": false,
>  "Dictionary Types": [
>  "HOT",
>  "DRY",
>  "[color=#ff0000]PLAINS[/color]",
>  "SANDY"
>  ],
>  "BiomeManager Entries": {
>  "DESERT Weights": [
>  10
>  ]
>  },
>  "Spawnable Creatures": [  ...

The biome also inerits some additional dictionary types that I did not add o.

**Comment by Zarzuf** [comment]
The additional biome types may be automatically assigned due to the properties of the biomes I coded (?).

For example "PLAINS" only appear in biomes with low heightVariation and "HOT/COLD", "DRY/HUMID" appear in biomes with appropriate temperature and humidity

**Comment by superckl** [comment]
Fixed in 1.8.9 versions. Probably won't backport. Dropping support for 1.8 down due to 1.9.
