### ISSUE TITLE
Incompatible with Recurrent Complex GUI

### ISSUE THREAD

**Issue by Sunconure11** [superckl/BiomeTweaker#78]
http://pastebin.com/f1QNEYBJ

**Comment by superckl** [comment]
Umm, context?

**Comment by Sunconure11** [comment]
Tried to open the recurrent complex gui, when I got to the section that handles biomes, and where a structure can spawn in terms of biomes, I crash with this error.

**Comment by superckl** [comment]
No longer support 1.7.10. If bug still persists in 1.8.9, please let me know and I'll reopen this issue.

**Comment by Sunconure11** [comment]
Recurrent Complex is not on 1.8.9 to my knowledge.
