### ISSUE TITLE
No caves break the surface when top/filler are changed

### ISSUE THREAD

**Issue by keybounce** [superckl/BiomeTweaker#8]
Caves are not breaking the surface if the top/filler are changed.

This is odd -- the code in minecraft for digging blocks is that in most biomes, stone, top, or filler are valid for digging caves. I am specifically looking in a mesa, and the special-case biomes are beach, mushroom island, and desert.

**Comment by superckl** [comment]
Strange. I don't have time currently to play with it, but at first glance it should work fine. There are a few biomes for which topBlock and fillerBlock don't work, namely Hills, mutated Savannah, and special cases of Taiga. I'll look into this.

**Comment by keybounce** [comment]
It's the mesas, more than anything -- the colored clay specifically.

**Comment by superckl** [comment]
Mesas have hard clay hard coded into their generation. If you change the top block, the cave generator derps out since it doesn't recognize the hard clay.

About a fix...err... I'll have to look into it more.

**Comment by keybounce** [comment]
Ok. I'd like a way to select biomes by their class.

For now, I am just going to hardcode a few biome ID numbers. This is the special vanilla biome classes -- deserts (includes hills), mushroom (both kinds), and the mesas (already learned to leave them alone :-) ).

Hmm... Earlier I said that beaches are special-cased in vanilla code. But I'm actually not sure that that's right. Normally, vanilla will carve/dig through stone, filler, or top; but in these special biomes, it only digs in stone, dirt, and grass. I'm still not sure where/how the mesa caving operates, deserts and mushrooms ... hmm, mushrooms I can handle if I leave dirt, but on this map dirt is going to be valuable ... so, they just won't find caves in there. That's all.

**Comment by superckl** [comment]
Fixing this would require overhauling a portion of the generation code, something I'm not going to do with BiomeTweaker. I'm going to consider it as an unfortunate side effect.
