### ISSUE TITLE
Generation stops at 0%

### ISSUE THREAD

**Issue by Danymaddox** [superckl/BiomeTweaker#83]
Hi! Every world I create stops at 0% on my screen. I've tried with only BiomeTweaker but the same ocurrs

**Comment by superckl** [comment]
MC version? BiomeTweaker version? Log file? Scripts? I need information.

**Comment by Danymaddox** [comment]
Sorry here you have:
MC 1.9
Biome Tweaker: 2.1.195
Log: https://mega.nz/#!gV4lzB7K!wOcptbt2ZnESDiFnjMXRLRnUoroYk-JYqj5niw5hY98

**Comment by superckl** [comment]
Wrong log file. I need the 'fml-client-latest' log file. I'm not sure why your generation is stopping. Works fine for me with three different scripts I've tested.

**Comment by Danymaddox** [comment]
Here you have: https://goo.gl/myCD3m

I dint try diferent scripts, Im using the default

**Comment by superckl** [comment]
You can grab a dev build with the fix here

http://jenkins.superckl.me/
