### ISSUE TITLE
[1.7.10]  .set Color(s) not applying 

### ISSUE THREAD

**Issue by MrBloodowrth** [superckl/BiomeTweaker#85]
BiomeTweaker.cfg

{
    //If true, BiomeTweaker will generate separate files for each biome when creating the status report.
    "separate files":true,
    //If true, BiomeTweaker will attempt to retrieve it's listing from NotEnoughMods to perform a version check.
    "version check":false,
    //If true, BiomeTweaker will only perform ASM changes necessary for it to function.
    //Tweaks such as color overrides and block replacement may not work in certain biomes.
    //You can enable this if you are having issues with compatibility.
    "enable light asm":false,
    //Enable this if you want BiomeTweaker to force topBlock and fillerBlock overrides in most biomes.
    //This is done by using ASM to strip some assignments that happen in the "genTerrainBlocks" method. This will not work for all biomes.
    //This WILL cause issues where some biomes will have incorrect top and filler blocks if you do not override them (Extreme Hills (M), Mutated Savannah, Taiga).
    //light ASM must be disabled for this to have any effect.
    "remove late block assignments":false,
    //This can be used to specify biome classes BiomeTweaker should not touch with ASM. You can find the class for a biome in the output files.
    //You should only be using this if you understand what ASM is, and you know the issue it is causing.
    "asm blacklist":[],
    //An array of tweak files to include. An example tweak file is created along with this configuration file.
    "include":["Custom.cfg"]
}

Custom.cfg:

`###########################################################################
# All biomes
# This variable contains all registered biomes from all dimensions.
###### 

allBiomes = forAllBiomes()
###### 
# Overworld biomes
# These variables should contain all Overworld biome IDs.
###### 

overworldBiomes = forAllBiomesExcept(8, 9, 115, 116, 117, 118, 119, 120, 121, 194, 195)
###### 
# Nether biomes
# These variables should contain all Nether biome IDs.
###### 

netherBiomes = forBiomes(8, 115, 116, 117, 118, 119, 120)
###### 
# End biomes
# These variables should contain all End biome IDs.
###### 

endBiomes = forBiomes(9, 121)
###### 
# Ocean biomes
# These variables should contain all oceanic biome IDs.
###### 

oceanBiomes = forBiomes(0, 24, 99, 100)
###### 
# Land biomes
# These variables should contain all land biome IDs.
# Uses forAllBiomesExcept() which means the actual ID parameters should be
# the same oceanic biome IDs used for oceanBiomes above.
###### 

landBiomes = forAllBiomesExcept(0, 24, 99, 100)
###### 
# Vanilla biomes
# Each vanilla biome has its own variable, should you need to reference it.
###### 

vanillaOcean = forBiomes(0)
vanillaPlains = forBiomes(1)
vanillaDesert = forBiomes(2)
vanillaExtremeHills = forBiomes(3)
vanillaForest = forBiomes(4)
vanillaTaiga = forBiomes(5)
vanillaSwampland = forBiomes(6)
vanillaRiver = forBiomes(7)
vanillaHell = forBiomes(8)
vanillaSky = forBiomes(9)
vanillaFrozenOcean = forBiomes(10)
vanillaFrozenRiver = forBiomes(11)
vanillaIcePlains = forBiomes(12)
vanillaIceMountains = forBiomes(13)
vanillaMushroomIsland = forBiomes(14)
vanillaMushroomIslandShore = forBiomes(15)
vanillaBeach = forBiomes(16)
vanillaDesertHills = forBiomes(17)
vanillaForestHills = forBiomes(18)
vanillaTaigaHills = forBiomes(19)
vanillaExtremeHillsEdge = forBiomes(20)
vanillaJungle = forBiomes(21)
vanillaJungleHills = forBiomes(22)
vanillaJungleEdge = forBiomes(23)
vanillaDeepOcean = forBiomes(24)
vanillaStoneBeach = forBiomes(25)
vanillaColdBeach = forBiomes(26)
vanillaBirchForest = forBiomes(27)
vanillaBirchForestHills = forBiomes(28)
vanillaRoofedForest = forBiomes(29)
vanillaColdTaiga = forBiomes(30)
vanillaColdTaigaHills = forBiomes(31)
vanillaMegaTaiga = forBiomes(32)
vanillaMegaTaigaHills = forBiomes(33)
vanillaExtremeHillsPlus = forBiomes(34)
vanillaSavanna = forBiomes(35)
vanillaSavannaPlateau = forBiomes(36)
vanillaMesa = forBiomes(37)
vanillaMesaPlateauF = forBiomes(38)
vanillaMesaPlateau = forBiomes(39)
vanillaSunflowerPlains = forBiomes(129)
vanillaDesertM = forBiomes(130)
vanillaExtremeHillsM = forBiomes(131)
vanillaFlowerForest = forBiomes(132)
vanillaTaigaM = forBiomes(133)
vanillaSwamplandM = forBiomes(134)
vanillaIcePlainsSpikes = forBiomes(140)
vanillaJungleM = forBiomes(149)
vanillaJungleEdgeM = forBiomes(151)
vanillaBirchForestM = forBiomes(155)
vanillaBirchForestHillsM = forBiomes(156)
vanillaRoofedForestM = forBiomes(157)
vanillaColdTaigaM = forBiomes(158)
vanillaMegaSpruceTaiga = forBiomes(160)
vanillaRedwoodTaigaHills = forBiomes(161)
vanillaExtremeHillsPlusM = forBiomes(162)
vanillaSavannaM = forBiomes(163)
vanillaSavannaPlateauM = forBiomes(164)
vanillaMesaBryce = forBiomes(165)
vanillaMesaPlateauFM = forBiomes(166)
vanillaMesaPlateauM = forBiomes(167)

bopAlps = forBiomes(40)
bopArctic = forBiomes(41)
bopBambooForest = forBiomes(42)
bopBayou = forBiomes(43)
bopBog = forBiomes(44)
bopBorealForest = forBiomes(45)
bopBrushland = forBiomes(46)
bopCanyon = forBiomes(47)
bopChaparral = forBiomes(48)
bopCherryBlossomGrove = forBiomes(49)
bopConiferousForest = forBiomes(50)
bopSnowyConiferousForest = forBiomes(51)
bopCrag = forBiomes(52)
bopDeadForest = forBiomes(53)
bopDeadSwamp = forBiomes(54)
bopDeciduousForest = forBiomes(55)
bopDenseForest = forBiomes(56)
bopEucalyptusForest = forBiomes(57)
bopFen = forBiomes(58)
bopFlowerField = forBiomes(59)
bopFrostForest = forBiomes(60)
bopFungiForest = forBiomes(61)
bopGarden = forBiomes(62)
bopGrassland = forBiomes(63)
bopGrove = forBiomes(64)
bopHeathland = forBiomes(65)
bopHighland = forBiomes(66)
bopJadeCliffs = forBiomes(67)
bopLandofLakes = forBiomes(68)
bopLavenderFields = forBiomes(69)
bopLushDesert = forBiomes(70)
bopLushSwamp = forBiomes(71)
bopMapleWoods = forBiomes(72)
bopMarsh = forBiomes(73)
bopMeadow = forBiomes(74)
bopMoor = forBiomes(75)
bopMountain = forBiomes(76)
bopMysticGrove = forBiomes(77)
bopOminousWoods = forBiomes(78)
bopOrchard = forBiomes(79)
bopOriginValley = forBiomes(80)
bopOutback = forBiomes(81)
bopPrairie = forBiomes(82)
bopRainforest = forBiomes(83)
bopRedwoodForest = forBiomes(84)
bopSacredSprings = forBiomes(85)
bopSeasonalForest = forBiomes(86)
bopShield = forBiomes(87)
bopShrubland = forBiomes(88)
bopSludgepit = forBiomes(89)
bopSteppe = forBiomes(90)
bopTemperateRainforest = forBiomes(91)
bopThicket = forBiomes(92)
bopTropicalRainforest = forBiomes(93)
bopTundra = forBiomes(94)
bopWasteland = forBiomes(95)
bopWetland = forBiomes(96)
bopWoodland = forBiomes(97)
bopXericShrubland = forBiomes(98)
bopCoralReef = forBiomes(99)
bopKelpForest = forBiomes(100)
bopTropics = forBiomes(101)
bopVolcano = forBiomes(102)
bopMangrove = forBiomes(103)
bopAlpsForest = forBiomes(104)
bopCanyonRavine = forBiomes(105)
bopGlacier = forBiomes(106)
bopLandofLakesMarsh = forBiomes(107)
bopMeadowForest = forBiomes(108)
bopOasis = forBiomes(109)
bopQuagmire = forBiomes(110)
bopScrubland = forBiomes(111)
bopSeasonalForestClearing = forBiomes(112)
bopSilkglades = forBiomes(113)
bopSpruceWoods = forBiomes(114)
bopCorruptedSands = forBiomes(115)
bopPhantasmagoricInferno = forBiomes(116)
bopBoneyard = forBiomes(117)
bopVisceralHeap = forBiomes(118)
bopUndergarden = forBiomes(119)
bopPolarChasm = forBiomes(120)
bopSpectralGarden = forBiomes(121)
bopLushRiver = forBiomes(122)
bopDryRiver = forBiomes(123)

tcTaintedLand = forBiomes(192)
tcMagicalForest = forBiomes(193)
tcEerie = forBiomes(194)
tcEldritch = forBiomes(195)
###### 
# Icy overworld biomes
# These variables should contain all ICY overworld biome IDs.
###### 

vanillaIcyOverworldBiomes = forBiomes(11, 12, 13, 26, 30, 31, 140, 158)
bopIcyOverworldBiomes = forBiomes(40, 41, 51, 60, 104, 106)
###### 
# Cool overworld biomes
# These variables should contain all COOL overworld biome IDs.
###### 

vanillaCoolOverworldBiomes = forBiomes(0, 3, 5, 19, 24, 25, 32, 33, 34, 131, 133, 160, 161, 162)
bopCoolOverworldBiomes = forBiomes(72, 94)
###### 
# Warm overworld biomes
# These variables should contain all WARM overworld biome IDs.
###### 

vanillaWarmOverworldBiomes = forBiomes(1, 4, 6, 7, 14, 15, 16, 18, 21, 22, 23, 27, 28, 29, 129, 132, 134, 149, 151, 155, 156, 157)
bopWarmOverworldBiomes = forBiomes(43, 44, 45, 47, 48, 49, 50, 52, 53, 54, 55, 56, 57, 58, 59, 61, 62, 63, 64, 65, 66, 67, 68, 69, 71, 73, 74, 75, 76, 77, 78, 79, 80, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 95, 96, 97, 98, 99, 100, 103, 105, 107, 108, 110, 112, 113, 114, 122, 123)
tcWarmOverworldBiomes = forBiomes(192, 193)
###### 
# Desert overworld biomes
# These variables should contain all DESERT overworld biome IDs.
###### 

vanillaDesertOverworldBiomes = forBiomes(2, 17, 35, 36, 37, 38, 39, 130, 163, 164, 165, 166, 167)
bopDesertOverworldBiomes = forBiomes(42, 46, 70, 81, 93, 101, 102, 109, 111)
###### 
# Add all Overworld biomes to the biome pool with a default weight of 1.
# This needs to appear BEFORE biome weights are set.
###### 

vanillaIcyOverworldBiomes.addToGeneration("ICY", 1)
vanillaCoolOverworldBiomes.addToGeneration("COOL", 1)
vanillaWarmOverworldBiomes.addToGeneration("WARM", 1)
vanillaDesertOverworldBiomes.addToGeneration("DESERT", 1)

bopIcyOverworldBiomes.addToGeneration("ICY", 1)
bopCoolOverworldBiomes.addToGeneration("COOL", 1)
bopWarmOverworldBiomes.addToGeneration("WARM", 1)
bopDesertOverworldBiomes.addToGeneration("DESERT", 1)

tcWarmOverworldBiomes.addToGeneration("WARM", 1)
###### 
# Biome weights
# Controls how frequently biomes are generated.
# You may change the weights to whatever you want.
# Weights must be non-negative integers.
###### 

vanillaBeach.set("genWeight", 1)
vanillaBirchForest.set("genWeight", 10)
vanillaBirchForestHills.set("genWeight", 8)
vanillaBirchForestHillsM.set("genWeight", 4)
vanillaBirchForestM.set("genWeight", 4)
vanillaColdBeach.set("genWeight", 1)
vanillaColdTaiga.set("genWeight", 10)
vanillaColdTaigaHills.set("genWeight", 8)
vanillaColdTaigaM.set("genWeight", 4)
vanillaDeepOcean.set("genWeight", 2)
vanillaDesert.set("genWeight", 10)
vanillaDesertHills.set("genWeight", 8)
vanillaDesertM.set("genWeight", 4)
vanillaExtremeHills.set("genWeight", 10)
vanillaExtremeHillsM.set("genWeight", 4)
vanillaExtremeHillsPlus.set("genWeight", 4)
vanillaExtremeHillsPlusM.set("genWeight", 2)
vanillaFlowerForest.set("genWeight", 4)
vanillaForest.set("genWeight", 10)
vanillaForestHills.set("genWeight", 8)
vanillaFrozenRiver.set("genWeight", 1)
vanillaIceMountains.set("genWeight", 2)
vanillaIcePlains.set("genWeight", 10)
vanillaIcePlainsSpikes.set("genWeight", 1)
vanillaJungle.set("genWeight", 10)
vanillaJungleEdge.set("genWeight", 4)
vanillaJungleEdgeM.set("genWeight", 2)
vanillaJungleHills.set("genWeight", 8)
vanillaJungleM.set("genWeight", 4)
vanillaMegaSpruceTaiga.set("genWeight", 4)
vanillaMegaTaiga.set("genWeight", 10)
vanillaMegaTaigaHills.set("genWeight", 8)
vanillaMesa.set("genWeight", 1)
vanillaMesaBryce.set("genWeight", 1)
vanillaMesaPlateau.set("genWeight", 1)
vanillaMesaPlateauF.set("genWeight", 1)
vanillaMesaPlateauFM.set("genWeight", 1)
vanillaMesaPlateauM.set("genWeight", 1)
vanillaMushroomIsland.set("genWeight", 1)
vanillaMushroomIslandShore.set("genWeight", 1)
vanillaOcean.set("genWeight", 2)
vanillaPlains.set("genWeight", 10)
vanillaRiver.set("genWeight", 1)
vanillaRoofedForest.set("genWeight", 8)
vanillaRoofedForestM.set("genWeight", 4)
vanillaSavanna.set("genWeight", 10)
vanillaSavannaM.set("genWeight", 4)
vanillaSavannaPlateau.set("genWeight", 6)
vanillaSavannaPlateauM.set("genWeight", 2)
vanillaStoneBeach.set("genWeight", 1)
vanillaSunflowerPlains.set("genWeight", 4)
vanillaSwampland.set("genWeight", 10)
vanillaSwamplandM.set("genWeight", 4)
vanillaTaiga.set("genWeight", 10)
vanillaTaigaHills.set("genWeight", 8)
vanillaTaigaM.set("genWeight", 4)

bopAlps.set("genWeight", 5)
bopArctic.set("genWeight", 5)
bopBambooForest.set("genWeight", 5)
bopBayou.set("genWeight", 5)
bopBog.set("genWeight", 5)
bopBorealForest.set("genWeight", 5)
bopBrushland.set("genWeight", 5)
bopCanyon.set("genWeight", 5)
bopChaparral.set("genWeight", 5)
bopCherryBlossomGrove.set("genWeight", 5)
bopConiferousForest.set("genWeight", 5)
bopSnowyConiferousForest.set("genWeight", 5)
bopCrag.set("genWeight", 5)
bopDeadForest.set("genWeight", 5)
bopDeadSwamp.set("genWeight", 5)
bopDeciduousForest.set("genWeight", 5)
bopDenseForest.set("genWeight", 5)
bopEucalyptusForest.set("genWeight", 5)
bopFen.set("genWeight", 5)
bopFlowerField.set("genWeight", 5)
bopFrostForest.set("genWeight", 5)
bopFungiForest.set("genWeight", 5)
bopGarden.set("genWeight", 5)
bopGrassland.set("genWeight", 5)
bopGrove.set("genWeight", 5)
bopHeathland.set("genWeight", 5)
bopHighland.set("genWeight", 5)
bopJadeCliffs.set("genWeight", 5)
bopLandofLakes.set("genWeight", 5)
bopLavenderFields.set("genWeight", 5)
bopLushDesert.set("genWeight", 5)
bopLushSwamp.set("genWeight", 5)
bopMapleWoods.set("genWeight", 5)
bopMarsh.set("genWeight", 5)
bopMeadow.set("genWeight", 5)
bopMoor.set("genWeight", 5)
bopMountain.set("genWeight", 5)
bopMysticGrove.set("genWeight", 5)
bopOminousWoods.set("genWeight", 5)
bopOrchard.set("genWeight", 5)
bopOriginValley.set("genWeight", 5)
bopOutback.set("genWeight", 5)
bopPrairie.set("genWeight", 5)
bopRainforest.set("genWeight", 5)
bopRedwoodForest.set("genWeight", 5)
bopSacredSprings.set("genWeight", 5)
bopSeasonalForest.set("genWeight", 5)
bopShield.set("genWeight", 5)
bopShrubland.set("genWeight", 5)
bopSludgepit.set("genWeight", 5)
bopSteppe.set("genWeight", 5)
bopTemperateRainforest.set("genWeight", 5)
bopThicket.set("genWeight", 5)
bopTropicalRainforest.set("genWeight", 5)
bopTundra.set("genWeight", 5)
bopWasteland.set("genWeight", 5)
bopWetland.set("genWeight", 5)
bopWoodland.set("genWeight", 5)
bopXericShrubland.set("genWeight", 5)
bopCoralReef.set("genWeight", 5)
bopKelpForest.set("genWeight", 5)
bopTropics.set("genWeight", 5)
bopVolcano.set("genWeight", 5)
bopMangrove.set("genWeight", 5)
bopAlpsForest.set("genWeight", 5)
bopCanyonRavine.set("genWeight", 5)
bopGlacier.set("genWeight", 5)
bopLandofLakesMarsh.set("genWeight", 5)
bopMeadowForest.set("genWeight", 5)
bopOasis.set("genWeight", 5)
bopQuagmire.set("genWeight", 5)
bopScrubland.set("genWeight", 5)
bopSeasonalForestClearing.set("genWeight", 5)
bopSilkglades.set("genWeight", 5)
bopSpruceWoods.set("genWeight", 5)

tcTaintedLand.set("genWeight", 5)
tcMagicalForest.set("genWeight", 5)
###### 
# Set the biome size for the "Realistic" world type
# Default is 4; Large Biomes is 6
###### 

Tweaker.setAverageBiomeSize("RTG", 4)
###### 
# Set the biomes that players can spawn in
# By default, players may spawn in any land biome.
# You may use any of the variables above to set spawn biomes.
# For example:
# vanillaFlowerForest.set("isSpawnBiome", true)
# overworldBiomes.set("isSpawnBiome", true)
# vanillaIcyOverworldBiomes.set("isSpawnBiome", false)
###### 

oceanBiomes.set("isSpawnBiome", false)
landBiomes.set("isSpawnBiome", true)
###### 
# Remove biomes from generation
# River biomes must be removed here, but they will still generate.
###### 

vanillaExtremeHillsEdge.remove()
vanillaFrozenOcean.remove()
vanillaRiver.remove()
vanillaFrozenRiver.remove()

bopLushRiver.remove()
bopDryRiver.remove()
# Biome Colors

tcTaintedLand.set("color", 10964349) 
tcTaintedLand.set("Grass Color", 10964349)
tcTaintedLand.set("Foliage Color", 10964349)
tcTaintedLand.set("Water Color", 10964349)
tcTaintedLand.set("skyColor", 10964349)

`
fml-server-latest.log:
https://dl.dropboxusercontent.com/u/1725660/Minecraft/1-Minecraftia_2016/Biometweaker%20Report/fml-server-latest.log

Relevant console output:

`[13:54:25] [Server thread/WARN] [BiomeTweaker]: Attempted to set property Grass Color but corresponding property was not found for biomes. Value: 10964349
[13:54:25] [Server thread/WARN] [BiomeTweaker]: Attempted to set property Foliage Color but corresponding property was not found for biomes. Value: 10964349
[13:54:25] [Server thread/WARN] [BiomeTweaker]: Attempted to set property Water Color but corresponding property was not found for biomes. Value: 10964349
[13:54:25] [Server thread/WARN] [BiomeTweaker]: Attempted to set property skyColor but corresponding property was not found for biomes. Value: 10964349
[13:54:25] [Server thread/INFO] [BiomeTweaker]: Generating biome status report...
`

**Comment by superckl** [comment]
I told you to change the end to

```
#Biome Colors
tcTaintedLand.set("color", 10964349) 
tcTaintedLand.set("grassColor", 10964349)
tcTaintedLand.set("foliageColor", 10964349)
tcTaintedLand.set("waterColor", 10964349)
tcTaintedLand.set("skyColor", 10964349)
```

Read carefully. The field names must match. Furthermore, skyColor isn't a field you can set in 1.7.10.

**Comment by MrBloodowrth** [comment]
I see it now. I think the issue was I copied from the output file, witch uses that formatting.

IE:
`{
  "ID": 192,
  "Name": "Tainted Land",
  "Class": "thaumcraft.common.lib.world.biomes.BiomeGenTaint",
  "Color": 10964349,
  "Root Height": 0.1,
  "Height Variation": 0.2,
  "Top Block": "minecraft:grass",
  "Filler Block": "minecraft:dirt",
  "Grass Color": "Not set. Check in-game.",
  "Foliage Color": "Not set. Check in-game.",
  "Water Color": "13373832",
  "Temperature": 0.5,
  "Humidity": 0.5,
  "Water Tint": 16777215,
  "Enable Rain": true,
  "Enable Snow": false,
  "Dictionary Types": [
    "MAGICAL",
    "WASTELAND"
  ],
`
