### ISSUE TITLE
[Suggestion] Disable village generation

### ISSUE THREAD

**Issue by ubermentat** [superckl/BiomeTweaker#9]
If it's at all possible (or already possible and I just can't find it), would you be able to add the ability to disable village generation on a per-biome/per-biome group basis?

**Comment by superckl** [comment]
Should be fairly easy. Seems to be a Forge method to do this. I'll let you know when it's implemented.

**Comment by superckl** [comment]
Ability to disable village generation:

http://jenkins.superckl.me/job/BiomeTweaker/73/

Will close this issue when 0.9 is released.

**Comment by superckl** [comment]
http://minecraft.curseforge.com/mc-mods/228895-biometweaker/files/2238153
