### ISSUE TITLE
I don't know how to code!

### ISSUE THREAD

**Issue by mchetvorka** [superckl/BiomeTweaker#91]
Hello, i found this mod earlier today. So the problem was that i downloaded Biomes o Planty and when i generate a world it still spawns me in a vanilla biome and some shitty vanilla looking like biome from BoP so i tried to find a solution. The problem is that i don't know how to remove/replace the vanilla biomes because i suck at coding and there aren't any tutorials. I was wondering if you could help. Thanks alot!

**Comment by superckl** [comment]
This is probably not the mod for you then. I would recommend Climate Control. Much less scripting.
