### ISSUE TITLE
Biome weights not being adhered to

### ISSUE THREAD

**Issue by Zygus42** [superckl/BiomeTweaker#92]
I'm using this mod in 1.10.2 together with Realistic Terrain Generation and Biomes O Plenty.  Latest versions of all.

I've been trying to put together a new world, so I've been flying around testing quite extensively, but I keep seeing just the same 10 or so biomes over and over - some are vanilla Minecraft, and some are BoP.  I've attached the file i'm using to define the weights etc.  Am I doing something wrong in the file, or is there some kind of issue with reading the weighting ?

[RTG.zip](https://github.com/superckl/BiomeTweaker/files/433638/RTG.zip)

**Comment by superckl** [comment]
I'm not entirely sure, but it seems like BOP for 1.10 is ignoring most of BT's generation tweaks. I'll look into it.

**Comment by Zygus42** [comment]
I think it's just gotten better with the latest BoP update - was just testing it:
         "BoP Build 1.10.2-5.0.0.2075:    Adubbz: Fixed a problem with biome configs not working"

Still doesn't feel 100% right, but is definitely better.

**Comment by justfinley** [comment]
has there been any discoveries? 

I have been trying to get heavier weights for the past 3 days with BOP biomes on my worlds. No luck.

**Comment by superckl** [comment]
If the BOP configs aren't working for setting weights of BOP biomes, I can't really help you right now unfortunately. Don't have time to look into this right now.

**Comment by superckl** [comment]
Going to close this with the latest addittions. Commands have been added to allow tweaking in the BOP world type.
