### ISSUE TITLE
I tried to replace netherrack with snow, it worked too well

### ISSUE THREAD

**Issue by itanshi** [superckl/BiomeTweaker#96]
It also replaced all non pool lava, gravel, and soul sand with snow

hellBiome.registerGenBlockRep("minecraft:netherrack", "minecraft:snow", 1)

This happens whether I add this or not (I'm under the impression that this code is pointless)
hellBiome.registerGenBlockRep("minecraft:soul_sand", "minecraft:ice", 1)
hellBiome.registerGenBlockRep("minecraft:gravel", "minecraft:packed_ice", 1)

Of course, I'd like its intention to work, somehow. thank you.

**BT for 1.7.10 version 2.0.182**

**Comment by superckl** [comment]
lava, gravel, and soul sand are placed over netherrack in the nether. If there is no netherrack, they won't be placed. I'm not really sure how to go about fixing that...

**Comment by itanshi** [comment]
maybe run the replacement of netherrack again for those two and then netherrack? thought i saw a timing related command, but i've not used them before.

edit: Oh, what if I ran a snow replacement to reintroduce blocks to the biome (using cofh core, i can readd the blocks)

**Comment by bookerthegeek** [comment]
COFH core would work, also Condensed ores from Reika would work.
