### ISSUE TITLE
Configuration feature Biome.registerGenBiomeRep not working.

### ISSUE THREAD

**Issue by TitusArmillius** [superckl/BiomeTweaker#97]
deserthillsBiome = forBiomes(17)
highlandBiome = forBiomes(60)
deserthillsBiome.registerGenBiomeRep(highlandBiome)

the above code should replace the sub-biome desert hills with the biome highlands from BOP, I have doubled checked that the biome names and ID's are correct, there I presume since it has not worked that there is a bug.

**Comment by superckl** [comment]
I need a full client log to help you out.

**Comment by TitusArmillius** [comment]
@superckl here is the full log https://gist.githubusercontent.com/TitusArmillius/e77c8ba78d7a2589f15fa901f5ac0d21/raw/6dd79de6f5969388cf4ab3ef0f7021f7ea7b2f01/Game%2520log%2520(minecraft)

**Comment by superckl** [comment]
Your log says it's applying 18 tweaks. Is there more to your script?

**Comment by TitusArmillius** [comment]
@superckl Here is my script http://pastebin.com/WB4f9A63.

Also, lets say now I want to make the BOP xeric_shrubland biome a sub-biome of the desert instead of Desert Hills. If I enter the following script, will it work?

deserthillsBiome = forBiomes(17)
xericshrublandBiome = forBiomes(92)
deserthillsBiome.registerGenBiomeRep(xericshrublandBiome)

**Comment by superckl** [comment]
Sorry, school has me busy...

That script will not do what you want. That functionality does not exist in BiomeTweaker yet. I'll be sure to add it when I get around to fleshing out the BOP integration some more.

**Comment by superckl** [comment]
Sub-biome modification is now a feature. Closing this.
