### ISSUE TITLE
How do I assign a biome to a different dimension?

### ISSUE THREAD

**Issue by Winddbourne** [superckl/BiomeTweaker#98]
The only tweak I really want to make to many biomes is where they generate. 

For example I have the Eribus in my mod pack . . . instead of having the hell biome generate in the nether I'd rather disable nether portals and have that biome generate in the Eribus making a single interesting underworld dimension for players to explore while also saving a server from having to generate chunks for two cave dimensions.

Another example along the same lines . . . I have the Atum and the Twilight forest . . . the atum has ONE biome in it and thus isn't very interesting on its own. It's just forcing chunks to generate and wasting server space. However if I add that single biome to the twilight forest I get a more interesting unified adventure dimension filled with mazes, towers, caverns, and pyramids. I think that might work out quite nicely. 

Even when I want to create a new biome I don't want to do it in the over world. It should be easy to create a cave dimension version of the end . . . perhaps have the real filler block be endstone, and the filler block be mycelium . . . replace the water with cryotheum from lycanites mobs for a real darkness and cold flavored biome to complement adding the nether into the Erebus while also allowing me to close off the end. It seems like it could be a good idea. 

But I don't see how to do it. The shape of the code seems to suggest that there is a variable somewhere that is defaulting to zero. But I can't find any reference as to where I'm supposed to add ",-1" or "77", or whatever. 

I send you a PM on curse a while back but I noticed you haven't been on there since october so I figure asking here may be more convenient.

**Comment by superckl** [comment]
Short answer is you can't.

Long answer (that I doubt I'll ever do) is that you could heavily modify the existing the generation code to provide dimensional information to subclasses. Not to mention this would almost certainly break with the addition of other mods.

Maybe sometime in the future this will be a feature, but not currently.
